### ISSUE TITLE
REQUEST: New membership for daniel-codefresh

### ISSUE THREAD

**Issue by daniel-codefresh** [argoproj/argoproj#102]
### GitHub Username
@daniel-codefresh

### Organization you are requesting membership in
@argoproj

### Requirements
- [x] I have reviewed the community membership guidelines (https://github.com/argoproj/argoproj/blob/master/community/membership.md)
- [x] I have enabled 2FA on my GitHub account (https://github.com/settings/security)
- [x] I am actively contributing to 1 or more Argoproj subprojects
- [x] I have two sponsors that meet the sponsor requirements listed in the community membership guidelines
- [x] I have spoken to my sponsors ahead of this application, and they have agreed to sponsor my application

### Sponsors
- @whynowy 
- @edlee2121 

### List of contributions to the Argoproj project
- PRs reviewed / authored
- https://github.com/argoproj/argo-events/pull/1323
- https://github.com/argoproj/argo-events/pull/1324
- https://github.com/argoproj/argo-events/pull/1333
- https://github.com/argoproj/argo-events/pull/1398
- https://github.com/argoproj/argo-events/pull/1402
- https://github.com/argoproj/argo-events/pull/1403
- https://github.com/argoproj/argo-events/pull/1412
- https://github.com/argoproj/argo-events/pull/1421
- https://github.com/argoproj/argo-events/pull/1433
- https://github.com/argoproj/argo-events/pull/1434
- https://github.com/argoproj/argo-events/pull/1438
- https://github.com/argoproj/argo-events/pull/1440
- Issues responded to
- https://github.com/argoproj/argo-events/issues/1418
- https://github.com/argoproj/argo-events/issues/1439
- https://github.com/argoproj/argo-events/issues/1393
- https://github.com/argoproj/argo-events/issues/1423
- https://github.com/argoproj/argo-events/issues/1432
- https://github.com/argoproj/argo-events/issues/1416
- Projects I am involved with: Argo Events

**Comment by whynowy** [comment]
+1

**Comment by edlee2121** [comment]
+1

**Comment by whynowy** [comment]
@alexec

**Comment by alexec** [comment]
Invite sent.

**Comment by daniel-codefresh** [comment]
Thanks you guys! @alexec @whynowy @edlee2121
