### ISSUE TITLE
REQUEST: New membership for @dpadhiar

### ISSUE THREAD

**Issue by dpadhiar** [argoproj/argoproj#104]
### GitHub Username
@dpadhiar

### Organization you are requesting membership in
@argoproj

### Requirements
- [x] I have reviewed the community membership guidelines (https://github.com/argoproj/argoproj/blob/master/community/membership.md)
- [x] I have enabled 2FA on my GitHub account (https://github.com/settings/security)
- [x] I am actively contributing to 1 or more Argoproj subprojects
- [x] I have two sponsors that meet the sponsor requirements listed in the community membership guidelines
- [x] I have spoken to my sponsors ahead of this application, and they have agreed to sponsor my application

### Sponsors
- @sarabala1979 
- @whynowy 

### List of contributions to the Argoproj project

- PRs authored: https://github.com/argoproj/argo-workflows/pulls?q=is%3Apr+is%3Aclosed+author%3Adpadhiar - https://github.com/argoproj/argo-events/pulls?q=is%3Apr+is%3Aclosed+author%3Adpadhiar
- Issues responded to: https://github.com/argoproj/argo-workflows/issues?q=is%3Aissue+dpadhiar+is%3Aclosed
- Projects I am involved with: argo-workflows and argo-events

**Comment by whynowy** [comment]
+1

**Comment by sarabala1979** [comment]
+1

**Comment by terrytangyuan** [comment]
+1

**Comment by alexec** [comment]
Is this still open for a reason?

**Comment by sarabala1979** [comment]
In the last meeting, members need to be at least two months. So we need to wait for one month. I think he is good for now. @jessesuen @alexmt

**Comment by alexec** [comment]
Another months has passed.

**Comment by alexec** [comment]
Invite sent.
