### ISSUE TITLE
REQUEST: New membership for JPZ13

### ISSUE THREAD

**Issue by JPZ13** [argoproj/argoproj#113]
### GitHub Username
[JPZ13](https://github.com/JPZ13/)

### Organization you are requesting membership in
[argoproj](https://github.com/argoproj)

### Requirements
- [x] I have reviewed the community membership guidelines (https://github.com/argoproj/argoproj/blob/master/community/membership.md)
- [x] I have enabled 2FA on my GitHub account (https://github.com/settings/security)
- [x] I am actively contributing to 1 or more Argoproj subprojects
- [x] I have two sponsors that meet the sponsor requirements listed in the community membership guidelines
- [x] I have spoken to my sponsors ahead of this application, and they have agreed to sponsor my application

### Sponsors
- @alexec 
- @terrytangyuan 

### List of contributions to the Argoproj project

**PRs reviewed / authored**
- [Upgrade kube client](https://github.com/argoproj/argo-workflows/pull/4810)
- [Add slack exit handler example](https://github.com/argoproj/argo-workflows/pull/6612)
- [Initial pod names v2 commit](https://github.com/argoproj/argo-workflows/pull/6712)
- [UI pod names v2](https://github.com/argoproj/argo-workflows/pull/6925)
- [UI pod names v2 tests](https://github.com/argoproj/argo-workflows/pull/6954)
- [Pod names workflow annotations](https://github.com/argoproj/argo-workflows/pull/6982)
- [CLI pod names v2 support](https://github.com/argoproj/argo-workflows/pull/7653)

**Issues responded to**
[JPZ13 mentions in issues](https://github.com/issues?q=is%3Aissue+mentions%3AJPZ13+archived%3Afalse+user%3Aargoproj)

Thank you, @terrytangyuan for showing me that link!

**Projects I am involved with**
- Workflows

**Comment by alexec** [comment]
+1

**Comment by alexec** [comment]
> Once your sponsors have responded, your request will be reviewed by the project leads. Any missing information will be requested.

@alexmt remind me, what is next step?

**Comment by alexec** [comment]
Invite sent.
