### ISSUE TITLE
REQUEST: New membership for juliev0 (Julie Vogelman)

### ISSUE THREAD

**Issue by juliev0** [argoproj/argoproj#124]
### GitHub Username
juliev0

### Organization you are requesting membership in
argo-events @ argo-proj

### Requirements
- [x] I have reviewed the community membership guidelines (https://github.com/argoproj/argoproj/blob/master/community/membership.md)
- [x] I have enabled 2FA on my GitHub account (https://github.com/settings/security)
- [x] I am actively contributing to 1 or more Argoproj subprojects
- [x] I have two sponsors that meet the sponsor requirements listed in the community membership guidelines
- [x] I have spoken to my sponsors ahead of this application, and they have agreed to sponsor my application

### Sponsors
- Derek Wang
- Saravanan Balasubramanian

### List of contributions to the Argoproj project
Contributed all of these PRs, all from argo-events:
- [1783](https://github.com/argoproj/argo-events/pull/1783): Major change to incorporate NATS Jetstream as the bus
- [1585](https://github.com/argoproj/argo-events/pull/1585): Enable Conditions Reset capability to work even in the case of the Sensor being down at the cron-defined time
- [1701](https://github.com/argoproj/argo-events/pull/1701): Fixed Regression submitted by user involving messages sent in quick succession not all triggering (with 1 day turn around time)
- [1600](https://github.com/argoproj/argo-events/pull/1600): AMQP Username/Password Authentication
- couple of PRs related to documentation clarification: [1736](https://github.com/argoproj/argo-events/pull/1736) and [1722](https://github.com/argoproj/argo-events/pull/1722)

**Comment by whynowy** [comment]
+1

**Comment by sarabala1979** [comment]
+1

**Comment by alexec** [comment]
@juliev0 you should have an invite in your inbox.
