### ISSUE TITLE
REQUEST: New membership for rishabh625 (Rishabh Mishra)

### ISSUE THREAD

**Issue by rishabh625** [argoproj/argoproj#127]
### GitHub Username

rishabh625

### Organization you are requesting membership in
argo-cd@argoproj

### Requirements
- [x] I have reviewed the community membership guidelines (https://github.com/argoproj/argoproj/blob/master/community/membership.md)
- [x] I have enabled 2FA on my GitHub account (https://github.com/settings/security)
- [x] I am actively contributing to 1 or more Argoproj subprojects
- [x] I have two sponsors that meet the sponsor requirements listed in the community membership guidelines
- [x] I have spoken to my sponsors ahead of this application, and they have agreed to sponsor my application

### Sponsors
- Jann Fischer
- Michael Crenshaw (crenshaw-dev)
- pasha-codefresh

### List of contributions to the Argoproj project
- PRs authored
[](url)
https://github.com/argoproj/argo-cd/pull/8412
https://github.com/argoproj/argo-cd/pull/8645
https://github.com/argoproj/argo-cd/pull/8864
https://github.com/argoproj/argo-cd/pull/8933
https://github.com/argoproj/argo-cd/pull/8954
https://github.com/argoproj/argo-cd/pull/8955
https://github.com/argoproj/argo-cd/pull/9087
https://github.com/argoproj/argo-cd/pull/9140
https://github.com/argoproj/argo-cd/pull/9150
https://github.com/argoproj/argo-cd/pull/9151
https://github.com/argoproj/argo-cd/pull/9179

- PRs reviewed
[](url)
https://github.com/argoproj/argo-cd/pull/9228
https://github.com/argoproj/argo-cd/pull/9080
https://github.com/argoproj/argo-cd/pull/9037
https://github.com/argoproj/argo-cd/pull/8991

- Issues responded to
[](url)
https://github.com/argoproj/argo-cd/issues/8982
https://github.com/argoproj/argo-cd/issues/8774
https://github.com/argoproj/argo-cd/issues/8781
https://github.com/argoproj/argo-cd/issues/9028
https://github.com/argoproj/argo-cd/issues/7512

**Comment by pasha-codefresh** [comment]
+ me as sponsor, great job!

**Comment by rishabh625** [comment]
> +me as sponsor, great job!

Thanks :)

**Comment by rishabh625** [comment]
Any Update on This?

**Comment by alexec** [comment]
Membership invite sent.

**Comment by alexec** [comment]
Welcome!

**Comment by rishabh625** [comment]
Thanks @alexec !!
And thanks to sponsors too
@jannfis @crenshaw-dev @pasha-codefresh
