### ISSUE TITLE
REQUEST: New membership for caelan-io

### ISSUE THREAD

**Issue by caelan-io** [argoproj/argoproj#128]
### GitHub Username
@caelan-io

### Organization you are requesting membership in
@argoproj

### Requirements
- [x] I have reviewed the community membership guidelines (https://github.com/argoproj/argoproj/blob/master/community/membership.md)
- [x] I have enabled 2FA on my GitHub account (https://github.com/settings/security)
- [x] I am actively contributing to 1 or more Argoproj subprojects
- [x] I have two sponsors that meet the sponsor requirements listed in the community membership guidelines
- [x] I have spoken to my sponsors ahead of this application, and they have agreed to sponsor my application

### Sponsors
- @alexec 
- @terrytangyuan 
- @sarabala1979 

### List of contributions to the Argoproj project
PRs reviewed / authored
- [Docs for Lifecycle Hooks](https://github.com/argoproj/argo-workflows/pull/8069) 
- [Edited Argo Workflows v3.3 release blog post](https://blog.argoproj.io/whats-new-in-argo-workflows-v3-3-dd051d2f1c7)

Issues responded to
- [Mentions in issues](https://github.com/issues?q=is%3Aissue+mentions%3Acaelan-io+archived%3Afalse+user%3Aargoproj+)
- [Additional issue](https://github.com/argoproj/argo-workflows/issues/7745)
- Responding in CNCF Slack as [at]Caelan [[1](https://cloud-native.slack.com/archives/C01QW9QSSSK/p1653058382580509?thread_ts=1651677256.776659&cid=C01QW9QSSSK)], [[2](https://cloud-native.slack.com/archives/C01QW9QSSSK/p1653056919085199?thread_ts=1652899585.803539&cid=C01QW9QSSSK)], [[3](https://cloud-native.slack.com/archives/C01QW9QSSSK/p1652887804170179?thread_ts=1652479265.686589&cid=C01QW9QSSSK)], [[4](https://cloud-native.slack.com/archives/C01QW9QSSSK/p1651241685435529?thread_ts=1651193773.436059&cid=C01QW9QSSSK)], [[5](https://cloud-native.slack.com/archives/C018DMLMPEH/p1651235708291659?thread_ts=1650925964.863179&cid=C018DMLMPEH)] are a few recent examples

Projects I am involved with
- Argo Workflows
- Argo Conformance

Other activities
- Argo Data Weekly scrum meetings
- Argo Workflows Monthly Community meetings
- Argo Conformance meetings
- Collecting feedback for multi-cluster workflow feature development

**Comment by terrytangyuan** [comment]
+1

**Comment by alexec** [comment]
Membership invite sent.

**Comment by caelan-io** [comment]
Thank you! @terrytangyuan @alexec
