### ISSUE TITLE
Link to Slack space does not work

### ISSUE THREAD

**Issue by tmplcl** [argoproj/argoproj#134]
I am not getting an invitation to the Argo Slack space when using this link: https://slack.cncf.io/

The following error occurs:

<img width="1384" alt="image" src="https://user-images.githubusercontent.com/56223564/170471104-37299a82-a038-4ac0-a9fb-f4562b5e3a8d.png">

**Comment by edlee2121** [comment]
Yes, unfortunately the link expires each time a certain number of people have joined and then we have to wait for CNCF to fix it again. They should just update their link every month before it expires.
