### ISSUE TITLE
REQUEST: Promotion for zachaller to approver for Argo Rollouts / Reviewer ArgoCD

### ISSUE THREAD

**Issue by zachaller** [argoproj/argoproj#136]
### GitHub Username
@zachaller

### Organization you are requesting membership in
argoproj

### Requirements
- [x] I have reviewed the community membership guidelines (https://github.com/argoproj/argoproj/blob/master/community/membership.md)
- [x] I have enabled 2FA on my GitHub account (https://github.com/settings/security)
- [x] I am actively contributing to 1 or more Argoproj subprojects
- [x] I have two sponsors that meet the sponsor requirements listed in the community membership guidelines
- [x] I have spoken to my sponsors ahead of this application, and they have agreed to sponsor my application

### Sponsors
- @crenshaw-dev
- @leoluz 

### List of contributions to the Argoproj project
- PRs authored
  * [Argo Rollouts](https://github.com/argoproj/argo-rollouts/pulls?q=is%3Apr+author%3Azachaller+is%3Aclosed)
    * https://github.com/argoproj/argo-rollouts/pull/2074
    * https://github.com/argoproj/argo-rollouts/pull/2030
    * https://github.com/argoproj/argo-rollouts/pull/1839
    * https://github.com/argoproj/argo-rollouts/pull/1907
    * https://github.com/argoproj/argo-rollouts/pull/2080
  * [Argo CD](https://github.com/argoproj/argo-cd/pulls?q=is%3Apr+author%3Azachaller+is%3Aclosed)
    * https://github.com/argoproj/argo-cd/pull/8870
    * https://github.com/argoproj/argo-cd/pull/8943
    * https://github.com/argoproj/argo-cd/pull/8870
    * Security Issues
      * GHSA-2m7h-86qq-fp4v
      * GHSA-7943-82jg-wmw5
      * GHSA-r642-gv9p-2wjj
  * [Argo Workflows](https://github.com/argoproj/argo-workflows/pulls?q=is%3Apr+author%3Azachaller+is%3Aclosed)
    * https://github.com/argoproj/argo-workflows/pull/2468
    * https://github.com/argoproj/argo-workflows/pull/2518
    * https://github.com/argoproj/argo-workflows/pull/3398
    * https://github.com/argoproj/argo-workflows/pull/5214
    * https://github.com/argoproj/argo-workflows/pull/5218
    * https://github.com/argoproj/argo-workflows/pull/5910
  * [Argo Events](https://github.com/argoproj/argo-events/pulls?q=is%3Apr+author%3Azachaller+is%3Aclosed)
    * https://github.com/argoproj/argo-events/pull/435
    * https://github.com/argoproj/argo-events/pull/436
    * https://github.com/argoproj/argo-events/pull/484
    * https://github.com/argoproj/argo-events/pull/704
    * https://github.com/argoproj/argo-events/pull/817
    * https://github.com/argoproj/argo-events/pull/829
- Issues responded to
  * https://github.com/argoproj/argo-rollouts/issues/2090
  * https://github.com/argoproj/argo-rollouts/issues/2073
  * https://github.com/argoproj/argo-rollouts/issues/1989
  * https://github.com/argoproj/argo-rollouts/issues/563
- Projects I am involved with
  * Argo Rollouts
  * ArgoCD

**Comment by leoluz** [comment]
+1

**Comment by crenshaw-dev** [comment]
+1

**Comment by terrytangyuan** [comment]
+1

**Comment by crenshaw-dev** [comment]
@jessesuen can you sponsor? Zach needs one lead.
