### ISSUE TITLE
REQUEST: Promotion to reviewer for @tczhao

### ISSUE THREAD

**Issue by tczhao** [argoproj/argoproj#137]
### GitHub Username
@tczhao

From "member" to "reviewer" for Argo Workflows.

### Sponsors
* @alexec
* @sarabala1979 

### List of contributions to the Argoproj project

- [PR](https://github.com/argoproj/argo-workflows/pulls?q=is%3Apr+author%3Atczhao)
- [PR-reviewed](https://github.com/argoproj/argo-workflows/pulls?q=is%3Apr+reviewed-by%3Atczhao+is%3Aopen)
- [Issues](https://github.com/argoproj/argo-workflows/issues?q=is%3Aissue+involves%3Atczhao)

### Previous Membership request

#89

**Comment by alexec** [comment]
I think this is a good idea.

**Comment by sarabala1979** [comment]
+1
