### ISSUE TITLE
MAINTAINERS.md needs enhancing

### ISSUE THREAD

**Issue by alexec** [argoproj/argoproj#141]
https://github.com/argoproj/argoproj/blob/master/MAINTAINERS.md

* Not kept up to date.
* Is not the master.
* Does not state what "Has Vote" means.

**Comment by hblixt** [comment]
It should be kept up to date, or at least that's the intent as this is the file that CNCF looks at to track maintainers. People should also add a PR here when they get added/promoted, which generally seem to work, though I did find that tetchel is missing. 
We use this doc as the master to track who has a vote in project matters and our governance doc outlines what the "Has vote" means. Do we need further clarification in this doc?

**Comment by terrytangyuan** [comment]
> though I did find that tetchel is missing. 

It was removed in https://github.com/argoproj/argoproj/pull/101.

**Comment by hblixt** [comment]
> > though I did find that tetchel is missing.
> 
> It was removed in #101.

So it's the argo-cd owners.md thats out of date then? :)

**Comment by edlee2121** [comment]
The doc has now been updated and the has vote column as been removed.
We should automate updating maintainers.md from the owners files in the future.
