### ISSUE TITLE
REQUEST: New membership for notfromstatefarm

### ISSUE THREAD

**Issue by notfromstatefarm** [argoproj/argoproj#147]
### GitHub Username
notfromstatefarm

### Organization you are requesting membership in
@argoproj

### Requirements
- [x] I have reviewed the community membership guidelines (https://github.com/argoproj/argoproj/blob/master/community/membership.md)
- [x] I have enabled 2FA on my GitHub account (https://github.com/settings/security)
- [x] I am actively contributing to 1 or more Argoproj subprojects
- [x] I have two sponsors that meet the sponsor requirements listed in the community membership guidelines
- [x] I have spoken to my sponsors ahead of this application, and they have agreed to sponsor my application

### Sponsors
- @crenshaw-dev 
- @alexmt 

### List of contributions to the Argoproj project
- PRs reviewed / authored
https://github.com/argoproj/argo-cd/pull/9789
https://github.com/argoproj/argo-cd/pull/9843
https://github.com/argoproj/argo-cd/pull/9883
https://github.com/argoproj/argo-cd/pull/9922
https://github.com/argoproj/argo-cd/pull/9948
https://github.com/argoproj/argo-cd/pull/9959
https://github.com/argoproj/argo-cd/pull/9971
https://github.com/argoproj/argo-cd/pull/9976
https://github.com/argoproj/argo-cd/pull/10019
https://github.com/argoproj/argo-cd/pull/10256
- Issues responded to
Majority of the above PRs were authored in response to issues, so I won't bother relinking them
- Projects I am involved with
argocd

**Comment by alexmt** [comment]
Please count me it!

**Comment by jannfis** [comment]
Count me in as well :)

**Comment by edlee2121** [comment]
@notfromstatefarm Invite sent. Let us know if you don't receive it.

**Comment by notfromstatefarm** [comment]
I'm in. Thank you!
