### ISSUE TITLE
Add CONTRIBUTING.md

### ISSUE THREAD

**Issue by crenshaw-dev** [argoproj/argoproj#153]
Add a CONTRIBUTING.md file linking to each of the sub-projects' contributing docs.

Increases our discoverability and our CLO score: https://clomonitor.io/projects/cncf/argo#argoproj

**Comment by crenshaw-dev** [comment]
Actually, we have one. The CLOMonitor just doesn't see it: https://clomonitor.io/docs/topics/checks/#contributing

**Comment by eddie-knight** [comment]
Requested that the failing check is extended to include `community/CONTRIBUTING.md`

**Comment by crenshaw-dev** [comment]
I added a link to the base README, which passed the check.
