### ISSUE TITLE
REQUEST: Promotion to Reviewer for @juliev0

### ISSUE THREAD

**Issue by sarabala1979** [argoproj/argoproj#160]
### GitHub Username
@juliev0

### Organization you are requesting membership in
Argo workflow 

### Requirements
- [ ] I have reviewed the community membership guidelines (https://github.com/argoproj/argoproj/blob/master/community/membership.md)
- [ ] I have enabled 2FA on my GitHub account (https://github.com/settings/security)
- [x] I am actively contributing to 1 or more Argoproj subprojects
- [ ] I have two sponsors that meet the sponsor requirements listed in the community membership guidelines
- [ ] I have spoken to my sponsors ahead of this application, and they have agreed to sponsor my application

### Sponsors
- @sarabala1979 
- (at)sponsor-2

### List of contributions to the Argoproj project
-  16 PRs [reviewed](https://github.com/argoproj/argo-workflows/pulls?q=is%3Apr+assignee%3Ajuliev0)/ 50 PRs [authored](https://github.com/argoproj/argo-workflows/pulls?q=is%3Apr+author%3Ajuliev0+is%3Aclosed+) 
- [35+ issues responder](https://github.com/argoproj/argo-workflows/issues?q=juliev0+)
- Projects I am involved with

@juliev0 is a full-time resource working on Argo workflow. She learned and started contributing argo workflow very quickly. She contributed Artifact GC and Visualization on v3.4.

**Comment by terrytangyuan** [comment]
+1 well deserved

**Comment by whynowy** [comment]
+1
