### ISSUE TITLE
REQUEST: New membership for reggie-k

### ISSUE THREAD

**Issue by reggie-k** [argoproj/argoproj#162]
### GitHub Username
@reggie-k

### Organization you are requesting membership in
@argoproj

### Requirements
- [x] I have reviewed the community membership guidelines (https://github.com/argoproj/argoproj/blob/master/community/membership.md)
- [x] I have enabled 2FA on my GitHub account (https://github.com/settings/security)
- [x] I am actively contributing to 1 or more Argoproj subprojects
- [x] I have two sponsors that meet the sponsor requirements listed in the community membership guidelines
- [x] I have spoken to my sponsors ahead of this application, and they have agreed to sponsor my application

### Sponsors
- @crenshaw-dev 
- @leoluz 

### List of contributions to the Argoproj project
- https://github.com/argoproj/argo-cd/pull/10885
- https://github.com/argoproj/argo-cd/pull/8353
- Projects I am involved with

**Comment by crenshaw-dev** [comment]
Additional contribution: _awesome_ recorded session at ArgoCon: https://youtu.be/kQZhdJn1Phw?t=323

**Comment by pasha-codefresh** [comment]
Thank you @reggie-k for all work that you done !

**Comment by leoluz** [comment]
Count me in as a sponsor as well
