### ISSUE TITLE
REQUEST: New membership for blakepettersson 🙌 

### ISSUE THREAD

**Issue by blakepettersson** [argoproj/argoproj#163]
### GitHub Username
blakepettersson

### Organization you are requesting membership in
@argoproj

### Requirements
- [x] I have reviewed the community membership guidelines (https://github.com/argoproj/argoproj/blob/master/community/membership.md)
- [x] I have enabled 2FA on my GitHub account (https://github.com/settings/security)
- [x] I am actively contributing to 1 or more Argoproj subprojects
- [x] I have two sponsors that meet the sponsor requirements listed in the community membership guidelines
- [x] I have spoken to my sponsors ahead of this application, and they have agreed to sponsor my application

### Sponsors
- @crenshaw-dev 
- @leoluz 

### List of contributions to the Argoproj project
- [PRs reviewed / authored in argo-cd](https://github.com/argoproj/argo-cd/pulls?q=is%3Apr+author%3Ablakepettersson)
- [PRs reviewed / authored in gitops-engine](https://github.com/argoproj/gitops-engine/pulls?q=is%3Apr+author%3Ablakepettersson)
- Issues responded to
    * argoproj/argo-cd#10997
    * argoproj/argo-cd#7437
- There should be a few more but I'm not sure how to query for issues that I commented on 😄 I'm more active on Slack though.
- Projects I am involved with
    * argoproj/argo-cd
    * argoproj/gitops-engine

**Comment by leoluz** [comment]
Count me in as a sponsor! 👍🏻

**Comment by blakepettersson** [comment]
Awesome, thanks @leoluz!
