### ISSUE TITLE
REQUEST: New membership for tico24

### ISSUE THREAD

**Issue by tico24** [argoproj/argoproj#166]
### GitHub Username
@tico24

### Organization you are requesting membership in
@argoproj

### Requirements
- [x] I have reviewed the community membership guidelines (https://github.com/argoproj/argoproj/blob/master/community/membership.md)
- [x] I have enabled 2FA on my GitHub account (https://github.com/settings/security)
- [x] I am actively contributing to 1 or more Argoproj subprojects
- [x] I have two sponsors that meet the sponsor requirements listed in the community membership guidelines
- [x] I have spoken to my sponsors ahead of this application, and they have agreed to sponsor my application

### Sponsors
- @sarabala1979
- @JPZ13

Please note, I sometimes submit under my company github account, @tim-sendible

### List of contributions to the Argoproj project
- https://github.com/argoproj/argo-workflows/pulls?q=is%3Apr+author%3Atim-sendible+is%3Aclosed
- https://github.com/argoproj/argo-workflows/pulls?q=is%3Apr+author%3Atico24+is%3Aclosed
- https://github.com/argoproj/argo-workflows/issues?q=is%3Aissue+author%3Atim-sendible+is%3Aclosed
- You'll find me answering a large number of issues on the #argo-cd, #argo-workflows and #argo-events slack channels
- https://killercoda.com/pipekit/course/argo-workflows/
- https://github.com/sendible-labs/argo-workflows-ci-example
- https://github.com/crumbhole/argocd-lovely-plugin
- https://github.com/crumbhole/argocd-vault-replacer
- https://medium.com/argo-project/migrating-from-jenkins-to-argo-at-sendible-2ad4268837e9

**Comment by terrytangyuan** [comment]
+1. I'd like to sponsor as well. Thank you!
