### ISSUE TITLE
REQUEST: New membership for ashutosh16

### ISSUE THREAD

**Issue by ashutosh16** [argoproj/argoproj#169]
### GitHub Username
ashutosh16

### Organization you are requesting membership in
e.g. (at)argoproj

### Requirements
- [ ] I have reviewed the community membership guidelines (https://github.com/argoproj/argoproj/blob/master/community/membership.md)
- [ ] I have enabled 2FA on my GitHub account (https://github.com/settings/security)
- [ ] I am actively contributing to 1 or more Argoproj subprojects
- [ ] I have two sponsors that meet the sponsor requirements listed in the community membership guidelines
- [ ] I have spoken to my sponsors ahead of this application, and they have agreed to sponsor my application

### Sponsors
- [leoluz](https://github.com/leoluz)
- [crenshaw-dev](https://github.com/crenshaw-dev)

### List of contributions to the Argoproj project
- PRs reviewed / authored
https://github.com/argoproj-labs/argocd-extensions/pull/16
https://github.com/argoproj/argo-cd/pull/10855
https://github.com/argoproj/argo-cd/pull/10556
https://github.com/argoproj/argo-cd/pull/9057
https://github.com/argoproj/argo-cd/pull/9057
https://github.com/argoproj/argo-cd/pull/10379
https://github.com/argoproj/argo-cd/pull/10493
- Projects I am involved with
Argo CD
Rollout-Extension
ArgoCD Extention 
ArgoCon

**Comment by crenshaw-dev** [comment]
@edlee2121 can you double-check that Ashutosh got added to the member group?

**Comment by ashutosh16** [comment]
@edlee2121 Would you be able to add me to the member group? I have already been approved for membership. Thx!

**Comment by crenshaw-dev** [comment]
@ashutosh16 I pinged Alex Collins about this too.

**Comment by alexec** [comment]
![image](https://user-images.githubusercontent.com/1142830/210395175-d2f9908d-b4e5-4665-99f7-93ac64736ce5.png)
