### ISSUE TITLE
How event listener will trigger argo workflows if all the resources are consumed 

### ISSUE THREAD

**Issue by aman21391** [argoproj/argoproj#171]
Hi Team,

If I have 1000's of events coming and I can process only a limited number in that case will be message will be there in the event bus and will execute once the resources are available,
or it will discard the message,
or it will create a dead lock in the system as multiple pod will try to get the resource (if yes then what should be the best practice)

Thanks in advance,
Aman

**Comment by agilgur5** [comment]
Sounds like this issue should probably have been filed under Argo Events. This repo is primarily governance oriented for the Argoproj organization.

I don't have permissions to move issues at this time, but feel free to re-open in Argo Events if this is still relevant.
