### ISSUE TITLE
REQUEST: New membership for @fengshunli 

### ISSUE THREAD

**Issue by fengshunli** [argoproj/argoproj#174]
GitHub Username
@fengshunli

Sponsors:
* @crenshaw-dev 

### List of contributions to the Argoproj project
- PRs reviewed / authored [argo-helm ](https://github.com/argoproj/argo-helm/pull/1672) [argo-cd ](https://github.com/argoproj/argo-cd/pulls?q=is%3Apr+author%3Afengshunli) [argo-rollouts ](https://github.com/argoproj/argo-rollouts/pulls?q=is%3Apr+author%3Afengshunli) [gitops-engine
](https://github.com/argoproj/gitops-engine/pulls?q=is%3Apr+author%3Afengshunli)

- Issues responded to
https://github.com/argoproj/argo-cd/issues/11603
https://github.com/argoproj/argo-cd/pull/11366
https://github.com/argoproj/argo-cd/pull/11417
https://github.com/argoproj/argo-cd/pull/11101
https://github.com/argoproj/argo-cd/issues/12382
https://github.com/argoproj/argo-cd/issues/12288
https://github.com/argoproj/argo-cd/issues/12419
- Projects I am involved with
argo-cd
argo-rollouts
argo-helm
gitops-engine

**Comment by crenshaw-dev** [comment]
@fengshunli has done a _lot_ of work helping us get k8s libraries upgraded in Argo CD. Strong +1 for this request.
