### ISSUE TITLE
REQUEST: New membership for jmeridth

### ISSUE THREAD

**Issue by jmeridth** [argoproj/argoproj#180]
### GitHub Username
@jmeridth

### Organization you are requesting membership in
@argoproj

### Requirements
- [x] I have reviewed the community membership guidelines (https://github.com/argoproj/argoproj/blob/master/community/membership.md)
- [x] I have enabled 2FA on my GitHub account (https://github.com/settings/security)
- [x] I am actively contributing to 1 or more Argoproj subprojects
- [x] I have two sponsors that meet the sponsor requirements listed in the community membership guidelines
- [x] I have spoken to my sponsors ahead of this application, and they have agreed to sponsor my application

Conversation started [here](https://cloud-native.slack.com/archives/C020XM04CUW/p1674068683378809) on CNCF slack about argo-helm

### Sponsors - actively acquiring
- @terrytangyuan 
- @crenshaw-dev 

### List of contributions to the Argoproj project

- argo-helm PRs authored [here](https://github.com/argoproj/argo-helm/pulls/jmeridth)
- argo-workflwos PRs authored [here](https://github.com/argoproj/argo-workflows/pulls/jmeridth)
- Issues responded to [argo-helm](https://github.com/argoproj/argo-helm/issues?q=is%3Aissue+commenter%3Ajmeridth+is%3Aclosed) and [argo-workflows](https://github.com/argoproj/argo-workflows/issues?q=is%3Aissue+is%3Aopen+commenter%3Ajmeridth)
- Projects I am involved with [argo-helm](https://github.com/argoproj/argo-helm) and working more in [argo-workflows](https://github.com/argoproj/argo-workflows)
- Active in CNCF slack, multiple argo channels

**Comment by wanghong230** [comment]
+1
