### ISSUE TITLE
REQUEST: Promotion to Reviewer for @blakepettersson

### ISSUE THREAD

**Issue by blakepettersson** [argoproj/argoproj#181]
### GitHub Username
@blakepettersson

### Organization you are requesting promotion in
@argoproj

### Requirements
- [x] I have reviewed the community membership guidelines (https://github.com/argoproj/argoproj/blob/master/community/membership.md)
- [x] I have enabled 2FA on my GitHub account (https://github.com/settings/security)
- [x] I am actively contributing to 1 or more Argoproj subprojects
- [x] I have two sponsors that meet the sponsor requirements listed in the community membership guidelines
- [x] I have spoken to my sponsors ahead of this application, and they have agreed to sponsor my application

### Sponsors
- @crenshaw-dev 
- @jannfis 
- @alexmt 

### List of contributions to the Argoproj project
- PRs [reviewed](https://github.com/argoproj/argo-cd/pulls?q=is%3Apr+reviewed-by%3Ablakepettersson) / [authored](https://github.com/argoproj/argo-cd/pulls?q=is%3Apr+author%3Ablakepettersson+)
- Issues responded to: yes, as well as on Slack
- Projects I am involved with: argoproj/argo-cd

**Comment by jannfis** [comment]
I'll happily sponsor this application, too!

**Comment by blakepettersson** [comment]
Thanks @jannfis! ❤️

**Comment by alexmt** [comment]
Please add me as a sponsor!
