### ISSUE TITLE
REQUEST: Promotion to reviewer for rohankmr414

### ISSUE THREAD

**Issue by rohankmr414** [argoproj/argoproj#188]
### GitHub Username
@rohankmr414

### Organization you are requesting membership in
@argoproj

### Requirements
- [x] I have reviewed the community membership guidelines (https://github.com/argoproj/argoproj/blob/master/community/membership.md)
- [x] I have enabled 2FA on my GitHub account (https://github.com/settings/security)
- [x] I am actively contributing to 1 or more Argoproj subprojects
- [x] I have two sponsors that meet the sponsor requirements listed in the community membership guidelines
- [x] I have spoken to my sponsors ahead of this application, and they have agreed to sponsor my application

### Sponsors
- @sarabala1979 
- @juliev0 

### List of contributions to the Argoproj project
- PRs [reviewed](https://github.com/argoproj/argo-workflows/pulls?q=is%3Apr+reviewed-by%3Arohankmr414) / [authored](https://github.com/argoproj/argo-workflows/pulls?q=is%3Apr+author%3Arohankmr414+)
- Issues [responded to](https://github.com/argoproj/argo-workflows/issues?q=is%3Aissue+commenter%3Arohankmr414)
- Projects I am involved with argoproj/argo-workflows
- Actively participating in bug triage

**Comment by juliev0** [comment]
+1

**Comment by sarabala1979** [comment]
Here the substantial PRs from Rohan. I am very closely working with him every day for workflow. He has a very good understanding of all areas of workflow code. He is 100%  argo workflow resource
-----
https://github.com/argoproj/argo-workflows/pull/7929
Description: added support for custom SSL certificates for HTTP templates
Area: controller, agent
-----
https://github.com/argoproj/argo-workflows/pull/8087
Description: added support for binaries in HTTP template body
Area: spec, controller, agent
-----
https://github.com/argoproj/argo-workflows/pull/8414
Description:  added support for HTTP artifact upload
Area: spec, artifact-driver/agent
-----
https://github.com/argoproj/argo-workflows/pull/9387
Description: added support for task names as variables in workflows
Area: controller
-----
https://github.com/argoproj-labs/go-git/pull/6
https://github.com/argoproj/argo-workflows/pull/9982
Description: fixed empty git-upload-pack given error on workflows using git artifacts with depth
Area:  go-git, artifact-driver

**Comment by sarabala1979** [comment]
Total reviewed and Approved 38 PRs https://github.com/argoproj/argo-workflows/pulls?q=is%3Apr+is%3Aclosed+commenter%3Arohankmr414
Here few PRs Rohan reviewed
1. https://github.com/argoproj/argo-workflows/pull/10300
2. https://github.com/argoproj/argo-workflows/pull/10774
3.

**Comment by sarabala1979** [comment]
@rohankmr414 can you close this request? I believe you have not actively contributed past 6 months. you can create the request once you come actively
