### ISSUE TITLE
REQUEST: New membership for @dfarr

### ISSUE THREAD

**Issue by dfarr** [argoproj/argoproj#195]
### GitHub Username
@dfarr

### Organization you are requesting membership in
@argoproj

### Requirements
- [x] I have reviewed the community membership guidelines (https://github.com/argoproj/argoproj/blob/master/community/membership.md)
- [x] I have enabled 2FA on my GitHub account (https://github.com/settings/security)
- [x] I am actively contributing to 1 or more Argoproj subprojects
- [x] I have two sponsors that meet the sponsor requirements listed in the community membership guidelines
- [x] I have spoken to my sponsors ahead of this application, and they have agreed to sponsor my application

### Sponsors
- @whynowy
- @juliev0
- @sarabala1979 

### List of contributions to the Argoproj project
- PRs reviewed / authored
  - argoproj/argo-events#2207
  - argoproj/argo-events#2438
  - argoproj/argo-events#2502
  - argoproj/argo-events#2523
  - argoproj/argo-events#2538
- Issues responded to
  - argoproj/argo-events#1682
  - argoproj/argo-workflows#1158
  - argoproj/argo-workflows#1160
  - argoproj/argo-workflows#1200
  - argoproj/argo-workflows#2302
- Projects I am involved with
  - argo-events

**Comment by juliev0** [comment]
It shouldn't be at all controversial, but in case there's any doubt, David has enabled a new kind of scale for Argo Events, so a strong recommendation.

**Comment by whynowy** [comment]
+1

**Comment by sarabala1979** [comment]
+1
