### ISSUE TITLE
REQUEST: Membership change to Lead @zachaller

### ISSUE THREAD

**Issue by zachaller** [argoproj/argoproj#201]
### GitHub Username
@zachaller 

### Organization you are requesting membership in
argoproj/argo-rollouts

### Requirements
- [x] I have reviewed the community membership guidelines (https://github.com/argoproj/argoproj/blob/master/community/membership.md)
- [x] I have enabled 2FA on my GitHub account (https://github.com/settings/security)
- [x] I am actively contributing to 1 or more Argoproj subprojects
- [x] I have two sponsors that meet the sponsor requirements listed in the community membership guidelines
- [x] I have spoken to my sponsors ahead of this application, and they have agreed to sponsor my application

### Sponsors
- @jessesuen 

### List of contributions to the Argoproj project
- PRs reviewed / authored
  - https://github.com/argoproj/argo-rollouts/pulls?q=is%3Apr+author%3Azachaller+is%3Aclosed
  - https://github.com/argoproj/argo-rollouts/pulls?q=is%3Apr+-label%3Adependencies+reviewed-by%3Azachaller+is%3Aclosed
- Issues responded to
  - https://github.com/argoproj/argo-rollouts/issues?q=is%3Aissue+is%3Aopen+involves%3Azachaller
- Projects I am involved with
  - https://github.com/argoproj/argo-schema-generator
  - https://github.com/argoproj/notifications-engine
  - https://github.com/argoproj-labs/rollout-extension

**Comment by jessesuen** [comment]
Zach has been instrumental to the project and wholeheartedly support this.
