### ISSUE TITLE
REQUEST: New membership for robertkotcher

### ISSUE THREAD

**Issue by robertkotcher** [argoproj/argoproj#205]
### GitHub Username

@robertkotcher

### Requirements
- [x] I have reviewed the community membership guidelines (https://github.com/argoproj/argoproj/blob/master/community/membership.md)
- [x] I have enabled 2FA on my GitHub account (https://github.com/settings/security)
- [x] I am actively contributing to 1 or more Argoproj subprojects
- [x] I have two sponsors that meet the sponsor requirements listed in the community membership guidelines
- [x] I have spoken to my sponsors ahead of this application, and they have agreed to sponsor my application

### Sponsors
- @terrytangyuan 
- @caelan-io
- @sarabala1979 

### List of contributions to the Argoproj project
- PRs reviewed / authored
https://github.com/argoproj/argo-workflows/pull/9992
(still in discussion, will be demoing to community on 17th)

- Issues responded to (Mainly slack conversations. Here are a few examples)
https://cloud-native.slack.com/archives/C01QW9QSSSK/p1681145946485849
https://cloud-native.slack.com/archives/C01QW9QSSSK/p1681245218220559
https://cloud-native.slack.com/archives/C01QW9QSSSK/p1681527579602539

- Issues created
https://github.com/argoproj/argo-workflows/issues/10844

- Projects I am involved with
Argo Workflows

**Comment by terrytangyuan** [comment]
+1 Thank you for your contributions!
