### ISSUE TITLE
REQUEST: New membership for rwong2888

### ISSUE THREAD

**Issue by rwong2888** [argoproj/argoproj#206]
### GitHub Username

@rwong2888

### Requirements
- [x] I have reviewed the community membership guidelines (https://github.com/argoproj/argoproj/blob/master/community/membership.md)
- [x] I have enabled 2FA on my GitHub account (https://github.com/settings/security)
- [x] I am actively contributing to 1 or more Argoproj subprojects
- [x] I have two sponsors that meet the sponsor requirements listed in the community membership guidelines
- [x] I have spoken to my sponsors ahead of this application, and they have agreed to sponsor my application

### Sponsors
- @crenshaw-dev 
- @sarabala1979 

### List of contributions to the Argoproj project
- PRs reviewed / authored
https://github.com/argoproj/argo-cd/pull/7152
https://github.com/argoproj/argo-workflows/pull/6798
https://github.com/argoproj/argo-cd/pull/12701
- Issues responded to
https://github.com/argoproj/argo-workflows/issues/5944
https://github.com/argoproj/argo-workflows/issues/5948
https://github.com/argoproj/argo-workflows/issues/5984
https://github.com/argoproj/argo-workflows/issues/6002
https://github.com/argoproj/argo-events/issues/1230
https://github.com/argoproj/argo-workflows/issues/6030
https://github.com/argoproj/argo-cd/issues/6749
https://github.com/argoproj/argo-cd/issues/6754
https://github.com/argoproj/argo-cd/issues/6839
https://github.com/argoproj/argo-cd/issues/6851
https://github.com/argoproj/argo-cd/issues/6958
https://github.com/argoproj/argo-workflows/issues/6534
https://github.com/argoproj/argo-cd/issues/6974
https://github.com/argoproj/argo-workflows/issues/6645
https://github.com/argoproj/argo-cd/issues/7144
https://github.com/argoproj/argo-cd/issues/7287
https://github.com/argoproj/argo-workflows/issues/6794
https://github.com/argoproj/argo-workflows/issues/7055
https://github.com/argoproj/argo-workflows/issues/7780
https://github.com/argoproj/argo-cd/issues/8715
https://github.com/argoproj/argo-cd/issues/8764
https://github.com/argoproj/argo-cd/issues/8839
https://github.com/argoproj/argo-workflows/issues/8547
https://github.com/argoproj/argo-cd/issues/9382
https://github.com/argoproj/argo-cd/issues/9786
https://github.com/argoproj/argo-workflows/issues/9649
https://github.com/argoproj/argo-cd/issues/10902
https://github.com/argoproj/argo-events/issues/2278
- Projects I am involved with
argo-cd
argo-workflows
argo-events

**Comment by terrytangyuan** [comment]
+1 Thank you for your contributions!

**Comment by crenshaw-dev** [comment]
+1

**Comment by sarabala1979** [comment]
+1
