### ISSUE TITLE
REQUEST: Promotion to Reviewer for @gdsoumya

### ISSUE THREAD

**Issue by gdsoumya** [argoproj/argoproj#207]
### GitHub Username

@gdsoumya 

### Sub-project(s)

Promotion is requested for the following sub-project(s).

- [x] Argo CD
- [ ] Argo Events
- [ ] Argo Rollouts
- [ ] Argo Workflows

### Requirements

- [x] Member for at least 3 months (as of the membership meeting date)
- [x] Reviewer for or author of at least 5 substantial PRs to the codebase
  - [Pull Requests made](https://github.com/argoproj/argo-cd/pulls?q=is%3Apr+author%3Agdsoumya)
  - [Pull Requests reviewed](https://github.com/argoproj/argo-cd/pulls?q=is%3Apr+reviewed-by%3Agdsoumya+-author%3Agdsoumya+)

### Sponsor(s)

- @alexmt 
- @jessesuen

**Comment by terrytangyuan** [comment]
+1

**Comment by alexmt** [comment]
+1
