### ISSUE TITLE
REQUEST: Demotion to Approver for alexec

### ISSUE THREAD

**Issue by alexec** [argoproj/argoproj#208]
### GitHub Username

@alexec 

### Sub-project(s)

Promotion is requested for the following sub-project(s). 

- [ ] Argo CD
- [ ] Argo Events
- [ ] Argo Rollouts
- [x] Argo Workflows

### Requirements

???

### Lead Sponsor(s)

Promotion to Approver requires sponsorship from at least one sub-project Lead.

- @<sponsor-1>

### Other Sponsors

- @<sponsor-1>

**Comment by alexec** [comment]
I request my own demotion.

**Comment by hblixt** [comment]
@alexec A big thank you for all your hard work with Workflows and Argo in general, the project and community wouldnt be where they are today without you!

**Comment by edlee2121** [comment]
I don't think demotion is quite the right word for it :-)
Thank you for you contributions in leading the community!

**Comment by terrytangyuan** [comment]
Thank you for everything you did for the project!

**Comment by wanghong230** [comment]
Thank you for everything!

**Comment by 34fathombelow** [comment]
Your legacy will live on, thank you for everything!

**Comment by sarabala1979** [comment]
Thank you for everything @alexec
