### ISSUE TITLE
REQUEST: argo-helm scoped Approver Promotion Request for mkilchhofer

### ISSUE THREAD

**Issue by jmeridth** [argoproj/argoproj#210]
### GitHub Username

@mkilchhofer

## SCOPED

Scoped helm charts based [argo-helm CODEOWNERS file](https://github.com/argoproj/argo-helm/blob/main/CODEOWNERS):

- all

Still retains admin rights on github.com/argoproj/argo-helm as a maintainer

### Membership Requirements

- [x] I have reviewed the community membership guidelines (https://github.com/argoproj/argoproj/blob/master/community/membership.md)
- [x] I have enabled 2FA on my GitHub account (https://github.com/settings/security)
- [x] I am actively contributing to argo-helm
- [x] I have two sponsors who meet the sponsor requirements listed in the community membership guidelines
- [x] I have spoken to my sponsors ahead of this application, and they have agreed to sponsor my application

### Reviewer Requirements

- [x] argo-helm contributor for at least 3 months (as of the membership meeting date)
- [x] Reviewer for or author of at least 5 substantial PRs to the codebase (look below)

Pull Requests created and merged: [22](https://github.com/argoproj/argo-helm/pulls?q=is%3Apr+author%3Amkilchhofer+merged%3A2021-03-09..2021-06-09+archived%3Afalse+is%3Aclosed+)

Pull Requests reviewed: [44](https://github.com/argoproj/argo-helm/pulls?q=is%3Apr+reviewed-by%3Amkilchhofer+merged%3A2021-03-09..2021-06-09+archived%3Afalse+is%3Aclosed+)

### Approver Requirements

- [x] argo-helm contributor for at least 3 months (as of the membership meeting date)
- [x] Reviewer for or author of at least 10 substantial PRs to the codebase (look below)

Pull Requests created and merged: [79](https://github.com/argoproj/argo-helm/pulls?q=is%3Apr+author%3Amkilchhofer+merged%3A%3E2021-06-09+archived%3Afalse+is%3Aclosed+)

Pull Requests reviewed: [337](https://github.com/argoproj/argo-helm/pulls?q=is%3Apr+reviewed-by%3Amkilchhofer+merged%3A%3E2021-06-09+archived%3Afalse+is%3Aclosed+)

## SPONSORS

- @jmeridth
- @terrytangyuan

**Comment by terrytangyuan** [comment]
+1

**Comment by jannfis** [comment]
+1 from me
