### ISSUE TITLE
REQUEST: New membership for christianh814 

### ISSUE THREAD

**Issue by christianh814** [argoproj/argoproj#217]
### GitHub Username

@christianh814 

### Requirements
- [x] I have reviewed the community membership guidelines (https://github.com/argoproj/argoproj/blob/master/community/membership.md)
- [x] I have enabled 2FA on my GitHub account (https://github.com/settings/security)
- [x] I am actively contributing to 1 or more Argoproj subprojects
- [x] I have two sponsors that meet the sponsor requirements listed in the community membership guidelines
- [x] I have spoken to my sponsors ahead of this application, and they have agreed to sponsor my application

### Sponsors
- @terrytangyuan
- @crenshaw-dev

### List of contributions to the Argoproj project

PRs reviewed / authored
- [#14354](https://github.com/argoproj/argo-cd/pull/14354)
- [#14295](https://github.com/argoproj/argo-cd/pull/14295)
- [#9632](https://github.com/argoproj/argo-cd/pull/9632)
- [#14380](https://github.com/argoproj/argo-cd/pull/14380)
- [#12265](https://github.com/argoproj/argo-cd/pull/12265)

Issues responded to
- [#14536](https://github.com/argoproj/argo-cd/issues/14536)
- [#13642](https://github.com/argoproj/argo-cd/issues/13642)
- [#13131](https://github.com/argoproj/argo-cd/issues/13131)
- [#12475](https://github.com/argoproj/argo-cd/issues/12475)
- [#11924](https://github.com/argoproj/argo-cd/issues/11924)
- [#1761](https://github.com/argoproj/argo-cd/issues/1761)

Projects I am involved with
- Argo CD
- [Argo Project Marketing SIG](https://github.com/argoproj/argoproj/tree/master/sigs/sig-marketing#members)

**Comment by terrytangyuan** [comment]
+1

**Comment by jannfis** [comment]
Also, Christian is involved _a lot_ with the community, so +1 from me, too.

**Comment by alexmt** [comment]
+1 !
