### ISSUE TITLE
REQUEST: New membership for toyamagu-2021

### ISSUE THREAD

**Issue by toyamagu-2021** [argoproj/argoproj#218]
### GitHub Username

@toyamagu-2021

### Requirements
- [x] I have reviewed the community membership guidelines (https://github.com/argoproj/argoproj/blob/master/community/membership.md)
- [x] I have enabled 2FA on my GitHub account (https://github.com/settings/security)
- [x] I am actively contributing to 1 or more Argoproj subprojects
- [x] I have two sponsors that meet the sponsor requirements listed in the community membership guidelines
- [x] I have spoken to my sponsors ahead of this application, and they have agreed to sponsor my application

### Sponsors
- @terrytangyuan 
- @crenshaw-dev 

### List of contributions to the Argoproj project
- PRs reviewed / authored
  - https://github.com/argoproj/argo-workflows/pull/11083
  - https://github.com/argoproj/argo-workflows/pull/11366
  - https://github.com/argoproj/argo-workflows/pull/11176
  - https://github.com/argoproj/argo-workflows/pull/11087
  - https://github.com/argoproj/argo-workflows/pull/10936
  - https://github.com/argoproj/argo-cd/pull/11665
  - https://github.com/argoproj/argo-cd/pull/12538
  - https://github.com/argoproj/argo-cd/pull/11771
  - https://github.com/argoproj/argo-cd/pull/11775
  - https://github.com/argoproj/argo-cd/pull/10857
- Issues responded to
  - https://github.com/argoproj/argo-workflows/issues/11113
  - https://github.com/argoproj/argo-workflows/issues/11086
  - https://github.com/argoproj/argo-workflows/issues/11371
  - https://github.com/argoproj/argo-workflows/issues/11367
  - https://github.com/argoproj/argo-workflows/issues/11278
  - https://github.com/argoproj/argo-workflows/issues/11148
  - https://github.com/argoproj/argo-cd/issues/11650
  - https://github.com/argoproj/argo-cd/issues/12537
  - https://github.com/argoproj/argo-cd/issues/11768
- Projects I am involved with
   - ArgoWorkflows
   - ArgoCD
   - Argo helm
     - https://github.com/argoproj/argo-helm/pulls?q=is%3Apr+sort%3Aupdated-desc+author%3Atoyamagu-2021+is%3Aclosed

**Comment by terrytangyuan** [comment]
+1 Thank you for your contributions!

**Comment by crenshaw-dev** [comment]
Count me in as well. Thanks, @toyamagu-2021!

**Comment by jannfis** [comment]
+1 from me
