### ISSUE TITLE
REQUEST: New membership for @agilgur5

### ISSUE THREAD

**Issue by agilgur5** [argoproj/argoproj#221]
### GitHub Username

@agilgur5

### Requirements
- [x] I have reviewed the community membership guidelines (https://github.com/argoproj/argoproj/blob/master/community/membership.md)
- [x] I have enabled 2FA on my GitHub account (https://github.com/settings/security)
- [x] I am actively contributing to 1 or more Argoproj subprojects
- [x] I have two sponsors that meet the sponsor requirements listed in the community membership guidelines
- [x] I have spoken to my sponsors ahead of this application, and they have agreed to sponsor my application

### Sponsors
- @terrytangyuan (I requested membership after [this comment](https://github.com/argoproj/argo-workflows/pull/11352#issuecomment-1634530557) 🙂)
- @juliev0

### List of contributions to the Argoproj project

Argo Workflows:
- [33+ PRs opened](https://github.com/argoproj/argo-workflows/pulls?q=is%3Apr+author%3Aagilgur5+)
- [18+ PRs reviewed](https://github.com/argoproj/argo-workflows/pulls?q=is%3Apr+involves%3Aagilgur5+-author%3Aagilgur5)
- [20+ issues responded to](https://github.com/argoproj/argo-workflows/issues?q=is%3Aissue+involves%3Aagilgur5+-author%3Aagilgur5+)
- [4+ issues opened](https://github.com/argoproj/argo-workflows/issues?q=is%3Aissue+author%3Aagilgur5)
- [8+ discussions responded to](https://github.com/argoproj/argo-workflows/discussions?discussions_q=commenter%3Aagilgur5+) (plus several sub-discussions as each comment from giscus is basically its own discussion)
- 13+ [Slack](https://cloud-native.slack.com/archives/C01QW9QSSSK) questions responded to (can't link to a Slack search, so just linked to the `#argo-workflows` channel -- can search my name there. also 1+ in `#argo-contributors`)

Argo Helm:
- [4+ PRs](https://github.com/argoproj/argo-helm/pulls?q=is%3Apr+author%3Aagilgur5)
- [2+ issues responded to](https://github.com/argoproj/argo-helm/issues?q=is%3Aissue+involves%3Aagilgur5+-author%3Aagilgur5+)

Argo CD:
- [2+ PRs](https://github.com/argoproj/argo-cd/pulls?q=is%3Apr+author%3Aagilgur5)
- Apparently nothing else despite using CD longer than Workflows, so I guess my teammates must've contributed there and I just upvoted or something 😅 

Argoproj (i.e. this repo):
- [2+ PRs](https://github.com/argoproj/argoproj/pulls?q=is%3Apr+author%3Aagilgur5)
- [2+ PRs reviewed](https://github.com/argoproj/argoproj/pulls?q=is%3Apr+involves%3Aagilgur5+-author%3Aagilgur5)
- [1+ issues responded to](https://github.com/argoproj/argoproj/issues?q=is%3Aissue+involves%3Aagilgur5+-author%3Aagilgur5+)
- [1+ issues opened](https://github.com/argoproj/argoproj/issues?q=is%3Aissue+author%3Aagilgur5+) (literally this one)

**Comment by terrytangyuan** [comment]
+1 Thank you for your contributions!

**Comment by juliev0** [comment]
happy to sponsor as well

**Comment by caelan-io** [comment]
+1 thanks for contributing on code + docs recently 👏

**Comment by Joibel** [comment]
+1, you've been good at catching my rubbish commits :clap:
