### ISSUE TITLE
REQUEST: Promotion to Approver for @ishitasequeira

### ISSUE THREAD

**Issue by crenshaw-dev** [argoproj/argoproj#224]
### GitHub Username

@ishitasequeira 

### Sub-project(s)

Promotion is requested for the following sub-project(s).

- [x] Argo CD
- [ ] Argo Events
- [ ] Argo Rollouts
- [ ] Argo Workflows

### Requirements

- [x] Reviewer for at least 3 months (as of the membership meeting date)
- [x] Reviewer for or author of at least 10 substantial PRs to the codebase
    - author: [feat: Multiple sources for applications](https://github.com/argoproj/argo-cd/pull/10432)
      This was a major feature that involved the API server, repo server, and controller.
    - author: [feat: create cli commands for ApplicationSet](https://github.com/argoproj/argo-cd/pull/9584)
      This PR touched 102 files and involved fixing complex issues with codegen.
    - author: [feat: simplify parametrization of Argo CD server processes](https://github.com/argoproj/argo-cd/pull/6328)
      This PR significantly improved the user experience of configuring parameters for different Argo CD components.
    - author: [feat(appset): Add support for self-signed TLS / Certificates for Gitlab Scm Provider](https://github.com/argoproj/argo-cd/pull/14348)
      An important security feature, showing off careful design, implementation, and documentation.
    - author: [feat: add timezone option to sync window](https://github.com/argoproj/argo-cd/pull/7442)
    - author: [feat: added cascade option to delete resources](https://github.com/argoproj/argo-cd/pull/5538)
    - author: [chore: move access checks from api server to repo server](https://github.com/argoproj/argo-cd/pull/5940)
    - author: [docs: proposal for backend support of ApplicationSets](https://github.com/argoproj/argo-cd/pull/9016)
    - reviewer: ...more to be added...

### Lead Sponsor(s)

Promotion to Approver requires sponsorship from at least one sub-project Lead.

- @alexmt 

### Other Sponsors

- @crenshaw-dev
- @jannfis 

### Extra Info

* Authored [35 merged PRs](https://github.com/argoproj/argo-cd/pulls?q=is%3Apr+author%3Aishitasequeira+is%3Aclosed)
* Reviewed [146 PRs](https://github.com/argoproj/argo-cd/pulls?q=is%3Apr+reviewed-by%3Aishitasequeira+is%3Aclosed+)

Ishita has authored multiple major features, spanning all major Argo CD components. She's methodical in the design phase, usually discovering issues very early and avoiding a lot of unnecessary development work.

She is one of the most prolific PR reviewers and has especially built expertise in the ApplicationSet component, providing in-depth reviews of major features and subtle bugfixes.

Ishita has authored multiple proposals for groundbreaking improvements in Argo CD. These proposals demonstrate a thorough understanding of the whole produce and diligent care for balancing robust design with the need for incremental improvements.

I wholeheartedly endorse Ishita's promotion to Approver. She's a vital part of the Argo maintainer community and will certainly be a major part of the project's ongoing success.

**Comment by jannfis** [comment]
Count me in as sponsor.

**Comment by alexmt** [comment]
Add me as well please
