### ISSUE TITLE
REQUEST: Promotion to Approver(docs) for @todaywasawesome

### ISSUE THREAD

**Issue by crenshaw-dev** [argoproj/argoproj#228]
### GitHub Username

@todaywasawesome

### Sub-project(s)

Promotion is requested for the following sub-project(s). 

- [x] Argo CD
- [ ] Argo Events
- [ ] Argo Rollouts
- [ ] Argo Workflows

### Requirements

- [x] Reviewer for at least 3 months (as of the membership meeting date)
- [x] Reviewer for or author of at least 10 substantial PRs to the codebase
   - [refactor: Update notification engine](https://github.com/argoproj/argo-cd/pull/9386)
   - [Add retry to cluster generation for testing in hack folder](https://github.com/argoproj/argo-cd/pull/11067)
   - [[Hack] Add concurrency to cluster creation in resource generator.](https://github.com/argoproj/argo-cd/pull/11266)
   - [docs: Feature bounty proposal (Experimental)](https://github.com/argoproj/argo-cd/pull/14234)
   - [docs: Update Okta OIDC SSO docs](https://github.com/argoproj/argo-cd/pull/13811#top)
     [Requesting improvements](https://github.com/argoproj/argo-cd/pull/13811#pullrequestreview-1470224123) to docs before approving.
   - [fix: remove all repo update](https://github.com/argoproj/argo-cd/pull/13968)
     Offering [pushback](https://github.com/argoproj/argo-cd/pull/13968#pullrequestreview-1472658348) on changes which might not be necessary/helpful.
   - [chore: support running dockerized toolchain in rootless mode](https://github.com/argoproj/argo-cd/pull/14088#top)
     [Testing locally](https://github.com/argoproj/argo-cd/pull/14088#pullrequestreview-1502239946) before approving.
   - [docs: Added information about scopes (#2782)](https://github.com/argoproj/argo-cd/pull/14354#top)
     Dropping [suggestions](https://github.com/argoproj/argo-cd/pull/14354#discussion_r1254498197) for quick/easy reviews.
   - [docs: add the default resource exclusions](https://github.com/argoproj/argo-cd/pull/13897)
     Another [good, solid suggestion](https://github.com/argoproj/argo-cd/pull/13897#discussion_r1223209261).
   - [fix: Fixes sharding placement algorithm and allows development of alternative algorithms](https://github.com/argoproj/argo-cd/pull/13018#top)
     Attention to [detail](https://github.com/argoproj/argo-cd/pull/13018#discussion_r1191351650).

### Lead Sponsor(s)

Promotion to Approver requires sponsorship from at least one sub-project Lead.

- @<sponsor-1>

### Other Sponsors

- @crenshaw-dev

**Comment by todaywasawesome** [comment]
Aw! Thanks!
