### ISSUE TITLE
REQUEST: Promotion to Reviewer(docs) for @morey-tech

### ISSUE THREAD

**Issue by crenshaw-dev** [argoproj/argoproj#229]
### GitHub Username

@morey-tech

### Sub-project(s)

Promotion is requested for the following sub-project(s).

- [x] Argo CD
- [ ] Argo Events
- [ ] Argo Rollouts
- [ ] Argo Workflows

### Requirements

- [x] Member for at least 3 months (as of the membership meeting date)
- [x] Reviewer for or author of at least 5 substantial PRs to the codebase
    - [docs: add helm values declarative syntax](https://github.com/argoproj/argo-cd/pull/13661)
    - [docs: add scalability benchmarking proposal](https://github.com/argoproj/argo-cd/pull/12662)
    - [fix: support for enabling progressive rollouts from argocd-cmd-params-cm](https://github.com/argoproj/argo-cd/pull/11776#top)
    - [docs: fix web terminal step list numbering](https://github.com/argoproj/argo-cd/pull/11590#top)
    - [docs: clarify value for disabling tools](https://github.com/argoproj/argo-cd/pull/11395#top)

### Lead Sponsor(s)

Promotion to Reviewer requires sponsorship from at least one sub-project Lead.

- @<sponsor-1>

### Other Sponsors

- @crenshaw-dev

**Comment by terrytangyuan** [comment]
+1
