### ISSUE TITLE
REQUEST: New membership for kshamajain99

### ISSUE THREAD

**Issue by kshamajain99** [argoproj/argoproj#23]
### GitHub Username
kshamajain99

### Organization you are requesting membership in
argoproj

### Requirements
- [x] I have reviewed the community membership guidelines (https://github.com/argoproj/argoproj/blob/master/community/membership.md)
- [x] I have enabled 2FA on my GitHub account (https://github.com/settings/security)
- [x] I am actively contributing to 1 or more Argoproj subprojects
  - [x] I am currently contributing to ArgoCD
- [x] I have two sponsors that meet the sponsor requirements listed in the community membership guidelines
- [x] I have spoken to my sponsors ahead of this application, and they have agreed to sponsor my application

### Sponsors
- @alexmt 
- @jessesuen 

### List of contributions to the Argoproj project
https://github.com/argoproj/argo-cd/pull/4785

**Comment by jessesuen** [comment]
I approve.

**Comment by alexmt** [comment]
Approved!
