### ISSUE TITLE
REQUEST: Promotion to Reviewer for @Joibel

### ISSUE THREAD

**Issue by Joibel** [argoproj/argoproj#231]
### GitHub Username

@Joibel

### Sub-project(s)
Promotion is requested for the following sub-project(s).

- [ ] Argo CD
- [ ] Argo Events
- [ ] Argo Rollouts
- [x] Argo Workflows

### Requirements

- [x] Member for at least [3 months](https://github.com/argoproj/argoproj/pull/209) (as of the membership meeting date) 
- [x] Reviewer for or author of at least 5 substantial PRs to the codebase.
I'm putting forward a bunch of small commits for some of these as they're more reviewable and merge-able that way.
  - Took devcontainer development forward so that it was generally usable, and have reviewed several further improvements to this 
    - https://github.com/argoproj/argo-workflows/pull/11104
    - https://github.com/argoproj/argo-workflows/pull/11115
    - As reviewer https://github.com/argoproj/argo-workflows/pull/11350
    - https://github.com/argoproj/argo-workflows/pull/11153
    - https://github.com/argoproj/argo-workflows/pull/11162
    - As reviewer https://github.com/argoproj/argo-workflows/pull/11981
  - Improved memoization so that it works in more cases, and based on popularity of the idea, changed it to allow 'no output' memoization.
    - https://github.com/argoproj/argo-workflows/pull/11225
    - https://github.com/argoproj/argo-workflows/pull/11257
    - https://github.com/argoproj/argo-workflows/pull/11379
    - https://github.com/argoproj/argo-workflows/pull/12119
  - Made retryPolicy saner so that it behaves more like people would expect. Included diagramming in the documentation. https://github.com/argoproj/argo-workflows/pull/11005
  - Improved how hook expressions are handled https://github.com/argoproj/argo-workflows/pull/10919
  - https://github.com/argoproj/argo-workflows/pull/11151
  - Allowed hooks to be added globally in workflowDefaults https://github.com/argoproj/argo-workflows/pull/11214 and then fixed it in https://github.com/argoproj/argo-workflows/pull/11693

Reviews where I've contributed to changes across the controller codebase:
  - https://github.com/argoproj/argo-workflows/pull/11736
  - https://github.com/argoproj/argo-workflows/pull/11760
  - https://github.com/argoproj/argo-workflows/pull/11456
  - https://github.com/argoproj/argo-workflows/pull/11350
  - https://github.com/argoproj/argo-workflows/pull/10777

Other Notes

Authored [24 merged PRs](https://github.com/argoproj/argo-workflows/pulls?q=is%3Apr+author%3AJoibel+is%3Aclosed)
I have contributed in #argo-workflows and #argo-cd in slack on many issues.

In the [6 months](https://argo.devstats.cncf.io/d/48/users-statistics-by-repository-group?orgId=1&var-period=w&var-metric=contributions&var-repogroup_name=argoproj%2Fargo-workflows&var-users=All&from=now-6M&to=now) since being a member I am 7th on the CNCF DevStats for Argo Workflows.

![image](https://github.com/argoproj/argoproj/assets/1827156/fc962ecf-0f78-41b3-8627-2bc7bfa39955)

### Lead Sponsor(s)

Promotion to Reviewer requires sponsorship from at least one sub-project Lead.

### Other Sponsors

- @juliev0

**Comment by sarabala1979** [comment]
Hi @Joibel 
Argoproj maintainers reviewed your request. Here is the feedback from the team.

You are on track.
You are almost there.
The team is looking for you to contribute to more features/issues in upcoming releases.
The team will review your request in the next membership meeting.

Thanks for your contribution.

**Comment by sarabala1979** [comment]
+1
