### ISSUE TITLE
REQUEST: Promotion to Approver for @isubasinghe

### ISSUE THREAD

**Issue by isubasinghe** [argoproj/argoproj#232]
### GitHub Username
@isubasinghe

### Sub-project(s)

Promotion is requested for the following sub-project(s). 

- [ ] Argo CD
- [ ] Argo Events
- [ ] Argo Rollouts
- [x] Argo Workflows

### Requirements

- [x] Reviewer for at least 3 months (as of the membership meeting date)
- [x] Reviewer for or author of at least 10 substantial PRs to the codebase
   - https://github.com/argoproj/argo-workflows/pull/11503
   - https://github.com/argoproj/argo-workflows/pull/11493
   - https://github.com/argoproj/argo-workflows/pull/11451
   - https://github.com/argoproj/argo-workflows/pull/10999
   - https://github.com/argoproj/argo-workflows/pull/10214
   - https://github.com/argoproj/argo-workflows/pull/10191
   - https://github.com/argoproj/argo-workflows/pull/9995
   - https://github.com/argoproj/argo-workflows/pull/7854
   - https://github.com/argoproj/argo-workflows/pull/7837
   - https://github.com/argoproj/argo-workflows/pull/10457
   - https://github.com/argoproj/argo-workflows/pull/12573
   - https://github.com/argoproj/argo-workflows/pull/12555
   - https://github.com/argoproj/argo-workflows/pull/12520
   - https://github.com/argoproj/argo-workflows/pull/12503
   
- [x] Contributed feedback (both actionable and not) on reviews
   - https://github.com/argoproj/argo-workflows/pull/12522
   - https://github.com/argoproj/argo-workflows/pull/12527
   - https://github.com/argoproj/argo-workflows/pull/12487
   - https://github.com/argoproj/argo-workflows/pull/12413
   - https://github.com/argoproj/argo-workflows/pull/12350
   - https://github.com/argoproj/argo-workflows/pull/12467
   - https://github.com/argoproj/argo-workflows/pull/12383
   - https://github.com/argoproj/argo-workflows/pull/12237
   - https://github.com/argoproj/argo-workflows/pull/11909
   - https://github.com/argoproj/argo-workflows/pull/11768
   - https://github.com/argoproj/argo-workflows/pull/11738
   - https://github.com/argoproj/argo-workflows/pull/11707
   - https://github.com/argoproj/argo-workflows/pull/12199
   - https://github.com/argoproj/argo-workflows/pull/12198
   - https://github.com/argoproj/argo-workflows/pull/11646
   - https://github.com/argoproj/argo-workflows/pull/11484
   - https://github.com/argoproj/argo-workflows/pull/11096
   - https://github.com/argoproj/argo-workflows/pull/11016
   - https://github.com/argoproj/argo-workflows/pull/10307
   - Many more see: https://github.com/argoproj/argo-workflows/pulls?q=is%3Apr+is%3Aopen+reviewed-by%3Aisubasinghe

74 reviews in total. 

In general I have a pretty good understanding of the codebase now, after being on this project for approx 2 years or so.
###

### Lead Sponsor(s)

Promotion to Approver requires sponsorship from at least one sub-project Lead.

- 

### Other Sponsors

- @juliev0

**Comment by sarabala1979** [comment]
Hi @isubasinghe 
Argoproj maintainers reviewed your request.  Here is the feedback from the team.
1. You are on track. 
2. You are almost there. 
3. The team is looking for you to contribute to more complex features/issues in upcoming releases.

The team will review your request in the next membership meeting.

Thanks for your contribution.

**Comment by isubasinghe** [comment]
Thanks for the feedback @sarabala1979, looking forward to the next membership meeting.

**Comment by terrytangyuan** [comment]
Hi @isubasinghe, we have reviewed your case in today's membership meeting. You are definitely on the right track and we will revisit your case in the next meeting. Here are some feedback from the team that you can work on in the meantime:
* More solid and in-depth reviews to catch bugs in PRs before they get through.
* More involvement in issue triaging (actively fixing them or mentoring new contributors to participate) and attending community meetings/discussions.

Thank you for your great contributions and keep up the good work!

**Comment by juliev0** [comment]
Hey @isubasinghe. Argoproj maintainers reviewed your request today. You've contributed a lot of great PRs that show depth in the code, plus innovation.

However, since an Approver's core responsibility is to merge PRs, would you be able to spend some of your time over the next 3 months reviewing other people's PRs? (going for depth over quantity)

(Also, there may be an oversight where the current Reviewer Responsibilities aren't included in the Approver Requirements ([here](https://github.com/argoproj/argoproj/blob/main/community/membership.md)), so just make sure you're aware of those as needed.)

Thank you!

**Comment by isubasinghe** [comment]
Sorry for the late response @juliev0, I was a bit busy with my full time job and couldn't get to argo workflows in the past month or so. But I am back now!

But firstly, I do really appreciate the transparency, I shall put more effort into reviewing PRs from now on.

Thanks!

**Comment by juliev0** [comment]
> Sorry for the late response @juliev0, I was a bit busy with my full time job and couldn't get to argo workflows in the past month or so. But I am back now!
> 
> But firstly, I do really appreciate the transparency, I shall put more effort into reviewing PRs from now on.
> 
> Thanks!

Thanks, Isitha! Sorry it wasn't very clear before. I just added a clarification to the [Approver Requirements](https://github.com/argoproj/argoproj/blob/main/community/membership.md) to clarify that better this week.

**Comment by juliev0** [comment]
Hey @isubasinghe - I'd like to update the template for these Issues for the author to highlight PRs that they reviewed and/or specific comments with actionable feedback - in the meantime, would you mind calling those out to help with reviewing this?

**Comment by isubasinghe** [comment]
Thanks @juliev0 I shall update this tomorrow evening in that case.

**Comment by sarabala1979** [comment]
@isubasinghe Please update the recent works

**Comment by isubasinghe** [comment]
Done @sarabala1979
