### ISSUE TITLE
REQUEST: New membership for @izturn

### ISSUE THREAD

**Issue by izturn** [argoproj/argoproj#240]
### GitHub Username

@izturn

### Requirements
- [X] I have reviewed [the community membership guidelines](https://github.com/argoproj/argoproj/blob/master/community/membership.md)
- [X] I have [enabled 2FA on my GitHub account](https://github.com/settings/security)
- [X] I am actively contributing to 1 or more Argoproj subprojects
- [ ] I have two sponsors that meet the sponsor requirements listed in the community membership guidelines
- [ ] I have spoken to my sponsors ahead of this application, and they have agreed to sponsor my application

### Sponsors
- @zachaller
- 

### List of contributions to the Argoproj project
- [PRs reviewed / authored - 1open / 5 closed](https://github.com/argoproj/argo-rollouts/pulls?q=is%3Apr+author%3Aizturn)
- Issues responded to
- Projects I am involved with
  +  https://github.com/argoproj-labs/rollouts-plugin-trafficrouter-contour

**Comment by zachaller** [comment]
did not hear back from slack msg, closing this for now please reach out of if you are still interested in becoming a member
