### ISSUE TITLE
REQUEST: Promotion to Reviewer for @agilgur5

### ISSUE THREAD

**Issue by agilgur5** [argoproj/argoproj#242]
Follow-up to #221

### GitHub Username

@agilgur5

### Sub-project(s)

Promotion is requested for the following sub-project(s).

- [ ] Argo CD
- [ ] Argo Events
- [ ] Argo Rollouts
- [x] Argo Workflows

Sub-sub-projects:
- [x] `argo-ui` would be helpful as well if possible
- [x] `pkg` too as it has some helpers that Workflows uses. But I haven't touched that as much as `argo-ui`

### Requirements

- [x] Member for at least 3 months (as of the membership meeting date)
- [x] Reviewer for or author of at least 5 substantial PRs to the codebase

#### Selected PRs
- An upgrade of virtually the entire UI build system that was several _years_ out-of-date: https://github.com/argoproj/argo-workflows/pull/11628
  - This may not be that many LoC (outside of the lockfile), but was a gargantuan effort that required significant trial-and-error, finding lots of dated upgraded guides, etc. The PR description is long and full of links about this.
  - Fixed a pretty gnarly, subtle follow-up bug from this by using a super minimal, dependency free implementation of an FNV hash: https://github.com/argoproj/argo-workflows/pull/11766
- Some very complicated UI refactors of some of the most complex components in the codebase: https://github.com/argoproj/argo-workflows/pull/11891, https://github.com/argoproj/argo-workflows/pull/11794
  - I've also spear-headed, completed, and reviewed nearly all of the UI hooks / [functional components refactor](https://github.com/argoproj/argo-workflows/issues/9810), involving 30+ components (see my comments on the issue which link to many more PRs)
  - And completed removal of all explicitly deprecated components, some of which used 6+ year old APIs that pre-date [the official React Context API](https://legacy.reactjs.org/blog/2018/03/29/react-v-16-3.html#official-context-api)
- Full copy-edits of multiple pages in the Docs: https://github.com/argoproj/argo-workflows/pull/11516, https://github.com/argoproj/argo-workflows/pull/11943
  - I've added to many parts of the docs and have rewritten sizeable chunks. I have also significantly enhanced and fixed the [docs contribution guidelines](https://github.com/argoproj/argo-workflows/pull/11712)
- Fixed a pretty gnarly and subtle UI bug that caused dropped network requests: https://github.com/argoproj/argo-workflows/pull/11711
  - I suspected this myself during [a code review](https://github.com/argoproj/argo-workflows/pull/11676#discussion_r1306119462) of a PR (not due to the changes of the PR, but was an incidental, related finding), then successfully root caused it all the way down to a status code in the log in [the issue](https://github.com/argoproj/argo-workflows/issues/11661). Did so after a [request for assistance](https://cloud-native.slack.com/archives/C0510EUH90V/p1692990152966289) from @terrytangyuan. See detailed PR description et al for more details.
    - Not that it's bad to ask for help in any way, shape, or form! I mean that I've been helping out wherever I can and whenever asked 🙂 
- Fixed two fairly popular `argo-helm` bugs by root causing them upstream to the Workflows Server itself: https://github.com/argoproj/argo-workflows/pull/11426
  - Only a few LoC, but the [root cause analysis](https://github.com/argoproj/argo-helm/issues/2159#issuecomment-1646988596) took a solid amount of time to dive in and figure out what was going on
  - My first contribution to Workflows, https://github.com/argoproj/argo-workflows/pull/10927, also required a substantial root cause analysis to determine. These both happen to be due to the Server's SSO logic
- Fixed [some flakey tests](https://github.com/argoproj/argo-workflows/pull/11753) that were occurring 50%+ of the time (anecdotally) on CI, significantly blocking PRs
  - These took quite some time to track down and pattern-match, and because they're E2Es, they were quite time-consuming to test as well.
   - This was a [dramatic improvement](https://cloud-native.slack.com/archives/C0510EUH90V/p1692120705627719) to CI success rates to 90%+ (anecdotally) -- some of the most impactful 5 LoC I've written 😅 
   - Made other significant QoL improvements to the developer experience on Workflows as well, such as https://github.com/argoproj/argo-workflows/pull/12006, https://github.com/argoproj/argo-workflows/pull/11981, https://github.com/argoproj/argo-workflows/pull/11928
- Did a substantial upgrade of `argo-ui` which required a lot of compatibility fixes and fairly sizeable debugging: https://github.com/argoproj/argo-workflows/pull/11585
  - Did so after [request for assistance](https://cloud-native.slack.com/archives/C0510EUH90V/p1691538680554359) from @terrytangyuan. I debugged most of it in [this comment](https://github.com/argoproj/argo-workflows/pull/11510#issuecomment-1678520239) and then fixed it all. See detailed comment and PR description for more details.
  - @terrytangyuan and @sarabala1979 then asked me to help with several other dependency upgrades that were failing CI. Some of these were also quite complicated to investigate and upgrade: https://github.com/argoproj/argo-workflows/pull/11593, https://github.com/argoproj/argo-workflows/pull/11710, https://github.com/argoproj/argo-workflows/pull/11598#issuecomment-1696429512 (and further comments), https://github.com/argoproj/argo-workflows/pull/11640#issuecomment-1696222851 + https://github.com/argoproj/argo-workflows/pull/11418#issuecomment-1696260188
    - Same as above, not that it's bad to ask for help in any way, shape, or form! I mean that I've been helping out wherever I can and whenever asked 🙂 
    - Solo found and resolved several other dependency issues: https://github.com/argoproj/argo-workflows/pull/11630, https://github.com/argoproj/argo-workflows/pull/11637, https://github.com/argoproj/argo-workflows/pull/11641
  - This also led me to take an interest in contributing to and [improving the state of](https://github.com/argoproj/argo-ui/issues/453) the fairly neglected [`argo-ui`](https://github.com/argoproj/argo-ui) repo. See below in "Other" about stats for this repo and contributions I've made there
      
#### Selected Code Reviews
- A few detailed UI code reviews I did that went through several iterations: https://github.com/argoproj/argo-workflows/pull/11811, https://github.com/argoproj/argo-workflows/pull/11790, https://github.com/argoproj/argo-workflows/pull/11803
  - There were some very subtle bugs (e.g. global CSS issues, memoization issues) that I caught during these reviews too
  - Received [much love](https://github.com/argoproj/argo-workflows/pull/11803#issuecomment-1722068963) from a first time ever OSS contributor too! ❤️ 🎉  
  - Also caught a few missed anti-patterns and bugs in these UI PRs: https://github.com/argoproj/argo-workflows/pull/11686#discussion_r1306692491, https://github.com/argoproj/argo-workflows/pull/11973#discussion_r1353099743
- Several Server code reviews I did went through many iterations as well  
  - This PR had 3 features/fixes in a single PR and had 30+ comments from me on it: https://github.com/argoproj/argo-workflows/pull/11777
  - Reviewed the `filterSSOGroups` feature in-depth as well as its docs: https://github.com/argoproj/argo-workflows/pull/11774, https://github.com/argoproj/argo-workflows/pull/11778
    - I would say that some of my suggestions were important improvements, such as compiling and erroring out early, following the existing docs style, adding details about gotchas, etc.
      - Notably my in-depth reviews caught some missed side-effects to other parts of the codebase among other issues. 
- Some Controller bugfixes that have went through multiple iterations after I caught some missed regressions during review: https://github.com/argoproj/argo-workflows/pull/11855, https://github.com/argoproj/argo-workflows/pull/11799     
- Many of my docs code reviews were fairly substantial rewrites of the original PR: https://github.com/argoproj/argo-workflows/pull/11342#pullrequestreview-1527437343, https://github.com/argoproj/argo-workflows/pull/11405#issuecomment-1646964988, https://github.com/argoproj/argo-workflows/pull/11732#pullrequestreview-1608607518, https://github.com/argoproj/argo-workflows/pull/11735#pullrequestreview-1608622598

#### Total
- [100+ PRs](https://github.com/argoproj/argo-workflows/pulls?q=author%3Aagilgur5) opened
- [215+](https://github.com/argoproj/argo-workflows/pulls?q=is%3Apr+involves%3Aagilgur5+-author%3Aagilgur5) PRs responded to and/or reviewed
  - Have received much [appreciation](https://github.com/argoproj/argo-workflows/pull/11811#issuecomment-1731035357) [for](https://github.com/argoproj/argo-workflows/pull/11701#discussion_r1309787214) [my](https://github.com/argoproj/argo-workflows/pull/11735#discussion_r1314418755) [thorough](https://github.com/argoproj/argo-workflows/pull/11577#issuecomment-1678437422) [reviews](https://github.com/argoproj/argo-workflows/pull/11751#discussion_r1317505208) 🙂 
  - See also Julie's comment [below](https://github.com/argoproj/argoproj/issues/242#issuecomment-1754310090) ❤️ 
- See issues, discussions, etc stats below in "Other"

#### Familiarity
- I am very familiar with the Docs, UI, CI + build systems, Server, CLI, and relatively familiar with the main Controller loop, but still have more to learn there, in the Executor, and some of the test suites.
  - I think I may know the Docs the best of any current contributor+ (if I may be so bold as to say), the UI build system the best (given I've rewritten and upgraded most of it), and large portions of the UI (similarly have refactored large parts of it).
    - Have reviewed most docs + UI PRs since becoming a Member, sometimes in great detail, finding bugs and requesting many changes
- I'm also a very experienced user, hence why I can contribute to docs and answer questions very well 😉 
  - Also why I contribute to `argo-helm` occasionally 
- I think most contributors know me too, in the other disambiguation of the word "familiarity" 😝 

#### Other contributions and stats
- According to CNCF DevStats for Argo Workflows (take that with the same of grain of salt as any other metric), I am top 4 contributors in [the past 3 years](https://argo.devstats.cncf.io/d/48/users-statistics-by-repository-group?orgId=1&var-period=w&var-metric=contributions&var-repogroup_name=argoproj%2Fargo-workflows&var-users=All&from=now-3y&to=now) that DevStats tracks, top 2 in [past year](https://argo.devstats.cncf.io/d/48/users-statistics-by-repository-group?orgId=1&var-period=w&var-metric=contributions&var-repogroup_name=argoproj%2Fargo-workflows&var-users=All&from=now-1y&to=now) - [6 months](https://argo.devstats.cncf.io/d/48/users-statistics-by-repository-group?orgId=1&var-period=w&var-metric=contributions&var-repogroup_name=argoproj%2Fargo-workflows&var-users=All&from=now-6M&to=now), and top 1 in [past 3 months](https://argo.devstats.cncf.io/d/48/users-statistics-by-repository-group?orgId=1&var-period=w&var-metric=contributions&var-repogroup_name=argoproj%2Fargo-workflows&var-users=All&from=now-90d&to=now) - [1 month](https://argo.devstats.cncf.io/d/48/users-statistics-by-repository-group?orgId=1&var-period=w&var-metric=contributions&var-repogroup_name=argoproj%2Fargo-workflows&var-users=All&from=now-30d&to=now)
  - Here's a screenshot at 2 years and at 6 months (I am in purple):
    ![Screenshot 2023-10-31 at 3 27 50 AM - 2 years](https://github.com/argoproj/argoproj/assets/4970083/bbae916e-1eab-44fa-b31e-a50459eeee8a)
    ![Screenshot 2023-10-31 at 3 28 59 AM -  6 months](https://github.com/argoproj/argoproj/assets/4970083/06d35c8f-edb0-4fc3-b915-917850f52888)

  - Notably, I have achieved that despite only actively contributing the past 4 months, i.e. in a much smaller time period than the width of the range, the entirety of which the average is taken from.
  - Also notably, I have largely not been paid by any company to make most of my contributions (maybe my first one could be considered under scope of my employer as it was a very specific feature for their SSO system)
- I've responded to hundreds of users over issues ([220+](https://github.com/argoproj/argo-workflows/issues?q=is%3Aissue+commenter%3Aagilgur5)), discussions ([70+](https://github.com/argoproj/argo-workflows/discussions?discussions_q=commenter%3Aagilgur5+) + many sub-discussions in giscus), and Slack
  - re: Slack, can search me in [#argo-workflows](https://cloud-native.slack.com/archives/C01QW9QSSSK) where I am very active, [#argo-contributors](https://cloud-native.slack.com/archives/C020XM04CUW) where I am occasionally active, [#argo-wf-contributors](https://cloud-native.slack.com/archives/C0510EUH90V) where I've weighed in as well as made bugfixes, reviews, and changes, and an occasional answer in [#argo-helm-charts](https://cloud-native.slack.com/archives/C02097VUKUM) and [#argo-events](https://cloud-native.slack.com/archives/C01TNKD6KL6).
  - Have closed out and consolidated many issues, added [new](https://cloud-native.slack.com/archives/C0510EUH90V/p1692641716347669) [labels](https://cloud-native.slack.com/archives/C0510EUH90V/p1692642013912419) and [label descriptions](https://cloud-native.slack.com/archives/C0510EUH90V/p1692120705627719), significantly reorganized the usage of some existing labels and significantly labeled hundreds of issues, and made other maintenance improvements (such as recommending [removing](https://github.com/argoproj/argo-workflows/issues/11802#issuecomment-1720117452) [`stalebot`](https://github.com/argoproj/argo-workflows/pull/11836) and [Snyk automated PRs](https://github.com/argoproj/argo-workflows/issues/11844))
  - Helped several users in issues or Slack [make](https://github.com/argoproj/argo-workflows/pull/11855) [their](https://github.com/argoproj/argo-workflows/pull/11799#pullrequestreview-1620959095) [first](https://github.com/argoproj/argo-workflows/pull/11432#issuecomment-1648183951) [contributions](https://github.com/argoproj/pkg/pull/486#issuecomment-1689389993)! 🎉 
  - Encouraged some contributors to request membership as well, such as in #249 and #251 in this repo 🙌 🙂 
  - Also helped making sure some useful (and sometimes stale) bugfixes got cherry-picked into patch releases
  - Also have been trying to [put the lights back on](https://github.com/argoproj/argo-ui/issues/453) on `argo-ui` ([issues + PRs](https://github.com/argoproj/argo-ui/issues?q=commenter%3Aagilgur5), [Slack thread](https://cloud-native.slack.com/archives/C020XM04CUW/p1692085374857769))
- Have come to every [Workflows Contributor Meeting](https://docs.google.com/document/d/1tznN5LB-KrNkC6dmeIzpKfuyvZWgCJpRuS-E84zseC8/edit#heading=h.gtrya8ijaa1k) since I [learned they existed](https://cloud-native.slack.com/archives/C020XM04CUW/p1691072343983519?thread_ts=1691071518.169849&cid=C020XM04CUW) as well as the [Community Meetings](https://docs.google.com/document/d/1DKR4VQ-04DJfHOh6S6-cbQw6MiWppC0k7afORiiy6XQ/edit) and one Bug Triage meeting.
  - I've also done most of the Bug Triage independently on my own whenever I check on the issues after I learned the process (as @juliev0 can attest to).
    - **EDIT**: The Bug Triage meeting has now [been cancelled](https://cloud-native.slack.com/archives/C0510EUH90V/p1698338891995169) since I've been doing triage myself near daily the past few months
- Come to [SIG Scalability](https://docs.google.com/document/d/1etHn3EDJN1KLvVKhLKFl634DMlJbfSFjtZoQopEt5Rw/edit#heading=h.i76q0dpxny2z) when I can (can also find me in [#argo-sig-scalability](https://cloud-native.slack.com/archives/C04SURUPDL2))
  - Working on [auto-scaling sharding](https://github.com/argoproj/argo-workflows/issues/9990#issuecomment-1732337352) for Workflows's Controller as well
- Come to [SIG Security](https://docs.google.com/document/d/1nl1adCRf4tD87Y01i3JcrLcHvtm1O5a7slqzNstct94/edit#heading=h.tv7amshpisnr) as well. I ran a security team at my last job, so fairly experienced in blue teaming InfraSec, AppSec, and ITSec
  - Working on [SLSA Level 3+](https://github.com/argoproj/argo-workflows/issues/12099) and other [OpenSSF Scorecard improvements](https://github.com/argoproj/argo-workflows/issues/12031) for Workflows
- Submitted a CFP on various Multi-cluster Architectures for ArgoCon NA 2023. Currently waitlisted!
  - **EDIT**: may end up presenting this at a recorded Community Meeting instead

#### Misc Notes

I am also a very experienced maintainer, having maintained other repos since ~2014, which is why I'm pretty comfortable in the issues and with the general OSS process. Here are [a](https://github.com/ezolenko/rollup-plugin-typescript2/issues?q=involves%3Aagilgur5+) [few](https://github.com/agilgur5/react-signature-canvas) [I](https://github.com/agilgur5/mst-persist) [maintain](https://github.com/agilgur5/django-serializable-model)/[previously maintained](https://github.com/jaredpalmer/tsdx/issues?q=commenter%3Aagilgur5+).
Contribute to various projects in the k8s ecosystem too, Argo obviously being the one I contribute to far more than any others at this point 😉 

### Lead Sponsor(s)

Promotion to Reviewer requires sponsorship from at least one sub-project Lead.

- @terrytangyuan

### Other Sponsors

Listing some from the same sub-project:

- Approvers:
  - @juliev0 
- Reviewers:
  - @isubasinghe 
- Members:
  - @JPZ13 
  - @caelan-io 
  - @jmeridth 
  - @toyamagu-2021 
- probably more who haven't seen this yet too 🙂

**Comment by juliev0** [comment]
Happy to be a second sponsor!

**Comment by juliev0** [comment]
@agilgur5 probably gives the impression to many of the users writing issues and contributors writing PRs that he is one of the central maintainers of the project. The activity level on the project has probably doubled since he started become so active.

He's also looking at central issues within the project that have been problematic for awhile such as how to fix our flakey CI tests.

**Comment by JPZ13** [comment]
Happy to sponsor

**Comment by terrytangyuan** [comment]
+1

**Comment by isubasinghe** [comment]
Happy to sponsor, @agilgur5 has been doing some great work. Really appreciate trying to understand bugs at their core problem.

**Comment by juliev0** [comment]
I might be wrong, but I just want to add that @agilgur5 might be the most thorough PR reviewer on the project from what I've seen (which to me is the most important criteria for promotion).

**Comment by sarabala1979** [comment]
+1 Happy to sponsor @agilgur5!  Thanks, @agilgur5 for your contribution to Argo worklow
