### ISSUE TITLE
REQUEST: New membership for @sonbui00

### ISSUE THREAD

**Issue by sonbui00** [argoproj/argoproj#249]
### GitHub Username

@sonbui00

### Requirements
- [x] I have reviewed [the community membership guidelines](https://github.com/argoproj/argoproj/blob/master/community/membership.md)
- [x] I have [enabled 2FA on my GitHub account](https://github.com/settings/security)
- [x] I am actively contributing to 1 or more Argoproj subprojects
- [ ] I have two sponsors that meet the sponsor requirements listed in the community membership guidelines
- [x] I have spoken to my sponsors ahead of this application, and they have agreed to sponsor my application

### Sponsors
- @terrytangyuan
- @<sponsor-2>

### Other Sponsors
- @agilgur5
- @<sponsor-2>

### List of contributions to the Argoproj project
- PRs reviewed / authored (13)
https://github.com/search?q=org%3Aargoproj+author%3Asonbui00&type=pullrequests
- Issues responded to (10)
https://github.com/search?q=org%3Aargoproj++involves%3Asonbui00&type=issues
- Projects I am involved with (2)
[Argo Workflow](https://github.com/argoproj/argo-workflows/)
[Argo Event](https://github.com/argoproj/argo-events/)

**Comment by terrytangyuan** [comment]
Happy to sponsor!

**Comment by agilgur5** [comment]
+1 as an "other sponsor" (approver+ is required for main sponsors). @sonbui00 has made some useful and complex contributions to Workflows 🙂 

For context, I also mentioned Membership [in this comment](https://github.com/argoproj/argo-workflows/pull/11707#issuecomment-1726962355) and this was one of the reasons I asked [about nominations on Slack](https://cloud-native.slack.com/archives/C020XM04CUW/p1695599315295319).
