### ISSUE TITLE
REQUEST: New membership for @sunyeongchoi

### ISSUE THREAD

**Issue by sunyeongchoi** [argoproj/argoproj#250]
### GitHub Username

@sunyeongchoi

### Requirements
- [X] I have reviewed [the community membership guidelines](https://github.com/argoproj/argoproj/blob/master/community/membership.md)
- [X] I have [enabled 2FA on my GitHub account](https://github.com/settings/security)
- [X] I am actively contributing to 1 or more Argoproj subprojects
- [X] I have two sponsors that meet the sponsor requirements listed in the community membership guidelines
- [X] I have spoken to my sponsors ahead of this application, and they have agreed to sponsor my application

### Sponsors
- @terrytangyuan 
- @

### List of contributions to the Argoproj project
- PRs reviewed / authored
https://github.com/argoproj/argo-workflows/pull/11816
https://github.com/argoproj/argo-workflows/pull/11761
https://github.com/argoproj/argo-workflows/pull/11703
https://github.com/argoproj/argo-workflows/pull/11701
https://github.com/argoproj/argo-workflows/pull/11684
https://github.com/argoproj/argo-workflows/pull/11662

- Issues responded to
https://github.com/argoproj/argo-workflows/issues/11815
https://github.com/argoproj/argo-workflows/issues/11702
https://github.com/argoproj/argo-workflows/issues/11700

- Projects I am involved with
https://github.com/argoproj/argo-workflows

**Comment by terrytangyuan** [comment]
+1 Thank you for your contributions!

**Comment by sarabala1979** [comment]
+1
