### ISSUE TITLE
REQUEST: New membership for @shmruin

### ISSUE THREAD

**Issue by shmruin** [argoproj/argoproj#251]
### GitHub Username

@shmruin

### Requirements
- [x] I have reviewed [the community membership guidelines](https://github.com/argoproj/argoproj/blob/master/community/membership.md)
- [x] I have [enabled 2FA on my GitHub account](https://github.com/settings/security)
- [x] I am actively contributing to 1 or more Argoproj subprojects
- [x] I have two sponsors that meet the sponsor requirements listed in the community membership guidelines
- [x] I have spoken to my sponsors ahead of this application, and they have agreed to sponsor my application

### Sponsors
- @agilgur5 
- @

### List of contributions to the Argoproj project
- PRs reviewed / authored
  - https://github.com/argoproj/argo-workflows/pull/11456
  - https://github.com/argoproj/argo-workflows/pull/11495
  - https://github.com/argoproj/argo-workflows/pull/11623
  - https://github.com/argoproj/argo-workflows/pull/11751
  - https://github.com/argoproj/argo-workflows/pull/11781
  - https://github.com/argoproj/argo-workflows/pull/11883
  - https://github.com/argoproj/argo-workflows/pull/12019
- Issues responded to
  - https://github.com/argoproj/argo-workflows/issues/11494
  - https://github.com/argoproj/argo-workflows/issues/11750
- Projects I am involved with
  - https://github.com/argoproj/argo-workflows

**Comment by terrytangyuan** [comment]
+1 Thank you for your contributions!

**Comment by agilgur5** [comment]
+1 as an "other sponsor" (as approver+ is required for main sponsors).@shmruin has had some great deep-dives and bugfixes!

I recommended membership and this was another reason I asked [about nominations on Slack](https://cloud-native.slack.com/archives/C020XM04CUW/p1695599315295319)

**Comment by sarabala1979** [comment]
+1
