### ISSUE TITLE
REQUEST: argo-helm scoped Approver Promotion Request for mbevc1

### ISSUE THREAD

**Issue by jmeridth** [argoproj/argoproj#253]
### GitHub Username

@mbevc1

## SCOPED

Scoped helm charts based [argo-helm CODEOWNERS file](https://github.com/argoproj/argo-helm/blob/main/CODEOWNERS):

- argo-cd

### Membership Requirements

- [x] I have reviewed the community membership guidelines (https://github.com/argoproj/argoproj/blob/master/community/membership.md)
- [x] I have enabled 2FA on my GitHub account (https://github.com/settings/security)
- [x] I am actively contributing to argo-helm
- [x] I have two sponsors who meet the sponsor requirements listed in the community membership guidelines
- [x] I have spoken to my sponsors ahead of this application, and they have agreed to sponsor my application

### Reviewer Requirements

- [x] argo-helm contributor for at least 3 months (as of the membership meeting date)
- [x] Reviewer for or author of at least 5 substantial PRs to the codebase (look below)

Pull Requests created and merged: [4](https://github.com/argoproj/argo-helm/pulls?q=is%3Apr+author%3Ambevc1+merged%3A2021-05-20..2021-08-20+archived%3Afalse+is%3Aclosed+)

Pull Requests reviewed: [17](https://github.com/argoproj/argo-helm/pulls?q=is%3Apr+reviewed-by%3Ambevc1+merged%3A2021-05-20..2021-08-20+archived%3Afalse+is%3Aclosed+)

### Approver Requirements

- [x] argo-helm contributor for at least 3 months (as of the membership meeting date)
- [x] Reviewer for or author of at least 10 substantial PRs to the codebase (look below)

Pull Requests created and merged: [3](https://github.com/argoproj/argo-helm/pulls?q=is%3Apr+author%3Ambevc1+merged%3A%3E2021-08-20+archived%3Afalse+is%3Aclosed+)

Pull Requests reviewed: [232](https://github.com/argoproj/argo-helm/pulls?q=is%3Apr+reviewed-by%3Ambevc1+merged%3A%3E2021-08-20+archived%3Afalse+is%3Aclosed+)

## SPONSORS

- @jmeridth
- @mkilchhofer

**Comment by mbevc1** [comment]
Thanks @jmeridth , but the correct username is `@mbevc1` :wink:

**Comment by jmeridth** [comment]
🤦 fixed
