### ISSUE TITLE
REQUEST: argo-helm scoped Approver Promotion Request for tico24

### ISSUE THREAD

**Issue by jmeridth** [argoproj/argoproj#255]
### GitHub Username

@tico24

## SCOPED

Scoped helm charts based [argo-helm CODEOWNERS file](https://github.com/argoproj/argo-helm/blob/main/CODEOWNERS):

- argo-cd
- argo-events
- argo-workflows

### Membership Requirements

- [x] I have reviewed the community membership guidelines (https://github.com/argoproj/argoproj/blob/master/community/membership.md)
- [x] I have enabled 2FA on my GitHub account (https://github.com/settings/security)
- [x] I am actively contributing to argo-helm
- [x] I have two sponsors who meet the sponsor requirements listed in the community membership guidelines
- [x] I have spoken to my sponsors ahead of this application, and they have agreed to sponsor my application

### Reviewer Requirements

- [x] argo-helm contributor for at least 3 months (as of the membership meeting date)
- [x] Reviewer for or author of at least 5 substantial PRs to the codebase (look below)

Pull Requests created and merged: [2](https://github.com/argoproj/argo-helm/pulls?q=is%3Apr+author%3Atico24+merged%3A2023-04-14..2023-07-14+archived%3Afalse+is%3Aclosed+)

Pull Requests reviewed: [24](https://github.com/argoproj/argo-helm/pulls?q=is%3Apr+reviewed-by%3Atico24+merged%3A2023-04-14..2023-07-14+archived%3Afalse+is%3Aclosed+)

### Approver Requirements

- [x] argo-helm contributor for at least 3 months (as of the membership meeting date)
- [x] Reviewer for or author of at least 10 substantial PRs to the codebase (look below)

Pull Requests created and merged: [4](https://github.com/argoproj/argo-helm/pulls?q=is%3Apr+author%3Atico24+merged%3A%3E2023-07-14+archived%3Afalse+is%3Aclosed+)

Pull Requests reviewed: [56](https://github.com/argoproj/argo-helm/pulls?q=is%3Apr+reviewed-by%3Atico24+merged%3A%3E2023-07-14+archived%3Afalse+is%3Aclosed+)

## SPONSORS

- @jmeridth
- @mkilchhofer

**Comment by tico24** [comment]
Updated metrics if useful:

APPROVER - From 7/14/2023 to present

- [x] PRs created and merged: [4](https://github.com/argoproj/argo-helm/pulls?q=is%3Apr+author%3Atico24+merged%3A%3E2023-07-14+archived%3Afalse+is%3Aclosed+)
- [x] PRs reviewed: [64](https://github.com/argoproj/argo-helm/pulls?q=is%3Apr+reviewed-by%3Atico24+merged%3A%3E2023-07-14+archived%3Afalse+is%3Aclosed+)
