### ISSUE TITLE
REQUEST: New membership for @shuangkun

### ISSUE THREAD

**Issue by shuangkun** [argoproj/argoproj#266]
### GitHub Username

@shuangkun

### Requirements
- [x] I have reviewed [the community membership guidelines](https://github.com/argoproj/argoproj/blob/master/community/membership.md)
- [x] I have [enabled 2FA on my GitHub account](https://github.com/settings/security)
- [x] I am actively contributing to 1 or more Argoproj subprojects
- [ ] I have two sponsors that meet the sponsor requirements listed in the community membership guidelines
- [ ] I have spoken to my sponsors ahead of this application, and they have agreed to sponsor my application

### Sponsors
- @terrytangyuan
- @Joibel 

### List of contributions to the Argoproj project
- PRs reviewed / authored
  - https://github.com/argoproj/argo-workflows/pull/12325
  - https://github.com/argoproj/argo-workflows/pull/12328
  - https://github.com/argoproj/argo-workflows/pull/12426
  - https://github.com/argoproj/argo-workflows/pull/12412
  - https://github.com/argoproj/argo-workflows/pull/12544
  - https://github.com/argoproj/argo-workflows/pull/12537
  - https://github.com/argoproj/argo-workflows/pull/12350
  - https://github.com/argoproj/argo-workflows/pull/12491
  - https://github.com/argoproj/argo-workflows/pull/12320
  - https://github.com/argoproj/argo-workflows/pull/12196
  - https://github.com/argoproj/argo-workflows/pull/12323
  - https://github.com/argoproj/argo-workflows/pull/12197
  - https://github.com/argoproj/argo-workflows/pull/12188
  - https://github.com/argoproj/argo-workflows/pull/12084
  - https://github.com/argoproj/argo-workflows/pull/11048
  - https://github.com/argoproj/argo-workflows/pull/12411
  - https://github.com/argoproj/argo-workflows/pull/12419
  - https://github.com/argoproj/argo-workflows/pull/12536
  - https://github.com/argoproj/argo-workflows/pull/12575
  - https://github.com/argoproj/argo-workflows/pull/12577
  - https://github.com/argoproj/argo-events/pull/2951
- Issues responded to
  - https://github.com/argoproj/argo-workflows/issues/12324
  - https://github.com/argoproj/argo-workflows/issues/12388
  - https://github.com/argoproj/argo-workflows/issues/12489
- Projects I am involved with
  - https://github.com/argoproj/argo-workflows
  - https://github.com/argoproj/argo-events

**Comment by terrytangyuan** [comment]
+1

**Comment by Joibel** [comment]
+1

**Comment by agilgur5** [comment]
> * [ ] I have spoken to my sponsors ahead of this application, and they have agreed to sponsor my application

> * @agilgur5

Sorry, I never said I'd be a sponsor and did not agree per the checkbox.
In https://github.com/argoproj/argo-workflows/pull/12359#discussion_r1429456159 I just mentioned that Membership is required so we'd need to change the language in order to include you.

It doesn't seem like I've reviewed any of your PRs currently, so I wouldn't be comfortable sponsoring at this time. (You have enough support in any case).

**Comment by terrytangyuan** [comment]
@shuangkun Please update the list of sponsors in the issue description.

**Comment by shuangkun** [comment]
> > * [ ]  I have spoken to my sponsors ahead of this application, and they have agreed to sponsor my application
> 
> > * @agilgur5
> 
> Sorry, I never said I'd be a sponsor and did not agree to sponsor per the checkbox. In [argoproj/argo-workflows#12359 (comment)](https://github.com/argoproj/argo-workflows/pull/12359#discussion_r1429456159) I just mentioned that Membership is required so we'd need to change the language in order to include you.
> 
> It doesn't seem like I've reviewed any of your PRs currently, so I wouldn't be comfortable sponsoring, at least not at this time. (You have enough support in any case).

ok, thanks.

**Comment by shuangkun** [comment]
> @shuangkun Please update the list of sponsors in the issue description.

ok, I have.

**Comment by agilgur5** [comment]
> It doesn't seem like I've reviewed any of your PRs currently, so I wouldn't be comfortable sponsoring, at least not at this time.

+1, I've now reviewed and looked through a handful of @shuangkun's PRs and he has made several fixes to various parts of the codebase and was the first to catch a few recent regressions as well
