### ISSUE TITLE
REQUEST: New membership for @Garett-MacGowan

### ISSUE THREAD

**Issue by Garett-MacGowan** [argoproj/argoproj#269]
### GitHub Username

@Garett-MacGowan

### Requirements
- [X] I have reviewed [the community membership guidelines](https://github.com/argoproj/argoproj/blob/master/community/membership.md)
- [X] I have [enabled 2FA on my GitHub account](https://github.com/settings/security)
- [X] I am actively contributing to 1 or more Argoproj subprojects
- [X] I have two sponsors that meet the sponsor requirements listed in the community membership guidelines
- [X] I have spoken to my sponsors ahead of this application, and they have agreed to sponsor my application

### Sponsors
- @agilgur5 
- @juliev0

### List of contributions to the Argoproj project
- PRs reviewed / authored
  - https://github.com/argoproj/argo-workflows/pull/12397
  - https://github.com/argoproj/argo-workflows/pull/12454
  - https://github.com/argoproj/argo-workflows/pull/12402
  - https://github.com/argoproj/argo-workflows/pull/11947
  - https://github.com/argoproj/argo-workflows/pull/12559
  - https://github.com/argoproj/argo-workflows/pull/12595
  - [See full list...](https://github.com/argoproj/argo-workflows/pulls?q=involves%3AGarett-MacGowan+is%3Apr)
 
- Issues responded to
  - https://github.com/argoproj/argo-workflows/issues/12331
  - [See full list...](https://github.com/argoproj/argo-workflows/issues?q=involves%3AGarett-MacGowan+is%3Aissue)
- Projects I am involved with
  - https://github.com/argoproj/argo-workflows

**Comment by terrytangyuan** [comment]
+1

**Comment by agilgur5** [comment]
+1 I suggested membership in https://github.com/argoproj/argo-workflows/pull/12397#issuecomment-1881932684 as Garett has had some A+ high quality PRs, found and fixed a bunch of bugs with artifacts, and has been really diligent in code review follow-ups. Would be an excellent addition 🙂

**Comment by juliev0** [comment]
+1 Garret has really deep dived into some core areas of the code and fixed some important issues.

**Comment by Garett-MacGowan** [comment]
@terrytangyuan Who is responsible for managing memberships?

**Comment by terrytangyuan** [comment]
We’ll review the request in membership meeting.

**Comment by Garett-MacGowan** [comment]
> We’ll review all requests in membership meeting.

I see, thanks!

**Comment by agilgur5** [comment]
> We’ll review all requests in membership meeting.

For clarity, the membership meeting is currently once a quarter in the [Argoproj calendar](https://calendar.google.com/calendar/u/0/embed?src=argoproj@gmail.com) with the next one at the beginning of February
