### ISSUE TITLE
REQUEST: New membership for @alexymantha

### ISSUE THREAD

**Issue by alexymantha** [argoproj/argoproj#271]
### GitHub Username

@alexymantha

### Requirements
- [x] I have reviewed [the community membership guidelines](https://github.com/argoproj/argoproj/blob/master/community/membership.md)
- [x] I have [enabled 2FA on my GitHub account](https://github.com/settings/security)
- [x] I am actively contributing to 1 or more Argoproj subprojects
- [ ] I have two sponsors that meet the sponsor requirements listed in the community membership guidelines
- [x] I have spoken to my sponsors ahead of this application, and they have agreed to sponsor my application

### Sponsors
- @agaudreault-jive 
- TBD

### List of contributions to the Argoproj project
- [PRs reviewed / authored](https://github.com/argoproj/argo-cd/pulls?q=is%3Apr+sort%3Aupdated-desc+author%3Aalexymantha)
- [Issues responded to](https://github.com/argoproj/argo-cd/issues?q=involves%3Aalexymantha+sort%3Aupdated-desc+)
- Projects I am involved with
	- [argoproj/argo-cd](https://github.com/argoproj/argo-cd)

**Comment by agaudreault-jive** [comment]
Alexy has been working on ArgoCD features related to monorepos performance, ApplicationSet progressive sync and UI integrations. He has created enhancement proposals and discussed them in ArgoCD community meetings. He is collaborating with different members of the ArgoCD project to deliver these features. The quality of his code when he opens pull requests is quite good and he has been continuously responsive to comments/reviews.

I think having @alexymantha as a member would be a great addition to the Argo community.
