### ISSUE TITLE
REQUEST: New membership for eduardodbr

### ISSUE THREAD

**Issue by eduardodbr** [argoproj/argoproj#272]
### GitHub Username

@eduardodbr

### Requirements
- [x] I have reviewed [the community membership guidelines](https://github.com/argoproj/argoproj/blob/master/community/membership.md)
- [x] I have [enabled 2FA on my GitHub account](https://github.com/settings/security)
- [x] I am actively contributing to 1 or more Argoproj subprojects
- [x] I have two sponsors that meet the sponsor requirements listed in the community membership guidelines
- [x] I have spoken to my sponsors ahead of this application, and they have agreed to sponsor my application

### Sponsors
- @caelan-io 
- @Joibel 

### List of contributions to the Argoproj project
- PRs reviewed / authored
Argo Events:
https://github.com/argoproj/argo-events/pull/2627
https://github.com/argoproj/argo-events/pull/2591
https://github.com/argoproj/argo-events/pull/2590
https://github.com/argoproj/argo-events/pull/2589
https://github.com/argoproj/argo-events/pull/2996
Argo Workflows:
https://github.com/argoproj/argo-workflows/pull/10774
https://github.com/argoproj/argo-workflows/pull/11559
https://github.com/argoproj/argo-workflows/pull/12305

- Issues responded to
- Projects I am involved with
Argo Workflows

**Comment by terrytangyuan** [comment]
+1

**Comment by caelan-io** [comment]
Thanks for your recent contributions!
