### ISSUE TITLE
REQUEST: Promotion to Approver for Joibel

### ISSUE THREAD

**Issue by Joibel** [argoproj/argoproj#276]
### GitHub Username

@Joibel

### Sub-project(s)

Promotion is requested for the following sub-project(s). 

- [ ] Argo CD
- [ ] Argo Events
- [ ] Argo Rollouts
- [x] Argo Workflows

### Requirements

- [x] Reviewer for at least 3 months (as of the membership meeting date)
- [x] Reviewer for or author of at least 10 substantial PRs to the codebase
   - [Completed workflow tracking](https://github.com/argoproj/argo-workflows/pull/12198) which was a lot of pain to track down where workflow could run onExit despite having completed already.
   - Improving test coverage and suite: [test](https://github.com/argoproj/argo-workflows/pull/12216) [test](https://github.com/argoproj/argo-workflows/pull/12215) and [test](https://github.com/argoproj/argo-workflows/pull/12214) improvements for regression testing
   - A review [preventing](https://github.com/argoproj/argo-workflows/pull/12595#issuecomment-1918887327) a possibly misleading approach to retries in conflict
   - A review [which helped steer](https://github.com/argoproj/argo-workflows/pull/12574#issuecomment-1914255041) a fix into a long term solution for regressions in 3.5.3
   - Tackling use of [withItems with hooks](https://github.com/argoproj/argo-workflows/pull/12281) including regression test.
   - Investigation into [regression with reapplying workflow](https://github.com/argoproj/argo-workflows/issues/12601), including resolution.
   - Review of [memoization under retry](https://github.com/argoproj/argo-workflows/pull/12491) including local testing and catching regressions.
   - Helping eduardobr (#272) as reviewer of [stop strategy for CronWorkflows](https://github.com/argoproj/argo-workflows/pull/12305)
   - Helping shuankun (#266) get onboard as one of his earlier reviewers for [deleting pending pods on workflow termination](https://github.com/argoproj/argo-workflows/pull/12196)
  - Took devcontainer development forward so that it was generally usable, and have reviewed several further improvements to this 
    - https://github.com/argoproj/argo-workflows/pull/11104
    - https://github.com/argoproj/argo-workflows/pull/11115
    - As reviewer https://github.com/argoproj/argo-workflows/pull/11350
    - https://github.com/argoproj/argo-workflows/pull/11153
    - https://github.com/argoproj/argo-workflows/pull/11162
    - As reviewer https://github.com/argoproj/argo-workflows/pull/11981
  - Improved memoization so that it works in more cases, and based on popularity of the idea, changed it to allow 'no output' memoization.
    - https://github.com/argoproj/argo-workflows/pull/11225
    - https://github.com/argoproj/argo-workflows/pull/11257
    - https://github.com/argoproj/argo-workflows/pull/11379
    - https://github.com/argoproj/argo-workflows/pull/12119
  - Made retryPolicy saner so that it behaves more like people would expect. Included diagramming in the documentation. https://github.com/argoproj/argo-workflows/pull/11005
  - Improved how hook expressions are handled https://github.com/argoproj/argo-workflows/pull/10919
  - https://github.com/argoproj/argo-workflows/pull/11151
  - Allowed hooks to be added globally in workflowDefaults https://github.com/argoproj/argo-workflows/pull/11214 and then fixed it in https://github.com/argoproj/argo-workflows/pull/11693

Other reviews where I've contributed to changes across the controller codebase:
  - https://github.com/argoproj/argo-workflows/pull/11736
  - https://github.com/argoproj/argo-workflows/pull/11760
  - https://github.com/argoproj/argo-workflows/pull/11456
  - https://github.com/argoproj/argo-workflows/pull/11350
  - https://github.com/argoproj/argo-workflows/pull/10777

Author of [35](https://github.com/argoproj/argo-workflows/pulls?q=is%3Apr+author%3AJoibel+is%3Aclosed) merged PRs, 11 since becoming a reviewer.

**Other notes**

I've been trying to build the community around workflows up in line with @juliev0 sustainability efforts, so my time has been spent more in slack and issues than PRs recently. I've helped with getting new people interested in membership of argoproj.

In the last [3 months](https://argo.devstats.cncf.io/d/48/users-statistics-by-repository-group?orgId=1&var-period=w&var-metric=contributions&var-repogroup_name=argoproj%2Fargo-workflows&var-users=All&from=now-3M&to=now) since becoming a reviewer I've been 4th most active in the github project.

![image](https://github.com/argoproj/argoproj/assets/1827156/38650986-48e6-47ef-acbd-c4af58225c44)

I am very active in #argo-workflows (and quite active in #argo-cd) slack channels.

### Lead Sponsor(s)

Promotion to Approver requires sponsorship from at least one sub-project Lead.

- @terrytangyuan 

### Other Sponsors

- @juliev0

**Comment by Garett-MacGowan** [comment]
+1

**Comment by juliev0** [comment]
+1 Alan shows strong technical judgment and has experience in many areas of the Controller, not to mention the DevContainer development effort. His PR reviews provide actionable feedback to contributors, and he has multiple reviews recently commenting on the overall approach taken by the contributor, which shows good overall knowledge of the Controller.

**Comment by juliev0** [comment]
Hey @Joibel. Everyone agreed that you've got strong technical judgment and thinks you've been doing a good job on PR reviews. Keep all of that up. Just keep adding more code-related PRs (non-trivial of course) and you'll get there.

**Comment by agilgur5** [comment]
+1 Alan has very detailed and thoughtful issue and PR feedback, often helping steer contributors to a better approach, improving tech debt in the codebase, and focusing on the root cause. He has corrected Julie and I before in reviews as well.

We need more folks that are diligent and thorough in their reviews, ensuring a high quality of code, and Alan certainly matches that description.

> so my time has been spent more in slack and issues than PRs recently.

Given that I spend the most time on these, I can say that Alan has been quite helpful in this area in particular.

**Comment by terrytangyuan** [comment]
+1
