### ISSUE TITLE
REQUEST: Promotion to Approver for @agilgur5

### ISSUE THREAD

**Issue by agilgur5** [argoproj/argoproj#277]
Follow-up to #242
Sorry that I filed this the night before the membership meeting, I've been, er, a bit preoccupied in passing a kidney stone the past week and all the pre-, side-, and after-effects of that and the (hard) medications 🫠
Also sorry if it's not as organized as my previous ones, because boy did those medications hit my brain like a truck :face_with_spiral_eyes: 

### GitHub Username

@agilgur5

### Sub-project(s)

Promotion is requested for the following sub-project(s). 

- [ ] Argo CD
- [ ] Argo Events
- [ ] Argo Rollouts
- [x] Argo Workflows

#### Other repos

- [x] `argo-ui`

Also `argo-site` and `pkg` could be useful, but I have significantly more contributions to `argo-ui` than either of those.

### Requirements

- [x] Reviewer for at least 3 months (as of the membership meeting date)
- [x] Reviewer for or author of at least 10 substantial PRs to the codebase

In my Reviewer promotion request in #242, I already had substantially more than the requirements for Approver, so here I'll just list some more from the past ~3 months of being a Reviewer. My Reviewer promotion also had a ton of support and praise.

#### Selected Code Reviews

Noting here that Julie wrote in my Reviewer promotion request that I may well be the [most thorough code reviewer on Workflows](https://github.com/argoproj/argoproj/issues/242#issuecomment-1754310090) 🙂 ❤️ 

- Many detailed reviews over several iterations and various improvements to the Workflows Sustainability Effort (led by Julie): https://github.com/argoproj/argo-workflows/pull/12249#pullrequestreview-1745578994 plus some iteration below that, https://github.com/argoproj/argo-workflows/pull/12359#pullrequestreview-1785741940 and several more iterative reviews below that, and https://github.com/argoproj/argo-workflows/pull/12547#discussion_r1458367075
- Several detailed reviews over several iterations as well on the versioned docs site (led by JM), where I caught a handful of issues: https://github.com/argoproj/argo-workflows/pull/12360#pullrequestreview-1791633160 plus a few more iterative reviews below that, https://github.com/argoproj/argo-workflows/pull/12362#pullrequestreview-1791676456, and also steered the redirect approach in a more accurate direction in early work in https://github.com/argoproj/argo-workflows/pull/12212#issuecomment-1814635375
   - Also personally followed up on this in https://github.com/argoproj/argo-workflows/pull/12443#discussion_r1451024296, https://github.com/argoproj/argo-workflows/pull/12500, https://github.com/argoproj/argo-workflows/issues/12453, https://github.com/argoproj/argo-workflows/pull/12465, etc (there were a few more build simplifications and smaller follow-ups afterward)
- Caught & personally fixed several impactful missed issues in the title & description markdown feature before it was released: https://github.com/argoproj/argo-workflows/pull/10553#pullrequestreview-1799370952, https://github.com/argoproj/argo-workflows/pull/12580, https://github.com/argoproj/argo-workflows/pull/12582
   - The last one also adds docs for the non-markdown variant of the feature, which was previously undocumented
- More large changes during docs reviews: https://github.com/argoproj/argo-workflows/pull/12597#pullrequestreview-1854819292

- Handed off remaining work in the UI functional refactor in https://github.com/argoproj/argo-workflows/issues/9810 to contributors and had several detailed reviews of their PRs: https://github.com/argoproj/argo-workflows/pull/11803#pullrequestreview-1622980332, https://github.com/argoproj/argo-workflows/pull/11899#pullrequestreview-1649892976, https://github.com/argoproj/argo-workflows/pull/11894#pullrequestreview-1649877948, https://github.com/argoproj/argo-workflows/pull/11901#pullrequestreview-1651606072 (plus a few iterations below that), https://github.com/argoproj/argo-workflows/pull/11920#discussion_r1357735906, https://github.com/argoproj/argo-workflows/pull/12046#pullrequestreview-1698274176

- CI improvements in a few reviews: https://github.com/argoproj/argo-workflows/pull/12064#issuecomment-1776284369, https://github.com/argoproj/argo-workflows/pull/12234#pullrequestreview-1740685561, https://github.com/argoproj/argo-workflows/pull/12413#discussion_r1468094644, 
- Script improvements in a few reviews: https://github.com/argoproj/argo-workflows/pull/12040#pullrequestreview-1689065435, https://github.com/argoproj/argo-workflows/pull/12520#pullrequestreview-1854934639
- Test improvements in some reviews: https://github.com/argoproj/argo-workflows/pull/12011#pullrequestreview-1685827398, https://github.com/argoproj/argo-workflows/pull/12071#pullrequestreview-1695469785
- Found some Server performance regressions while reviewing older code in the Server while investigating https://github.com/argoproj/argo-workflows/issues/12025#issuecomment-1914065370: https://github.com/argoproj/argo-workflows/pull/11121#discussion_r1469101802, https://github.com/argoproj/argo-workflows/pull/11684#discussion_r1469090044 
  - Plus some other Server reviews: https://github.com/argoproj/argo-workflows/pull/12199#pullrequestreview-1785686879 (and had a previous review on an iteration above that)
- During review, discovered that the Controller / Server separation of duties was broken by the `retry` method: https://github.com/argoproj/argo-workflows/pull/12105#discussion_r1376399199, https://github.com/argoproj/argo-workflows/pull/12419#issuecomment-1896552339, https://github.com/argoproj/argo-workflows/issues/12538, etc
     
#### Selected PRs

- Leading the effort to code-split giant deps in the UI to improve load times per https://github.com/argoproj/argo-workflows/issues/12059: https://github.com/argoproj/argo-workflows/pull/12061, https://github.com/argoproj/argo-workflows/pull/12150, https://github.com/argoproj/argo-workflows/pull/12158, https://github.com/argoproj/argo-workflows/pull/12580
  - Plus entirely remove some giant, deprecated deps and replace with native code: https://github.com/argoproj/argo-workflows/pull/12097, https://github.com/argoproj/argo-workflows/pull/12611
- Finally migrated several deprecated UI deps to new, supported ones: https://github.com/argoproj/argo-workflows/pull/12163, https://github.com/argoproj/argo-workflows/pull/12290, https://github.com/argoproj/argo-workflows/pull/12540
  - Plus some other sizeable UI build & deps improvements:  https://github.com/argoproj/argo-workflows/pull/12480, https://github.com/argoproj/argo-workflows/pull/12516
  - Plus `argo-ui` dep fixes & improvements too: https://github.com/argoproj/argo-ui/pull/509, https://github.com/argoproj/argo-ui/pull/510, https://github.com/argoproj/argo-ui/pull/511, etc
  - Some of these were _months_ in the making, requiring lots of pre-work and sequenced PRs to update the code to be compatible with the new deps and then update the deps to be compatible with each other etc. I continued to make improvements in sequence over a longer period of time as they were possible
- One-liner UI bugfix, but complicated root cause analysis: https://github.com/argoproj/argo-workflows/issues/12327#issuecomment-1903263812

- Docs build improvements: https://github.com/argoproj/argo-workflows/pull/12463, https://github.com/argoproj/argo-workflows/pull/12464, https://github.com/argoproj/argo-workflows/pull/12466, https://github.com/argoproj/argo-workflows/pull/12501, https://github.com/argoproj/argo-workflows/pull/12518, https://github.com/argoproj/argo-workflows/pull/12522, https://github.com/argoproj/argo-workflows/pull/12521
- More substantial docs rewrites: https://github.com/argoproj/argo-workflows/pull/12148, https://github.com/argoproj/argo-workflows/pull/12560, https://github.com/argoproj/argo-workflows/pull/12582

- More QoL and maintenance improvements: https://github.com/argoproj/argo-workflows/pull/12487, https://github.com/argoproj/argo-workflows/pull/12488, https://github.com/argoproj/argo-workflows/pull/12583.

- Server logging fixes / improvements: https://github.com/argoproj/argo-workflows/pull/11978, https://github.com/argoproj/argo-workflows/pull/12145
- Detailed Controller root cause analyses & fixes:
  - very detailed follow-up in https://github.com/argoproj/argo-workflows/issues/12165 that was initially suspected to be a UI issue but was actually a Controller issue -- detailed root cause analysis of ~6 year old code in https://github.com/argoproj/argo-workflows/issues/12165#issuecomment-1807244326
    - I wasn't feeling well, so Alan then followed up with the simple fix plus tests in https://github.com/argoproj/argo-workflows/pull/12203 etc
    - **EDIT**: PR for the root cause fix: https://github.com/argoproj/argo-workflows/pull/12614
  - discovered a regression in Executor customization in a root cause analysis of ~2 year old code in: https://github.com/argoproj/argo-workflows/issues/12315#issuecomment-1913359846
    - **EDIT**: PR to fix this: https://github.com/argoproj/argo-workflows/pull/12609
  - discovered an `expr` regression as the root cause of: https://github.com/argoproj/argo-workflows/issues/12037
    - Isitha then beat me to the chase in following up on and fixing
  - root caused an issue that was supposedly solved in supporting Azure DevOps artifacts: https://github.com/argoproj/argo-workflows/issues/11705#issuecomment-1793778023
    - this got a PR just yesterday from a first-time contributor following my suggested solution: https://github.com/argoproj/argo-workflows/pull/12598

I'm also currently juggling like 20+ open PRs as well and still have some branches WIP as well; it's a lot to keep organized 😅 

#### New Total
- [135+ PRs](https://github.com/argoproj/argo-workflows/pulls?q=author%3Aagilgur5) opened
- [340+](https://github.com/argoproj/argo-workflows/pulls?q=is%3Apr+commenter%3Aagilgur5+-author%3Aagilgur5) PRs responded to and/or reviewed
- See issues, discussions, etc stats below in "Other"

#### Familiarity
- Largely same as before, but now I know the Controller and the E2E test suites a bit better as I've had a few more reviews and contributions there
  - I have been intentionally spending some more time doing bugfixes in those to increase my familiarity, but it's vast enough that I would not yet call myself an expert in those and will still rely on others to double-check my reviews in places that I'm unfamiliar and not confident in my review (in general, I do not approve PRs that I do not feel confident in my understanding of).
   - Currently, I believe I am the top expert on the Docs, UI, and all build systems, and potentially parts of the Server and CLI as well (and maybe some of the informers in the Controller as well).

#### Other contributions and stats
- Main changes to CNCF DevStats for Argo Workflows is that I am now top 3 contributors in the [past 2 years](https://argo.devstats.cncf.io/d/48/users-statistics-by-repository-group?orgId=1&var-period=w&var-metric=contributions&var-repogroup_name=argoproj%2Fargo-workflows&var-users=All&from=now-2y&to=now) and top 1 in the [past 6 months](https://argo.devstats.cncf.io/d/48/users-statistics-by-repository-group?orgId=1&var-period=w&var-metric=contributions&var-repogroup_name=argoproj%2Fargo-workflows&var-users=All&from=now-6M&to=now) - [3 months](https://argo.devstats.cncf.io/d/48/users-statistics-by-repository-group?orgId=1&var-period=w&var-metric=contributions&var-repogroup_name=argoproj%2Fargo-workflows&var-users=All&from=now-90d&to=now) - [1 month](https://argo.devstats.cncf.io/d/48/users-statistics-by-repository-group?orgId=1&var-period=w&var-metric=contributions&var-repogroup_name=argoproj%2Fargo-workflows&var-users=All&from=now-30d&to=now)
  - Here's updated screenshots at 2 years and at 6 months (I am in pale yellow):
  ![Screenshot 2024-01-31 at 10 37 10 PM](https://github.com/argoproj/argoproj/assets/4970083/a4798b59-789c-412a-8a66-f79b0e8e0f5b)
  ![Screenshot 2024-01-31 at 10 37 43 PM](https://github.com/argoproj/argoproj/assets/4970083/3f290959-d8f1-4913-9ff4-d043a510dd9c)
  - Similar to before, for the 2 year range I have achieved that despite only actively contributing the past ~6 months, i.e. in a much smaller time period than the width of the range, the entirety of which the average is taken from.
  
- Responded to hundreds of users over issues ([300+](https://github.com/argoproj/argo-workflows/issues?q=is%3Aissue+commenter%3Aagilgur5)), discussions ([100+](https://github.com/argoproj/argo-workflows/discussions?discussions_q=commenter%3Aagilgur5+) + many sub-discussions in giscus), and Slack
  - Still very active in all our Slack channels, particularly in user support in [#argo-workflows](https://cloud-native.slack.com/archives/C01QW9QSSSK), where I probably have several hundred responses if I could do a `COUNT` on it.
    - When I had some family and personal medical emergencies to attend to (for weeks; lot of hospitalizations in the fam recently 😞), I could not contribute as much code or reviews (see the dip in the graph above), but I was still quite active in those channels that don't require the same large blocks of focus time as coding or reviewing code

- Encouraged more contributors to request membership, see #269 in this repo 🙌 🙂 
- Continued to handle Bug Triage on my own whenever I check on the issues and still handle the vast majority of issue triage
  - Alan has started helping too recently
- Admin of the [FOSSA license scan](https://app.fossa.com/projects/git%2Bgithub.com%2Fargoproj%2Fargo-workflows?ref=badge_shield) where I set things up and diligently checked & [documented all false positives](https://github.com/argoproj/argo-workflows/pull/12023#issuecomment-1891111404) etc
    - Also fixed one dep licensing issue: https://github.com/argoproj/argo-workflows/pull/12033
- Admin of the [new ReadTheDocs site](https://argo-workflows.readthedocs.com)

### Lead Sponsor(s)

Promotion to Approver requires sponsorship from at least one sub-project Lead.

- @terrytangyuan
- @sarabala1979 

### Other Sponsors

- @juliev0 
- @isubasinghe 
- @Joibel 
- @jmeridth 
- @caelan-io 

Will add some more sponsors once this issue is filed

**Comment by Joibel** [comment]
+1 for Anton, he's doing amazing work on the project.

**Comment by isubasinghe** [comment]
+1 for Anton as well

**Comment by sarabala1979** [comment]
+1 for Anton.

**Comment by terrytangyuan** [comment]
+1

**Comment by Garett-MacGowan** [comment]
+1
