### ISSUE TITLE
REQUEST: New membership for csantanapr

### ISSUE THREAD

**Issue by csantanapr** [argoproj/argoproj#279]
### csantanapr

@csantanapr

### Requirements
- [x] I have reviewed [the community membership guidelines](https://github.com/argoproj/argoproj/blob/master/community/membership.md)
- [x] I have [enabled 2FA on my GitHub account](https://github.com/settings/security)
- [x] I am actively contributing to 1 or more Argoproj subprojects
- [x] I have two sponsors that meet the sponsor requirements listed in the community membership guidelines
- [x] I have spoken to my sponsors ahead of this application, and they have agreed to sponsor my application

### Sponsors
- @crenshaw-dev 
- @todaywasawesome 

### List of contributions to the Argoproj project
- PRs reviewed / authored
  - argo-cd https://github.com/argoproj/argo-cd/pull/17063
  - notifications-engine https://github.com/argoproj/notifications-engine/pull/259 
- Projects I am involved with:
  - **argocd**
    - member of [argo sig-scalability](https://github.com/argoproj/argoproj/blob/main/sigs/sig-scalability/README.md)
    - answer questions in argocd slack channels
    - created open source project [gitops-bridge](https://github.com/gitops-bridge-dev) provides patterns for using argocd 
    - co-chair and cfp reviewer for argocon
    - cfp reviewer for gitopscon  
   - **argo-events/workflows** 
     - shared examples on github  [gitops-hpc](https://github.com/csantanapr/gitops-hpc) ends users of argo leveraging

**Comment by todaywasawesome** [comment]
+1

**Comment by terrytangyuan** [comment]
+1

**Comment by agilgur5** [comment]
+1 Carlos is very involved in the community and a near constant presence in SIG Scalability as well.
Also appreciate the resources he took the time to find for me for some other examples of sharding in CNCF 🙂

**Comment by todaywasawesome** [comment]
Want to add that Carlos is serving as co-chair of ArgoCon and has been great at organizing contributions from the AWS team.
