### ISSUE TITLE
REQUEST: New membership for @terrytangyuan 

### ISSUE THREAD

**Issue by alexec** [argoproj/argoproj#28]
### GitHub Username

@terrytangyuan 

### Organization you are requesting membership in

argo-workflows only

### Requirements

- [ ] I have reviewed the community membership guidelines (https://github.com/argoproj/argoproj/blob/master/community/membership.md)
- [x] I have enabled 2FA on my GitHub account (https://github.com/settings/security)
- [x] I am actively contributing to 1 or more Argoproj subprojects
- [x] I have two sponsors that meet the sponsor requirements listed in the community membership guidelines
- [x] ~~I have spoken to my sponsors ahead of this application, and they have agreed to sponsor my application~~ N/A

### Sponsors

- @alexec 
- @simster7 

### List of contributions to the Argoproj project
- PRs reviewed / authored: 53 merged PRs: https://github.com/argoproj/argo-workflows/pulls?q=is%3Apr+author%3Aterrytangyuan+is%3Amerged
- Issues responded to: 8 issues: https://github.com/argoproj/argo-workflows/issues?q=is%3Aissue+terrytangyuan+
- Projects involved with: CoulerProj - the defacto Python SDK for Argo Workflows.

**Comment by alexec** [comment]
Terry is already a member.

**Comment by simster7** [comment]
Should this PR be made against the Argo Workflows repo? We need to edit OWNERS there

**Comment by alexec** [comment]
Just me doing the due diligence.

**Comment by terrytangyuan** [comment]
@simster7 @alexec Thank you for the **official** invitation!
