### ISSUE TITLE
REQUEST: "graduate" Hera from argoproj-labs to argoproj

### ISSUE THREAD

**Issue by flaviuvadan** [argoproj/argoproj#286]
# Hera

## Goal

Support the growth of the Hera project and the community!

## Summary

[Hera](https://github.com/argoproj-labs/hera) has been part of the Argo ecosystem for ~3 years now. The project has undergone a lot of development to achieve a point of feature parity with Argo Workflows. In addition, Hera provides users with numerous features to facilitate access to Argo Workflows via integrations with Pydantic. In addition, everything that can be expressed in Argo Workflows can be expressed in Hera! The project:
- has a great community
- has a mature and stable codebase
- has grown a lot in the last 3 years
- is used in production
  -  [incomplete users list](https://github.com/argoproj-labs/hera/blob/main/USERS.md)
- has 3 active maintainers
  - @samj1912
  - @elliotgunton
  - @flaviuvadan
- is approaching the 500 stars mark
- is vendor neutral, licensed under Apache 2.0
- ~1M downloads
  - https://www.pepy.tech/projects/hera

In addition, there are now companies who [hire SWEs to work on Hera exclusively](https://www.linkedin.com/feed/update/urn:li:activity:7140289239132311553?updateEntityUrn=urn%3Ali%3Afs_feedUpdate%3A%28V2%2Curn%3Ali%3Aactivity%3A7140289239132311553%29). Maintainers have the [vision of using Hera to bring to MLOps what FastAPI brought to web development](https://www.linkedin.com/posts/sambhav-kothari_hiringnow-opensourcedevelopment-softwarejobs-activity-7140289239132311553--Zlf?utm_source=share&utm_medium=member_desktop) :) That's all to say: the project has an amazing community and plans to keep growing!

## Next steps
A potential next step in the growth of Hera is to "graduate" it to argoproj. Concretely this means:
- move the repo from argoproj-labs to argoproj to make Hera an "official" Argo project
- establish a clear path for onboarding/offboarding Hera maintainers in accordance with Argo guidelines

## Asks

**Support the graduation of Hera from argoproj-labs to argoproj**!

### Support

To support this initiative please leave a comment on this issue expressing your support. Alternatively, please use 👍🏻  to showcase support or 👎🏻 to vote against this initiative. If you do not support this initiative please express any feedback you might have!

#### Sponsors

- @

**Comment by JPZ13** [comment]
Given how well Hera is maintained and how loved it is by users, I'd suggest graduating Hera and deprecating the Argo Workflows computer-generated Python SDK in favor of Hera

**Comment by terrytangyuan** [comment]
We will probably need to establish a formal "graduation" process for projects like Hera. There are a couple of other projects that are even more "popular" than Hera in argoproj-labs and may have similar requests at some point.

**Comment by terrytangyuan** [comment]
It will not be my personal call. Could you bring this up in the maintainers meeting? It's open to everyone. There's an upcoming meeting next week [https://docs.google.com/document/d/1C71GA0XCxsyGP7Q4SYveHak5ZZcJOuaOiDCt_xHG10U/edit#](https://www.google.com/url?q=https://docs.google.com/document/d/1C71GA0XCxsyGP7Q4SYveHak5ZZcJOuaOiDCt_xHG10U/edit&sa=D&source=calendar&usd=2&usg=AOvVaw2wv0kWSAvLIM6gCOWa2Ul6)

**Comment by flaviuvadan** [comment]
Thanks @terrytangyuan added to the March 13th meeting: https://docs.google.com/document/d/1C71GA0XCxsyGP7Q4SYveHak5ZZcJOuaOiDCt_xHG10U/edit#heading=h.y5xnyirokxg4

**Comment by hblixt** [comment]
Recommendation to get traction and close this
- Discuss with Argoproj leads and come up with an agreed on solution and plan, the more details the better. 
- Bring to maintainer meeting

Once we have a more detailed proposal, it will be easier to make some decisions and move forward.

**Comment by elliotgunton** [comment]
Hi folks, we (the Hera maintainers) would like to withdraw/close this issue as we've discussed broader plans for Hera for be a Python entrypoint to the Kubernetes ecosystem. This would mean Hera going beyond being the Python SDK for just Argo, so for now, we would prefer to hold off on moving Hera to the `argoproj` organisation, staying in `argoproj-labs` until we are clear on the direction we go. Thanks!

cc @sambhav

**Comment by terrytangyuan** [comment]
> we've discussed broader plans for Hera for be a Python entrypoint to the Kubernetes ecosystem. This would mean Hera going beyond being the Python SDK for just Argo

Could you elaborate on this?

Apologies for the delay but @sarabala1979 and I had a discussion on this earlier but couldn't get a chance to report back in the maintainers meeting. 

Here are some thoughts on how we could've proceeded without knowing your comment above:
1. Keep it in argoproj-labs since:
  a. No tangible benefits of moving to argoproj. If there's ask about visibility, we can do via #2.
  b. May need to re-brand to argoproj-python-sdk instead of Hera
2. Give more visibility of Hera in argo-workflows repo. Deprecate auto-generated Python SDK.

**Comment by elliotgunton** [comment]
Hey @terrytangyuan - we want to look into better Argo Events integration in Hera to begin with. And we also see potential to provide a Python framework for Kubernetes operators - https://github.com/nolar/kopf is in "maintenance mode" for now (and [used to have a funny warning](https://github.com/nolar/kopf/commit/642ebf4af95d6bd8865b0422d95dcf08213275b6) not to use it in its README).

On your other comments - we do want to increase visibility, but would not want to rebrand the project as it has started to bring its own Python-centric features on top of Argo Workflows, along with some "brand recognition" from ArgoCon talks, so it would be better to remain distinct as it offers more than just being an SDK for AW at this point.

Agreed on (2), and if we can help in any way let us know! If you're open to e.g. adding Python examples to the Argo Workflows docs, maybe a "Python" section of the "Getting Started" tab?

**Comment by terrytangyuan** [comment]
>we also see potential to provide a Python framework for Kubernetes operators - https://github.com/nolar/kopf 

I'd suggest that to be a separate project instead of diluting Hera's brand. We'd only want to increase visibility if the project is specific to Argo ecosystem (Argo Workflows + Argo Events are fine).

**Comment by elliotgunton** [comment]
Yes that would be a separate project (naming of that and an umbrella org TBD), Hera itself (i.e. the https://github.com/argoproj-labs/hera repo) will only be for Argo.

**Comment by terrytangyuan** [comment]
Sounds great. Happy to review any PRs to update the Argo Workflows docs related to Python SDKs.
