### ISSUE TITLE
REQUEST: New membership for OpenGuidou

### ISSUE THREAD

**Issue by OpenGuidou** [argoproj/argoproj#291]
### GitHub Username

@OpenGuidou

### Requirements
- [x] I have reviewed [the community membership guidelines](https://github.com/argoproj/argoproj/blob/master/community/membership.md)
- [x] I have [enabled 2FA on my GitHub account](https://github.com/settings/security)
- [x] I am actively contributing to 1 or more Argoproj subprojects
- [x] I have two sponsors that meet the sponsor requirements listed in the community membership guidelines
- [x] I have spoken to my sponsors ahead of this application, and they have agreed to sponsor my application
- [x] I understand that I can [make my membership public](https://docs.github.com/en/account-and-profile/setting-up-and-managing-your-personal-account-on-github/managing-your-membership-in-organizations/publicizing-or-hiding-organization-membership) if I'd like to once I am invited to the organization

### Sponsors
- @zachaller 
- @crenshaw-dev 

### List of contributions to the Argoproj project
- PRs reviewed / authored:
https://github.com/argoproj/argo-rollouts/pull/3353
https://github.com/argoproj/argo-rollouts/pull/3213
https://github.com/argoproj/argo-rollouts/pull/3038
https://github.com/argoproj/argo-rollouts/pull/2914
- Issues responded to
- Projects I am involved with: Argo CD, Argo Rollouts

**Comment by crenshaw-dev** [comment]
+1
