### ISSUE TITLE
REQUEST: Promotion to Reviewer for @shuangkun

### ISSUE THREAD

**Issue by shuangkun** [argoproj/argoproj#293]
### GitHub Username

@shuangkun 

### Sub-project(s)

Promotion is requested for the following sub-project(s).

- [ ] Argo CD
- [ ] Argo Events
- [ ] Argo Rollouts
- [x] Argo Workflows

### Requirements

- [x] Member for at least 3 months (as of the membership meeting date)
- [x] Reviewer for or author of at least 5 substantial PRs to the codebase
Authored：
    - < offload the envtemplate to support long arguments> https://github.com/argoproj/argo-workflows/pull/12325
    - < parallel resolve reference to speed up execution of large workflow > https://github.com/argoproj/argo-workflows/pull/12328
    - < update command for cron/wft/cwft > https://github.com/argoproj/argo-workflows/pull/12803
    - < move delete logic from server to controller > https://github.com/argoproj/argo-workflows/pull/12734
    - < enable scheduling constraints in step/dag level > https://github.com/argoproj/argo-workflows/pull/12700
    -  < enable dynamic template reference naming > https://github.com/argoproj/argo-workflows/pull/12842
    - < raise and resolve issues in large workflow > 
              https://github.com/argoproj/argo-workflows/pull/12574
              https://github.com/argoproj/argo-workflows/pull/12537
              https://github.com/argoproj/argo-workflows/pull/11048
    - < locate the causes of some very important stuck issues about workflow/containerset/terminating >
               https://github.com/argoproj/argo-workflows/pull/12196
               https://github.com/argoproj/argo-workflows/pull/12761
               https://github.com/argoproj/argo-workflows/pull/12756
     - < fixed some issues with core workflow logict about retryStrategy/memoize/hook/loop/dag/containerOn/artifacts/http/exector/data/resouce/server/controller>
                https://github.com/argoproj/argo-workflows/pull/12491
                https://github.com/argoproj/argo-workflows/pull/12683
                https://github.com/argoproj/argo-workflows/pull/12815
 	        https://github.com/argoproj/argo-workflows/pull/12701
                https://github.com/argoproj/argo-workflows/pull/12817
                https://github.com/argoproj/argo-workflows/pull/12835
                https://github.com/argoproj/argo-workflows/pull/12831
                https://github.com/argoproj/argo-workflows/pull/12825
                https://github.com/argoproj/argo-workflows/pull/12780
                https://github.com/argoproj/argo-workflows/pull/12575
                https://github.com/argoproj/argo-workflows/pull/12544
                https://github.com/argoproj/argo-workflows/pull/12419
                https://github.com/argoproj/argo-workflows/pull/12197
                https://github.com/argoproj/argo-workflows/pull/12084

[Totol Authored 52](https://github.com/argoproj/argo-workflows/pulls/shuangkun) / [44 Merged](https://github.com/argoproj/argo-workflows/pulls?q=is%3Apr+author%3Ashuangkun+is%3Aclosed) 

[Reviewed](https://github.com/argoproj/argo-workflows/pulls?page=1&q=is%3Apr+is%3Aclosed+commenter%3Ashuangkun)

[Issues](https://github.com/argoproj/argo-workflows/issues/assigned/shuangkun)

Other Notes:

 I am the fourth in the past [6months](https://argo.devstats.cncf.io/d/48/users-statistics-by-repository-group?orgId=1&var-period=w&var-metric=contributions&var-repogroup_name=argoproj%2Fargo-workflows&var-users=All&from=now-6M&to=now) on the CNCF DevStats for Argo Workflows.
![image](https://github.com/argoproj/argoproj/assets/72060326/20678c5d-c17a-442f-b5e8-ce3e57dc3e25)
I have over three years of experience using and troubleshooting Argo Workflows issues on my team. My team also participated in the Argo workflow community contribution very early and member has participated in maintaining it before. Hoping to make more contributions in the future.

### Lead Sponsor(s)

Promotion to Reviewer requires sponsorship from at least one sub-project Lead.

- @ terrytangyuan 

### Other Sponsors

- @ tczhao 
- @ juliev0

**Comment by tczhao** [comment]
+1
sounds good to me
just keep in mind the responsibility as a reviewer
https://github.com/argoproj/argoproj/blob/main/community/membership.md#responsibilities-and-privileges-1

**Comment by terrytangyuan** [comment]
+1

**Comment by juliev0** [comment]
+1 no doubt - Shuangkun has tackled a significant number of high priority core bugs in the last few months at a serious velocity.

**Comment by sarabala1979** [comment]
+1.Thanks Shuangkun for your contribution

**Comment by agilgur5** [comment]
+1 Shuangkun has contributed quite a bit and is generally very responsive. He also tests well and has added many test cases (as well as fixed some flakes).
