### ISSUE TITLE
REQUEST: New membership for jiachengxu

### ISSUE THREAD

**Issue by jiachengxu** [argoproj/argoproj#294]
### GitHub Username

@jiachengxu

### Requirements
- [x] I have reviewed [the community membership guidelines](https://github.com/argoproj/argoproj/blob/master/community/membership.md)
- [x] I have [enabled 2FA on my GitHub account](https://github.com/settings/security)
- [x] I am actively contributing to 1 or more Argoproj subprojects
- [x] I have two sponsors that meet the sponsor requirements listed in the community membership guidelines
- [x] I have spoken to my sponsors ahead of this application, and they have agreed to sponsor my application
- [x] I understand that I can [make my membership public](https://docs.github.com/en/account-and-profile/setting-up-and-managing-your-personal-account-on-github/managing-your-membership-in-organizations/publicizing-or-hiding-organization-membership) if I'd like to once I am invited to the organization

### Sponsors
- @agilgur5 
- @jessesuen 
- @terrytangyuan 

### List of contributions to the Argoproj project
- PRs reviewed / authored
- argo-workflows:
  - https://github.com/argoproj/argo-workflows/pull/12912
  - https://github.com/argoproj/argo-workflows/pull/12736
  - https://github.com/argoproj/argo-workflows/pull/10693
  - https://github.com/argoproj/argo-workflows/pull/10677
  - https://github.com/argoproj/argo-workflows/pull/10489
  - https://github.com/argoproj/argo-workflows/pull/10449
  - https://github.com/argoproj/argo-workflows/pull/10424
  - https://github.com/argoproj/argo-workflows/pull/10346  
- argo-cd:
  - https://github.com/argoproj/argo-cd/pull/13360
- argo-rollouts:
  - https://github.com/argoproj/argo-rollouts/pull/2557
- Issues responded to
- Projects I am involved with

**Comment by jessesuen** [comment]
+1 from me as well

**Comment by agilgur5** [comment]
+1 @jiachengxu has been very diligent and detailed with his approach and follow-ups to https://github.com/argoproj/argo-workflows/pull/12736 et al
