### ISSUE TITLE
REQUEST: New membership for @jswxstw

### ISSUE THREAD

**Issue by jswxstw** [argoproj/argoproj#295]
### jswxstw

@jswxstw

### Requirements
- [x] I have reviewed [the community membership guidelines](https://github.com/argoproj/argoproj/blob/master/community/membership.md)
- [x] I have [enabled 2FA on my GitHub account](https://github.com/settings/security)
- [x] I am actively contributing to 1 or more Argoproj subprojects
- [x] I have two sponsors that meet the sponsor requirements listed in the community membership guidelines
- [x] I have spoken to my sponsors ahead of this application, and they have agreed to sponsor my application
- [x] I understand that I can [make my membership public](https://docs.github.com/en/account-and-profile/setting-up-and-managing-your-personal-account-on-github/managing-your-membership-in-organizations/publicizing-or-hiding-organization-membership) if I'd like to once I am invited to the organization

### Sponsors
- @agilgur5 
- @Joibel 

### List of contributions to the Argoproj project
- PRs reviewed / authored
  - https://github.com/argoproj/argo-workflows/pull/12440
  - https://github.com/argoproj/argo-workflows/pull/12620
  - [Other open PRs](https://github.com/argoproj/argo-workflows/pulls/jswxstw)
- Issues responded to
  - https://github.com/argoproj/argo-workflows/issues/12733
  - https://github.com/argoproj/argo-workflows/issues/12760
  - https://github.com/argoproj/argo-workflows/issues/12765
  - https://github.com/argoproj/argo-workflows/issues/12779
  - https://github.com/argoproj/argo-workflows/issues/12790
  - https://github.com/argoproj/argo-workflows/issues/12821
  - [Full list](https://github.com/argoproj/argo-workflows/issues?q=involves%3Ajswxstw+is%3Aissue)
- Projects I am involved with
  - [Argo Workflows](https://github.com/argoproj/argo-workflows)

**Comment by terrytangyuan** [comment]
+1

**Comment by shuangkun** [comment]
+1

**Comment by agilgur5** [comment]
+1 I suggested Membership in https://github.com/argoproj/argo-workflows/discussions/12840#discussioncomment-8912369 (which is also where Alan supported). @jswxstw has had some great root cause analyses and found and fixed various bugs 🙂
