### ISSUE TITLE
REQUEST: Promotion to Approver for @tczhao

### ISSUE THREAD

**Issue by tczhao** [argoproj/argoproj#296]
### GitHub Username

@tczhao 

### Sub-project(s)

Promotion is requested for the following sub-project(s). 

- [ ] Argo CD
- [ ] Argo Events
- [ ] Argo Rollouts
- [x] Argo Workflows

### Requirements

- [x] Reviewer for at least 3 months (as of the membership meeting date)
- [x] Reviewer for or author of at least 10 substantial PRs to the codebase
   - https://github.com/argoproj/argo-workflows/pull/12734
   - https://github.com/argoproj/argo-workflows/pull/12842
   - https://github.com/argoproj/argo-workflows/pull/12756
   - https://github.com/argoproj/argo-workflows/pull/12815
   - https://github.com/argoproj/argo-workflows/pull/12701
   - https://github.com/argoproj/argo-workflows/pull/12817
   - https://github.com/argoproj/argo-workflows/pull/12792
   - https://github.com/argoproj/argo-workflows/pull/12799
   - https://github.com/argoproj/argo-workflows/pull/8993
   - https://github.com/argoproj/argo-workflows/pull/9538
   - https://github.com/argoproj/argo-workflows/pull/8779

[~90 PRs](https://github.com/argoproj/argo-workflows/pulls?q=author%3Atczhao) opened
[~90 PRs](https://github.com/argoproj/argo-workflows/pulls?q=is%3Apr+commenter%3Atczhao+-author%3Atczhao+) responded to or reviewed
[3rd in activity from past 2 months](https://argo.devstats.cncf.io/d/48/users-statistics-by-repository-group?orgId=1&var-period=w&var-metric=contributions&var-repogroup_name=argoproj%2Fargo-workflows&var-users=All&from=now-2M&to=now)

Been contributing on and off since 2021, and have a reasonable sense of areas/practices to look out for in reviewing PRs

### Lead Sponsor(s)

Promotion to Approver requires sponsorship from at least one sub-project Lead.

- @terrytangyuan 

### Other Sponsors

- @juliev0
- @agilgur5 
- @shuangkun

**Comment by shuangkun** [comment]
+1 Very experienced reviewer, always gives effective suggestions.

**Comment by juliev0** [comment]
+1 Shows good knowledge of the code through reviewsOn May 1, 2024, at 4:04 PM, shuangkun tian ***@***.***> wrote:﻿
+1 Very experienced reviewer, always gives effective suggestions.

**Comment by terrytangyuan** [comment]
+1
