### ISSUE TITLE
REQUEST: New membership for Enclavet

### ISSUE THREAD

**Issue by Enclavet** [argoproj/argoproj#302]
### GitHub Username

@Enclavet

### Requirements
- [x] I have reviewed [the community membership guidelines](https://github.com/argoproj/argoproj/blob/master/community/membership.md)
- [x] I have [enabled 2FA on my GitHub account](https://github.com/settings/security)
- [x] I am actively contributing to 1 or more Argoproj subprojects
- [x] I have two sponsors that meet the sponsor requirements listed in the community membership guidelines
- [x] I have spoken to my sponsors ahead of this application, and they have agreed to sponsor my application
- [x] I understand that I can [make my membership public](https://docs.github.com/en/account-and-profile/setting-up-and-managing-your-personal-account-on-github/managing-your-membership-in-organizations/publicizing-or-hiding-organization-membership) if I'd like to once I am invited to the organization

### Sponsors
- @jannfis 
- @crenshaw-dev 

### List of contributions to the Argoproj project
- PRs reviewed / authored
  - [17014](https://github.com/argoproj/argo-cd/pull/17014) - authored
  - [16564 ](https://github.com/argoproj/argo-cd/pull/16564) - reviewed/authored
  - [17802 ](https://github.com/argoproj/argo-cd/pull/17802) - reviewed
- Issues responded to
  - [17257](https://github.com/argoproj/argo-cd/issues/17257)
  - [15237](https://github.com/argoproj/argo-cd/pull/15237)
- Projects I am involved with
  - [argo-cd](https://github.com/argoproj/argo-cd)
  - [argoproj-labs/argo-cd-benchmarking](https://github.com/argoproj-labs/argo-cd-benchmarking)
  - [cnoe.io](https://github.com/cnoe-io)
- Blogs
  - https://cnoe.io/blog/argo-workflow-scalability
  - https://cnoe.io/blog/argo-cd-application-scalability
  - https://aws.amazon.com/blogs/opensource/argo-cd-application-controller-scalability-testing-on-amazon-eks/

**Comment by agilgur5** [comment]
+1 Andrew has also ran or attended nearly every SIG Scalability meeting in the past year

**Comment by terrytangyuan** [comment]
+1
