### ISSUE TITLE
REQUEST: New membership for miltalex

### ISSUE THREAD

**Issue by miltalex** [argoproj/argoproj#307]
### GitHub Username

@miltalex

### Requirements
- [x] I have reviewed [the community membership guidelines](https://github.com/argoproj/argoproj/blob/master/community/membership.md)
- [x] I have [enabled 2FA on my GitHub account](https://github.com/settings/security)
- [x] I am actively contributing to 1 or more Argoproj subprojects
- [x] I have two sponsors that meet the sponsor requirements listed in the community membership guidelines
- [x] I have spoken to my sponsors ahead of this application, and they have agreed to sponsor my application
- [x] I understand that I can [make my membership public](https://docs.github.com/en/account-and-profile/setting-up-and-managing-your-personal-account-on-github/managing-your-membership-in-organizations/publicizing-or-hiding-organization-membership) if I'd like to once I am invited to the organization

### Sponsors
- @agilgur5 
- @Joibel 

### List of contributions to the Argoproj project
- PRs reviewed / authored
https://github.com/argoproj/argo-workflows/pull/13250
https://github.com/argoproj/argo-workflows/pull/13183
https://github.com/argoproj/argo-workflows/pull/13120
https://github.com/argoproj/argo-workflows/pull/13007
https://github.com/argoproj/argo-workflows/pull/13000
https://github.com/argoproj/argo-workflows/pull/12953
- Issues responded to
https://github.com/argoproj/argo-workflows/issues/12864
https://github.com/argoproj/argo-workflows/issues/13006
https://github.com/argoproj/argo-workflows/issues/12944
https://github.com/argoproj/argo-workflows/issues/13052
https://github.com/argoproj/argo-workflows/issues/12913
https://github.com/argoproj/argo-workflows/issues/10076
https://github.com/argoproj/argo-workflows/issues/12948
- Projects I am involved with
[argo-workflows](https://github.com/argoproj/argo-workflows)

**Comment by Joibel** [comment]
+1
Thanks for your work on workflows @miltalex.

**Comment by agilgur5** [comment]
+1 @miltalex has high quality, well tested PRs.

**Comment by terrytangyuan** [comment]
+1
