### ISSUE TITLE
REQUEST: New membership for Adrien-d

### ISSUE THREAD

**Issue by Adrien-D** [argoproj/argoproj#312]
### GitHub Username

@adrien-d

### Requirements
- [x] I have reviewed [the community membership guidelines](https://github.com/argoproj/argoproj/blob/master/community/membership.md)
- [x] I have [enabled 2FA on my GitHub account](https://github.com/settings/security)
- [x] I am actively contributing to 1 or more Argoproj subprojects
- [x] I have two sponsors that meet the sponsor requirements listed in the community membership guidelines
- [x] I have spoken to my sponsors ahead of this application, and they have agreed to sponsor my application
- [x] I understand that I can [make my membership public](https://docs.github.com/en/account-and-profile/setting-up-and-managing-your-personal-account-on-github/managing-your-membership-in-organizations/publicizing-or-hiding-organization-membership) if I'd like to once I am invited to the organization

### Sponsors
- @Joibel 
- @terrytangyuan 

#### PRs reviewed / authored

Argo-workflows

- https://github.com/argoproj/argo-workflows/pull/13343
- https://github.com/argoproj/argo-workflows/pull/13284
- https://github.com/argoproj/argo-workflows/pull/13160
- https://github.com/argoproj/argo-workflows/pull/13113
- https://github.com/argoproj/argo-workflows/pull/13111

Argo-ui

- https://github.com/argoproj/argo-ui/pull/561
- https://github.com/argoproj/argo-ui/pull/560
- https://github.com/argoproj/argo-ui/pull/558

#### Issues responded to

- https://github.com/argoproj/argo-workflows/issues/13171
- https://github.com/argoproj/argo-workflows/issues/13151
- https://github.com/argoproj/argo-workflows/issues/13142
- https://github.com/argoproj/argo-workflows/issues/12947
- https://github.com/argoproj/argo-workflows/issues/12161
- https://github.com/argoproj/argo-workflows/issues/11106

#### Projects I am involved with

- [argo-workflows](https://github.com/argoproj/argo-workflows)
- [argo-ui](https://github.com/argoproj/argo-ui)

**Comment by Joibel** [comment]
+1 Adrien has been usefully contributing to the argo workflows UI. He is a colleague.

**Comment by terrytangyuan** [comment]
+1

**Comment by agilgur5** [comment]
+1 Adrien has made some useful PRs and issues to the UI, API, and some dev env things. Hoping to see more 🙂
