### ISSUE TITLE
REQUEST: New membership for rumstead

### ISSUE THREAD

**Issue by rumstead** [argoproj/argoproj#313]
### GitHub Username

@rumstead

### Requirements
- [x] I have reviewed [the community membership guidelines](https://github.com/argoproj/argoproj/blob/master/community/membership.md)
- [x] I have [enabled 2FA on my GitHub account](https://github.com/settings/security)
- [x] I am actively contributing to 1 or more Argoproj subprojects
- [x] I have two sponsors that meet the sponsor requirements listed in the community membership guidelines
- [x] I have spoken to my sponsors ahead of this application, and they have agreed to sponsor my application
- [x] I understand that I can [make my membership public](https://docs.github.com/en/account-and-profile/setting-up-and-managing-your-personal-account-on-github/managing-your-membership-in-organizations/publicizing-or-hiding-organization-membership) if I'd like to once I am invited to the organization

### Sponsors
- @crenshaw-dev 
- @wanghong230

### List of contributions to the Argoproj project
- PRs reviewed / authored
    * https://github.com/argoproj/argo-cd/pulls?q=is%3Apr+author%3Arumstead+is%3Aclosed (26)
    * https://github.com/argoproj/gitops-engine/pull/598
    * https://github.com/argoproj/applicationset/pull/249
- Issues responded to
    * https://github.com/argoproj/argo-cd/issues?q=is%3Aissue+commenter%3Arumstead
        * 33 open, 42 closed
    * https://github.com/argoproj/argo-cd/discussions?discussions_q=rumstead (6)
- Projects I am involved with
    * Argo CD

**Comment by 34fathombelow** [comment]
+1 rumstead has been actively in the community for quite some time.
