### ISSUE TITLE
argocd_notifications_deliveries_total, argocd_notifications_trigger_eval_total metrics not available in notifications-controller

### ISSUE THREAD

**Issue by shreyakansal96** [argoproj/argoproj#317]
I'm using argocd version 2.10.4 and I'm not able to get notification controller metrics (argocd_notifications_deliveries_total, argocd_notifications_trigger_eval_total) mentioned here at the metrics endpoint.
However, I'm getting go and process related metrics and metrics flag is set to enabled:true in the values.yaml.
Any suggestions on this?
Thanks!
https://github.com/argoproj/argo-cd/blob/v2.10.4/docs/operator-manual/notifications/monitoring.md

**Comment by agilgur5** [comment]
This repo is for Argoproj governance, it sounds like you want the Argo CD repo: https://github.com/argoproj/argo-cd
