### ISSUE TITLE
REQUEST: New membership for @nueavv

### ISSUE THREAD

**Issue by nueavv** [argoproj/argoproj#321]
### GitHub Username
@nueavv

### Requirements
- [x] I have reviewed [the community membership guidelines](https://github.com/argoproj/argoproj/blob/master/community/membership.md)
- [x] I have [enabled 2FA on my GitHub account](https://github.com/settings/security)
- [x] I am actively contributing to 1 or more Argoproj subprojects
- [x] I have two sponsors that meet the sponsor requirements listed in the community membership guidelines
- [x] I have spoken to my sponsors ahead of this application, and they have agreed to sponsor my application
- [x] I understand that I can [make my membership public](https://docs.github.com/en/account-and-profile/setting-up-and-managing-your-personal-account-on-github/managing-your-membership-in-organizations/publicizing-or-hiding-organization-membership) if I'd like to once I am invited to the organization

### Sponsors
- @terrytangyuan 
- @crenshaw-dev 

### List of contributions to the Argoproj project
- PRs reviewed / authored
https://github.com/argoproj/argo-cd/pull/16823
https://github.com/argoproj/argo-cd/pull/16827
https://github.com/argoproj/argo-cd/pull/19469
https://github.com/argoproj/argo-cd/pull/19580
https://github.com/argoproj/argo-cd/pull/19593
https://github.com/argoproj/argo-cd/pull/19853
https://github.com/argoproj/argo-cd/pull/19874
https://github.com/argoproj/argo-cd/pull/20041
https://github.com/argoproj/argo-cd/pull/20049

- Issues responded to
https://github.com/argoproj/argo-cd/issues/19928
https://github.com/argoproj/argo-cd/issues/19872
https://github.com/argoproj/argo-cd/issues/19852
https://github.com/argoproj/argo-cd/issues/20048

- Projects I am involved with
https://github.com/argoproj/argo-cd

**Comment by sunyeongchoi** [comment]
+1

**Comment by terrytangyuan** [comment]
+1

**Comment by ishitasequeira** [comment]
+1
