### ISSUE TITLE
REQUEST: New membership for chengjoey

### ISSUE THREAD

**Issue by chengjoey** [argoproj/argoproj#322]
### GitHub Username

@chengjoey

### Requirements
- [x] I have reviewed [the community membership guidelines](https://github.com/argoproj/argoproj/blob/master/community/membership.md)
- [x] I have [enabled 2FA on my GitHub account](https://github.com/settings/security)
- [x] I am actively contributing to 1 or more Argoproj subprojects
- [x] I have two sponsors that meet the sponsor requirements listed in the community membership guidelines
- [x] I have spoken to my sponsors ahead of this application, and they have agreed to sponsor my application
- [x] I understand that I can [make my membership public](https://docs.github.com/en/account-and-profile/setting-up-and-managing-your-personal-account-on-github/managing-your-membership-in-organizations/publicizing-or-hiding-organization-membership) if I'd like to once I am invited to the organization

### Sponsors
- @agilgur5 
- @terrytangyuan 
- @Joibel 

### List of contributions to the Argoproj project
- PRs authored
   - [fix(controller): remove ArtifactGC finalizer when no artifacts](https://github.com/argoproj/argo-workflows/pull/13500)
   - [fix(docs): use sh instead of bash with busybox](https://github.com/argoproj/argo-workflows/pull/13508)
   - [docs(contrib): add note for signal_darwin error](https://github.com/argoproj/argo-workflows/pull/13534)
   - [fix(controller): handle nil processedTmpl in DAGs](https://github.com/argoproj/argo-workflows/pull/13548)
   - [fix(controller): should fail if dependencies fail, despite continueOn](https://github.com/argoproj/argo-workflows/pull/13501)
   - [feat: use container name as archive log key](https://github.com/argoproj/argo-workflows/pull/13597)
   - [fix(dag): Running hooks should be able to refer to output of earlier tasks](https://github.com/argoproj/argo-workflows/pull/13639)

- Issues responded to
  - [Workflow of workflow containing artifacts cannot be deleted after completion due to finalizer](https://github.com/argoproj/argo-workflows/issues/13556)
   - [riscv64 compiling error: expected 'package', found signal_darwin](https://github.com/argoproj/argo-workflows/issues/9590)
   - [controller panic: nil pointer dereference on DAG processedTmpl](https://github.com/argoproj/argo-workflows/issues/13547)
   - [Using dependencies and continueOn results in unexpected Workflow success status](https://github.com/argoproj/argo-workflows/issues/13498)
  -  [Use container name if supplied in archive logs](https://github.com/argoproj/argo-workflows/issues/13590)
   - [Hooks in DAG cannot refer to output of earlier tasks in some cases](https://github.com/argoproj/argo-workflows/issues/13619)
- Projects I am involved with
   argo-workflows

**Comment by agilgur5** [comment]
+1, I recommended membership in https://github.com/argoproj/argo-workflows/pull/13639#issuecomment-2365229751 as @chengjoey has reported and fixed bugs, root caused some other bugs, helped users in issues, and contributed a new feature! Great work 👏 

> - [ ] I have two sponsors that meet the sponsor requirements listed in the community membership guidelines

For other readers, the lack of initial checkbox is on me: in my linked comment above I also assured we could get a second sponsor, especially as three other Approvers have approved the PRs listed above. I'll ask folks to take a look shortly if they don't see this themselves

**Comment by terrytangyuan** [comment]
+1

**Comment by Joibel** [comment]
+1
