### ISSUE TITLE
REQUEST: Promotion to Reviewer for @rumstead

### ISSUE THREAD

**Issue by rumstead** [argoproj/argoproj#326]
### GitHub Username

@rumstead

### Sub-project(s)

Promotion is requested for the following sub-project(s).

- [x] Argo CD
- [ ] Argo Events
- [ ] Argo Rollouts
- [ ] Argo Workflows

### Requirements

- [x] Member for at least 3 months (as of the membership meeting date)
- [x] Reviewer for or author of at least 5 substantial PRs to the codebase
1. https://github.com/argoproj/argo-cd/pull/12714
2. https://github.com/argoproj/argo-cd/pull/12409
3. https://github.com/argoproj/argo-cd/pull/12480
4. https://github.com/argoproj/argo-cd/pull/18537
5. https://github.com/argoproj/argo-cd/pull/9080

### Lead Sponsor(s)

Promotion to Reviewer requires sponsorship from at least one sub-project Lead.

- @crenshaw-dev 

### Other Sponsors

- @<sponsor-1>

**Comment by wanghong230** [comment]
+1

**Comment by edlee2121** [comment]
+1

**Comment by ishitasequeira** [comment]
+1

**Comment by jannfis** [comment]
+1
