### ISSUE TITLE
REQUEST: New membership for MasonM

### ISSUE THREAD

**Issue by MasonM** [argoproj/argoproj#327]
### GitHub Username

@MasonM

### Requirements
- [X] I have reviewed [the community membership guidelines](https://github.com/argoproj/argoproj/blob/master/community/membership.md)
- [X] I have [enabled 2FA on my GitHub account](https://github.com/settings/security)
- [X] I am actively contributing to 1 or more Argoproj subprojects
- [X] I have two sponsors that meet the sponsor requirements listed in the community membership guidelines
- [X] I have spoken to my sponsors ahead of this application, and they have agreed to sponsor my application
- [X] I understand that I can [make my membership public](https://docs.github.com/en/account-and-profile/setting-up-and-managing-your-personal-account-on-github/managing-your-membership-in-organizations/publicizing-or-hiding-organization-membership) if I'd like to once I am invited to the organization

### Sponsors
- @agilgur5 
- @terrytangyuan 

### List of contributions to the Argoproj project
- https://github.com/argoproj/argo-workflows/pull/13593
- https://github.com/argoproj/argo-workflows/pull/13670
- https://github.com/argoproj/argo-workflows/pull/13660
- https://github.com/argoproj/argo-workflows/pull/13635
- https://github.com/argoproj/argo-workflows/pull/13604
- https://github.com/argoproj/argo-workflows/pull/13596
- https://github.com/argoproj/argo-workflows/pull/13609
- https://github.com/argoproj/argo-workflows/pull/13628
- https://github.com/argoproj/argo-workflows/pull/13642
- https://github.com/argoproj/argo-workflows/pull/13656
- https://github.com/argoproj/argo-workflows/pull/13674
- https://github.com/argoproj/argo-workflows/pull/13695

**Comment by terrytangyuan** [comment]
+1

**Comment by Joibel** [comment]
+1

**Comment by isubasinghe** [comment]
+1

**Comment by shuangkun** [comment]
+1
