### ISSUE TITLE
REQUEST: New membership for @daengdaengLee

### ISSUE THREAD

**Issue by daengdaengLee** [argoproj/argoproj#328]
### GitHub Username

@daengdaengLee

### Requirements
- [X] I have reviewed [the community membership guidelines](https://github.com/argoproj/argoproj/blob/master/community/membership.md)
- [X] I have [enabled 2FA on my GitHub account](https://github.com/settings/security)
- [X] I am actively contributing to 1 or more Argoproj subprojects
- [X] I have two sponsors that meet the sponsor requirements listed in the community membership guidelines
- [X] I have spoken to my sponsors ahead of this application, and they have agreed to sponsor my application
- [X] I understand that I can [make my membership public](https://docs.github.com/en/account-and-profile/setting-up-and-managing-your-personal-account-on-github/managing-your-membership-in-organizations/publicizing-or-hiding-organization-membership) if I'd like to once I am invited to the organization

### Sponsors
- @terrytangyuan 
- @pasha-codefresh 
- @crenshaw-dev 

### List of contributions to the Argoproj project
- PRs reviewed / authored
  - https://github.com/argoproj/argo-cd/pull/19128
  - https://github.com/argoproj/argo-cd/pull/19191
  - https://github.com/argoproj/argo-cd/pull/19274
  - https://github.com/argoproj/argo-cd/pull/19288
  - https://github.com/argoproj/argo-cd/pull/19354
  - https://github.com/argoproj/argo-cd/pull/19397
  - https://github.com/argoproj/argo-cd/pull/19686
  - https://github.com/argoproj/argo-cd/pull/19742
  - https://github.com/argoproj/argo-cd/pull/20002
  - https://github.com/argoproj/argo-cd/pull/20043
  - https://github.com/argoproj/argo-cd/pull/20113 (cowork)
  - https://github.com/argoproj/argo-cd/pull/20211 (cowork)
  - https://github.com/argoproj/argo-cd/pull/20543
- Issues responded to
  - https://github.com/argoproj/argo-cd/issues/19741 (create)
  - https://github.com/argoproj/argo-cd/issues/19269 (comment)
  - https://github.com/argoproj/argo-cd/issues/20252 (create)
- Projects I am involved with
  - ArgoCD

**Comment by sunyeongchoi** [comment]
+1

**Comment by pasha-codefresh** [comment]
+1

**Comment by terrytangyuan** [comment]
+1
