### ISSUE TITLE
REQUEST: Promotion to Reviewer for reggie-k

### ISSUE THREAD

**Issue by reggie-k** [argoproj/argoproj#329]
### GitHub Username

@reggie-k 

### Sub-project(s)

Promotion is requested for the following sub-project(s).

- [X] Argo CD
- [ ] Argo Events
- [ ] Argo Rollouts
- [ ] Argo Workflows

### Requirements

- [X] Member for at least 3 months (as of the membership meeting date)
- [X] Reviewer for or author of at least 5 substantial PRs to the codebase
    - Author: feat: Introduce RBAC based approach to pod logs - https://github.com/argoproj/argo-cd/pull/8353, https://github.com/argoproj/argo-cd/pull/9828
    - Author: feat: Create job action - https://github.com/argoproj/argo-cd/pull/12925
    - Author: fix: Exec with disable auth not logged in - https://github.com/argoproj/argo-cd/pull/19529
    - Author: feat: AppSet UI Support - https://github.com/argoproj/argo-cd/pull/16689 (WIP)
    - Author: feat: Shared custom health check for multiple resources - https://github.com/argoproj/argo-cd/pull/10885
    - Author: chore: Make dev env redis password protected - https://github.com/argoproj/argo-cd/pull/19863
    - Author: chore: fixing dubious ownership error - https://github.com/argoproj/argo-cd/pull/19400
    - Reviewer: fix(pkce): 20111 PKCE auth flow does not return user to previous path like dex auth flow 
    -  https://github.com/argoproj/argo-cd/pull/20202
    - Reviewer: fix(pkce): 18045 PKCE respect base href and Reauth to PKCE on token expire - https://github.com/argoproj/argo-cd/pull/20110
    - Reviewer: feat(appset): parameterize requeue time - https://github.com/argoproj/argo-cd/pull/20064
    - Reviewer: fix: Refine resource option evaluation for argocd app sync command - https://github.com/argoproj/argo-cd/pull/19579
    - Reviewer: fix(#19263): 'argocd admin settings rbac can' command should honor server.rbac.log.enforce.enable param in argocd-cm - https://github.com/argoproj/argo-cd/pull/19264
    - Reviewer: fix(cli): admin settings rbac can has inconsistency among project resources - https://github.com/argoproj/argo-cd/pull/17805
    - Reviewer: fix: handle incorrect cluster RESTconfig without panic - https://github.com/argoproj/argo-cd/pull/20150
    - Reviewer: feat(ui): support auto theme - https://github.com/argoproj/argo-cd/pull/20080
    - Reviewer: feat(ui): display sha's revision in every history release - https://github.com/argoproj/argo-cd/pull/19963
    - Reviewer: feat: Change the file name convention when downloading pod logs - https://github.com/argoproj/argo-cd/pull/19938
    
- [X] Additional contributions: triaged and labeled ~200 GitHub issues in ArgoCD repo

### Lead Sponsor(s)

Promotion to Reviewer requires sponsorship from at least one sub-project Lead.

- @crenshaw-dev 

### Other Sponsors

- @todaywasawesome 
- @pasha-codefresh

**Comment by crenshaw-dev** [comment]
An enthusiastic +1 from me!

**Comment by terrytangyuan** [comment]
+1

**Comment by todaywasawesome** [comment]
+1

**Comment by jannfis** [comment]
Oops. Missed this. Obviously, this is a clear +1

**Comment by leoluz** [comment]
+1

**Comment by tuunit** [comment]
+1
