### ISSUE TITLE
REQUEST: Self-nomination for sub-project lead for @Joibel

### ISSUE THREAD

**Issue by Joibel** [argoproj/argoproj#330]
There is no pro-forma for this. Opened in response to [request for nominations](https://cloud-native.slack.com/archives/C022F03E6BD/p1728911781755299) (this is a private channel for maintainers)

### GitHub Username

@Joibel

### Sub-project(s)

Promotion is requested for the following sub-project(s).

- [ ] Argo CD
- [ ] Argo Events
- [ ] Argo Rollouts
- [x] Argo Workflows

### Lead Sponsors

-

### Other Sponsors

-

#### Feature development

To measure feature size I'm using the crude metric `git log origin/main...v3.5.0 --shortstat --grep feat -- workflow/ server/ ui/ cli/ | grep insertions` and manually discarding changes to `ui/yarn.lock`.

I have delivered 18 new features to workflows in total: https://github.com/argoproj/argo-workflows/pulls?q=is%3Apr+author%3AJoibel+is%3Amerged+feat+

I also have the highest number of new features in 3.6, although this count is heavily dependent on the separated metrics features:
`git log origin/main...v3.5.0 --shortstat --grep feat | grep Author | sort | uniq -c`

##### Metrics and OpenTelemetry

The workflow controller can now emit metrics over OpenTelemetry GRPC protocol [#13265](https://github.com/argoproj/argo-workflows/pull/13265). This is the largest new golang feature in 3.6.

This comes with selectable temporality[#13267](https://github.com/argoproj/argo-workflows/pull/13267) and more configuration of what is emitted [#13268](https://github.com/argoproj/argo-workflows/pull/13268), and new metrics:
* Version information in the controller [#13269](https://github.com/argoproj/argo-workflows/pull/13269)
* Is this controller the leader [#13270](https://github.com/argoproj/argo-workflows/pull/13270)
* Kubernetes API calls duration [#13271](https://github.com/argoproj/argo-workflows/pull/13271)
* Pod phase monitoring [#13272](https://github.com/argoproj/argo-workflows/pull/13272) and pod pending problem metrics [#13273](https://github.com/argoproj/argo-workflows/pull/13273)
* Cron Workflow [#13274](https://github.com/argoproj/argo-workflows/pull/13274) and Workflow Template [#13275](https://github.com/argoproj/argo-workflows/pull/13275) counters

This also enables adding of future, well deliniated new metrics such like [this](https://github.com/argoproj/argo-workflows/blob/main/workflow/metrics/counter_cronworkflow_policy.go) as implemented later in [#13497](https://github.com/argoproj/argo-workflows/pull/13497)

This feature is for the community and although it takes feedback from many sources is not directly a Pipekit customer demand, and [steered](https://github.com/argoproj/argo-workflows/issues/12589) by the community.

##### Multiple semaphores

[#13358](https://github.com/argoproj/argo-workflows/pull/13358) is the second largest new golang feature in 3.6.

This addresses two long standing issues [#5022](https://github.com/argoproj/argo-workflows/issues/5022) and [#11859](https://github.com/argoproj/argo-workflows/issues/11859). Although this was developed directly as a Pipekit customer request, the demand was pre-existing.
https://github.com/argoproj/argo-workflows/pulls?q=is%3Apr+author%3AJoibel+is%3Amerged+feat+

##### Fixing server crashes

Fixing the sqllite change crashing the server [#13166](https://github.com/argoproj/argo-workflows/pull/13166) was developed by myself in response to various problem reports.

Note: No pipekit customer was affected by this bug, they had not upgraded at the time of the issue.

##### Sustainability

13 PRs improving [devcontainer](https://github.com/argoproj/argo-workflows/pulls?q=is%3Apr+author%3Ajoibel+devcontainer+is%3Aclosed+) and [everyone's](https://github.com/argoproj/argo-workflows/pulls?q=is%3Apr+author%3Ajoibel+devcontainer+is%3Aclosed+) developer experience.

And a number improving [linting/testing](https://github.com/argoproj/argo-workflows/pulls?q=is%3Apr+author%3Ajoibel+is%3Amerged++lint) (I can't find a good query to eliminate the invalid matched ones of those).

I have also encouraged a number of active new members:
* [Shuangkun](https://github.com/argoproj/argoproj/issues/266)
* [Eduardodbr](https://github.com/argoproj/argoproj/issues/272)
* [jswxstw](https://github.com/argoproj/argoproj/issues/295)
* [miltalex](https://github.com/argoproj/argoproj/issues/307)
* [Adrien-D (Pipekit affiliated)](https://github.com/argoproj/argoproj/issues/312).
 
I'm working with two more Pipekit staff to get them membership through their contributions: https://github.com/djanjic and https://github.com/elliotgunton/.

##### Talks around Argo

* [Memoization at ArgoCon 2023 Chicago](https://www.youtube.com/watch?v=29r3wZHP2eU)
* [Project updates at ArgoCon 2024 Paris](https://www.youtube.com/watch?v=rAxmd9oPiFk)
* [Talk on Argo CD feature at ArgoCon 2024 Paris](https://www.youtube.com/watch?v=n0X2b8Rcqb4)
* Future talk on a new feature - tracing [at ArgoCon 2024 Salt Lake](https://colocatedeventsna2024.sched.com/event/1izsI/untangling-the-threads-understanding-argo-workflows-with-workflow-tracing-alan-clucas-pipekit-inc-jason-meridth-github)

##### Deprecations

To help maintain the project I've done a fair amount of work on paving a smooth path to remove legacy code:

* Metrics to know if you're using them [#13735](https://github.com/argoproj/argo-workflows/pull/13735)
* Highlight deprecations [#13757](https://github.com/argoproj/argo-workflows/pull/13757)
* Deprecate python auto generated SDK [#13719](https://github.com/argoproj/argo-workflows/pull/13719)

##### Little fixes all over the place

Picking up those one line fixes to keep things moving:
Missed documentation:
https://github.com/argoproj/argo-workflows/pull/13582
https://github.com/argoproj/argo-workflows/pull/13463
Fixing the test suite when it breaks: https://github.com/argoproj/argo-workflows/pull/13624
Improving upgrades: https://github.com/argoproj/argo-workflows/pull/13332
There are more of these, but these are highlights.

##### Slack, community and office hours

I am one of the most active people in #argo-workflows in slack, and Pipekit run regular office-hours sessions to help people out face-to-face which I attend.

##### CNCF Talks Committee

I have was a member of the KubeCon + CloudNativeCon Program Committee NA 2024 (Operations & Performance)

#### Releases

Kicked off the 3.6 release cycle along with blog posts and administering the process.

Picked up 3.5.11 release when Anton was ill.

#### Stats

How do you want to measure it:

- I'm the second most active contributor in the last 12 months: https://github.com/argoproj/argo-workflows/graphs/contributors?from=30%2F09%2F2023
- I'm the third most active contributor in the last 12 months: https://insights.lfx.linuxfoundation.org/foundation/cncf/overview?project=argo&repository=https:%2F%2Fgithub.com%2Fargoproj%2Fargo-workflows

#### Older evidence

Pre-approver commentary in #276

**Comment by JPZ13** [comment]
I'm @Joibel's manager and am obviously biased, but we're very fortunate to have Alan on the team. He is an extremely thoughtful and kind person/engineer. He would be an excellent steward of the project that would benefit the community as a whole

**Comment by isubasinghe** [comment]
+1 I am obviously biased as Alan's colleague, but I do truly believe he would be an excellent steward of the project.

**Comment by terrytangyuan** [comment]
+1

**Comment by sarabala1979** [comment]
+1
