### ISSUE TITLE
REQUEST: New membership for @jaehanbyun

### ISSUE THREAD

**Issue by jaehanbyun** [argoproj/argoproj#333]
### GitHub Username

@jaehanbyun

### Requirements
- [X] I have reviewed [the community membership guidelines](https://github.com/argoproj/argoproj/blob/master/community/membership.md)
- [X] I have [enabled 2FA on my GitHub account](https://github.com/settings/security)
- [X] I am actively contributing to 1 or more Argoproj subprojects
- [X] I have two sponsors that meet the sponsor requirements listed in the community membership guidelines
- [X] I have spoken to my sponsors ahead of this application, and they have agreed to sponsor my application
- [X] I understand that I can [make my membership public](https://docs.github.com/en/account-and-profile/setting-up-and-managing-your-personal-account-on-github/managing-your-membership-in-organizations/publicizing-or-hiding-organization-membership) if I'd like to once I am invited to the organization

### Sponsors
- @terrytangyuan
- @edlee2121
- @jannfis 

### List of contributions to the Argoproj project
- PRs reviewed / authored
  - argoproj/argo-cd#20118
  - argoproj/argo-cd#20251
  - argoproj/argo-cd#20303
  - argoproj/argo-cd#20322
  - argoproj/argo-cd#20533
  - argoproj/argo-cd#20521
  - argoproj/argo-cd#20560
  - argoproj/argo-cd#20702
&nbsp;
- Issues responded to
    - argoproj/argo-cd#20289
    - argoproj/argo-cd#20510
&nbsp;
- Projects I am involved with
    - argo-cd

**Comment by terrytangyuan** [comment]
+1

**Comment by edlee2121** [comment]
+!

**Comment by jannfis** [comment]
+1
