### ISSUE TITLE
REQUEST: New membership for @nitishfy

### ISSUE THREAD

**Issue by nitishfy** [argoproj/argoproj#334]
### GitHub Username

@nitishfy

### Requirements
- [x] I have reviewed [the community membership guidelines](https://github.com/argoproj/argoproj/blob/master/community/membership.md)
- [x] I have [enabled 2FA on my GitHub account](https://github.com/settings/security)
- [x] I am actively contributing to 1 or more Argoproj subprojects
- [x] I have two sponsors that meet the sponsor requirements listed in the community membership guidelines
- [x] I have spoken to my sponsors ahead of this application, and they have agreed to sponsor my application
- [x] I understand that I can [make my membership public](https://docs.github.com/en/account-and-profile/setting-up-and-managing-your-personal-account-on-github/managing-your-membership-in-organizations/publicizing-or-hiding-organization-membership) if I'd like to once I am invited to the organization

### Sponsors
- @crenshaw-dev 
- @leoluz 
- @ishitasequeira 
- @terrytangyuan

### List of contributions to the Argoproj project
- PRs reviewed / authored
  - PRs merged:
    - https://github.com/argoproj/argo-cd/pull/20342
    - https://github.com/argoproj/argo-cd/pull/20070
    - https://github.com/argoproj/argo-cd/pull/20069
    - https://github.com/argoproj/argo-cd/pull/19887
    - https://github.com/argoproj/argo-cd/pull/19879
    - https://github.com/argoproj/argo-cd/pull/19621
    - https://github.com/argoproj/argo-cd/pull/19384
  - PRs opened:
    - https://github.com/argoproj/argo-cd/pull/19598
    - https://github.com/argoproj/argo-cd/pull/20074
  - Issues opened/closed:
    - https://github.com/argoproj/argo-cd/issues/20324
    - https://github.com/argoproj/argo-cd/issues/19756
    - https://github.com/argoproj/argo-cd/issues/19616
    - https://github.com/argoproj/argo-cd/issues/19851
  - PRs reviewed (Opened):
    - https://github.com/argoproj/argo-cd/pull/20506
    - https://github.com/argoproj/argo-cd/pull/20486
    - https://github.com/argoproj/argo-cd/pull/20470
    - https://github.com/argoproj/argo-cd/pull/20329
    - https://github.com/argoproj/argo-cd/pull/20074
    - https://github.com/argoproj/argo-cd/pull/20036
    - https://github.com/argoproj/argo-cd/pull/19921
    - https://github.com/argoproj/argo-cd/pull/19907
    - https://github.com/argoproj/argo-cd/pull/14189
  - PRs reviewed (Merged):
    - https://github.com/argoproj/argo-cd/pull/20303
    - https://github.com/argoproj/argo-cd/pull/20317
    - https://github.com/argoproj/argo-cd/pull/20318
    - https://github.com/argoproj/argo-cd/pull/20322
    - https://github.com/argoproj/argo-cd/pull/20337
    - https://github.com/argoproj/argo-cd/pull/20339
    - https://github.com/argoproj/argo-cd/pull/20347
    - https://github.com/argoproj/argo-cd/pull/20409
    - https://github.com/argoproj/argo-cd/pull/20420
    - https://github.com/argoproj/argo-cd/pull/20488
    - https://github.com/argoproj/argo-cd/pull/20490
    - https://github.com/argoproj/argo-cd/pull/20503
     and 70+ other PRs.... (https://github.com/argoproj/argo-cd/pulls?q=is%3Apr+reviewed-by%3A%40me+is%3Aclosed)
- Issues responded to
  - https://github.com/argoproj/argo-cd/issues/19563
  - https://github.com/argoproj/argo-cd/issues/18968
  - https://github.com/argoproj/argo-cd/issues/19193
  - https://github.com/argoproj/argo-cd/issues/19638
  - https://github.com/argoproj/argo-cd/issues/19709 
- Projects I am involved with:
  -  Argo CD

**Comment by leoluz** [comment]
+1

**Comment by wanghong230** [comment]
+!

**Comment by crenshaw-dev** [comment]
+1

**Comment by terrytangyuan** [comment]
+1

**Comment by ishitasequeira** [comment]
+1

**Comment by andrii-korotkov-verkada** [comment]
+1
