### ISSUE TITLE
REQUEST: Promotion to Reviewer for @jswxstw

### ISSUE THREAD

**Issue by jswxstw** [argoproj/argoproj#337]
### GitHub Username

@jswxstw 

### Sub-project(s)

Promotion is requested for the following sub-project(s).

- [ ] Argo CD
- [ ] Argo Events
- [ ] Argo Rollouts
- [x] Argo Workflows

### Requirements

- [x] Member for at least 3 months (as of the membership meeting date)
- [x] Reviewer for or author of at least 5 substantial PRs to the codebase
    - https://github.com/argoproj/argo-workflows/pull/13761
    - https://github.com/argoproj/argo-workflows/pull/13537
    - https://github.com/argoproj/argo-workflows/pull/13491
    - https://github.com/argoproj/argo-workflows/pull/13294
    - https://github.com/argoproj/argo-workflows/pull/13260
    - https://github.com/argoproj/argo-workflows/pull/13214
    - https://github.com/argoproj/argo-workflows/pull/13211
    - https://github.com/argoproj/argo-workflows/pull/13198
    - https://github.com/argoproj/argo-workflows/pull/13016
    - https://github.com/argoproj/argo-workflows/pull/12960
    - https://github.com/argoproj/argo-workflows/pull/12833
    - https://github.com/argoproj/argo-workflows/pull/12830
    - https://github.com/argoproj/argo-workflows/pull/12723
    - https://github.com/argoproj/argo-workflows/pull/12620
    - https://github.com/argoproj/argo-workflows/pull/12476
    - https://github.com/argoproj/argo-workflows/pull/12440

### Lead Sponsor(s)

Promotion to Reviewer requires sponsorship from at least one sub-project Lead.

- @terrytangyuan 

### Other Sponsors

- @Joibel

**Comment by Joibel** [comment]
+1 from me. jswxstw has some really good knowledge of the controller codebase. They already heavily contribute by adding valuable commentary on other people's PRs
I've edited the description to put myself as "Other Sponsors" and will await @juliev0 and @terrytangyuan publically commenting to re-add them to the description.

**Comment by terrytangyuan** [comment]
+1

**Comment by juliev0** [comment]
+1 @jswxstw has worked on some complicated PRs in the Controller and shows excellent logical reasoning. Highly recommend.
