### ISSUE TITLE
REQUEST: New membership for @svghadi

### ISSUE THREAD

**Issue by svghadi** [argoproj/argoproj#339]
### GitHub Username

@svghadi

### Requirements
- [x] I have reviewed [the community membership guidelines](https://github.com/argoproj/argoproj/blob/master/community/membership.md)
- [x] I have [enabled 2FA on my GitHub account](https://github.com/settings/security)
- [x] I am actively contributing to 1 or more Argoproj subprojects
- [x] I have two sponsors that meet the sponsor requirements listed in the community membership guidelines
- [x] I have spoken to my sponsors ahead of this application, and they have agreed to sponsor my application
- [x] I understand that I can [make my membership public](https://docs.github.com/en/account-and-profile/setting-up-and-managing-your-personal-account-on-github/managing-your-membership-in-organizations/publicizing-or-hiding-organization-membership) if I'd like to once I am invited to the organization

### Sponsors
- @jannfis 
- @ishitasequeira 

### List of contributions to the Argoproj project
- PRs reviewed / authored
  - https://github.com/argoproj/argo-cd/pull/19488
  - https://github.com/argoproj/argo-cd/pull/18216
  - https://github.com/argoproj/argo-cd/pull/18160
  - https://github.com/argoproj/argo-cd/pull/16794
  - https://github.com/argoproj/argo-cd/pull/16748
  - https://github.com/argoproj/argo-cd/pull/15394
  - https://github.com/argoproj/gitops-engine/pull/538
  - https://github.com/argoproj/gitops-engine/pull/577
  - https://github.com/argoproj/argo-cd/pull/18660 

- Issues responded to
  - https://github.com/argoproj/argo-cd/issues/19638
  - https://github.com/argoproj/argo-cd/issues/9070
  - https://github.com/argoproj/argo-cd/issues/16972
  - https://github.com/argoproj/argo-cd/issues/11381
  - https://github.com/argoproj/argo-cd/issues/13726
  - https://github.com/argoproj/argo-cd/issues/3539
  - https://github.com/argoproj/argo-cd/issues/18576

- Issues reported
  - https://github.com/argoproj/argo-cd/issues/15074
  - https://github.com/argoproj/argo-cd/issues/15392
  - https://github.com/argoproj/argo-cd/issues/16775
  - https://github.com/argoproj/argo-cd/issues/16793
  - https://github.com/argoproj/argo-cd/issues/19138
  - https://github.com/argoproj/argo-cd/issues/19780
  - https://github.com/argoproj/argo-cd/issues/14038

- Projects I am involved with
  - argo-cd

**Comment by wtam2018** [comment]
+1

**Comment by ishitasequeira** [comment]
+1

**Comment by jannfis** [comment]
+1

**Comment by terrytangyuan** [comment]
+1

**Comment by blakepettersson** [comment]
+1
