### ISSUE TITLE
REQUEST: New membership for andrii-korotkov-verkada and andrii-korotkov

### ISSUE THREAD

**Issue by andrii-korotkov-verkada** [argoproj/argoproj#341]
### GitHub Username

@andrii-korotkov-verkada
@andrii-korotkov

### Requirements
- [x] I have reviewed [the community membership guidelines](https://github.com/argoproj/argoproj/blob/master/community/membership.md)
- [x] I have [enabled 2FA on my GitHub account](https://github.com/settings/security)
- [x] I am actively contributing to 1 or more Argoproj subprojects
- [x] I have two sponsors that meet the sponsor requirements listed in the community membership guidelines
- [x] I have spoken to my sponsors ahead of this application, and they have agreed to sponsor my application
- [x] I understand that I can [make my membership public](https://docs.github.com/en/account-and-profile/setting-up-and-managing-your-personal-account-on-github/managing-your-membership-in-organizations/publicizing-or-hiding-organization-membership) if I'd like to once I am invited to the organization

### Sponsors
- @crenshaw-dev 
- @jannfis 

### List of contributions to the Argoproj project
- PRs reviewed / authored: https://github.com/argoproj/argo-cd/pulls?q=is%3Apr+author%3Aandrii-korotkov-verkada+
- Issues responded to: https://github.com/argoproj/argo-cd/issues?q=commenter%3A%40me+, https://github.com/argoproj/argo-cd/issues?q=author%3Aandrii-korotkov-verkada+
- Projects I am involved with: ArgoCD

**Comment by andrii-korotkov-verkada** [comment]
The usernames are my work username and personal username. I mainly contribute with the work one, but wanna remain a member if I change jobs.

**Comment by ishitasequeira** [comment]
+1

**Comment by jannfis** [comment]
+1

**Comment by blakepettersson** [comment]
+1

**Comment by terrytangyuan** [comment]
+1

**Comment by alexmt** [comment]
+1

**Comment by andrii-korotkov-verkada** [comment]
This was done, I'm a member now! Thanks everyone!
