### ISSUE TITLE
Introduce Backlog Grooming for all Argo projects

### ISSUE THREAD

**Issue by sbose78** [argoproj/argoproj#37]
### Proposal
I would like to propose a process for grooming new issues that get opened on Github.

At the moment, we have a lot of open issues which have not been added to any milestone:

- [Untriaged Argo Workflow issues](https://github.com/argoproj/argo-workflows/issues?q=is%3Aissue+no%3Amilestone+sort%3Acreated-asc+is%3Aopen)
- [Untriaged Argo Events issues](https://github.com/argoproj/argo-events/issues?q=is%3Aissue+no%3Amilestone+sort%3Acreated-asc+is%3Aopen)
- [Untriaged Argo CD issues](https://github.com/argoproj/argo-cd/issues?q=is%3Aissue+no%3Amilestone+sort%3Acreated-asc+is%3Aopen)
- [Untriaged Argo Rollout issues](https://github.com/argoproj/argo-rollouts/issues?q=is%3Aissue+no%3Amilestone+sort%3Acreated-asc+is%3Aopen)

----

#### Why
* Separates out "discussions" from bug/feature reports.
* Helps identify if something needs a detailed enhancement proposal early on.

#### Who
* Weekly assignment of "triage" role ( good way for new folks to get involved )
* If assignee doesn't have permissions to add labels, pair up with someone who has. 

----

#### Why
* Provides feedback to the issue reporter on how soon an issue may be taken up for resolution.
* Helps contributors pick up new tasks which align with the strategy/priorities of the project
* Helps identify if something needs a detailed enhancement proposal early on.

#### Who
* Led by project leads, attended by anyone interested. 
* Once-in-two weeks.
* Existing meetings may be re-purposed.

#### What
What will we answer about every new Github Issue ?

* Will this be attempted in this milestone ? "Current" milestone
* Will this be attempted in the next milestone ? "Current + 1" milestone 
* Will this be considered at all ? "backlog" milestone

Note, this is an expression of intent. Milestone assignments may change during planning.

**Comment by sbose78** [comment]
Update: This was discussed and we'll be starting this process for ArgoCD.

**Comment by edlee2121** [comment]
Closing stale issue
