### ISSUE TITLE
Plan for graduating the ArgoCD Image Updater Project?

### ISSUE THREAD

**Issue by gnunn1** [argoproj/argoproj#39]
Currently there is a gap in integrating CI tools like Tekton with ArgoCD. The ArgoCD Image Updater project (https://argocd-image-updater.readthedocs.io/en/stable/) aims to address this gap however the project documentation indicates that it still has a ways to go. I think this project is important with regards to integrating ArgoCD with CI which currently tends to be a cumbersome process that different teams are repeating over and over due to missing this sort of tool.

I was wondering if there is a formal plan for on-boarding and graduating this project into the ArgoCD umbrella and if any details could be shared.

**Comment by edlee2121** [comment]
Closing stale issue

**Comment by crenshaw-dev** [comment]
Work underway to merge w/ Argo CD: https://github.com/argoproj/argo-cd/pull/10446
