### ISSUE TITLE
[Proposal] Argoproj Community Supported Project Listing

### ISSUE THREAD

**Issue by dcherman** [argoproj/argoproj#41]
I think it'd be useful to have an area of the site where the community could contribute links to non-Argoproj sponsored/maintained projects that are related to one or more Argoproj projects.

To give you an idea of what I mean, it could be something like the `awesome-kubernetes` site https://ramitsurana.github.io/awesome-kubernetes/projects/projects/ where community members contribute links to their projects that others might find useful, but with the understanding that they are not part of the Argoproj umbrella.

I'd love to get this kicked off with a link to [my own project](https://github.com/dcherman/image-cache-daemon) for pre-pulling images that are referenced in WorkflowTemplates, CronWorkflows, etc..  :)

**Comment by sbose78** [comment]
Thank you @dcherman I would support this,
We could have a repository `https://github.com/argoproj-labs/friends` where every project is a <directory>/README.md . These are projects who haven't necessarily moved to argoproj-labs but is uses Argo in a way that it should be listed and discoverable. 

@todaywasawesome (Dan) , @edlee2121 what do you think?

**Comment by sbose78** [comment]
Added to the agenda of today's bootstrap committee meeting for consensus.

**Comment by sbose78** [comment]
notes from the meeting : We'll be creating a repo in the argoproj-labs org. Thanks a lot @dcherman for initiating this.

**Comment by sbose78** [comment]
I could create a repo if https://github.com/argoproj/argoproj/issues/55 is taken care of 
@edlee2121 could you help me get moving?

**Comment by edlee2121** [comment]
Done

**Comment by sbose78** [comment]
Thank you, @edlee2121 ! 


@dcherman https://github.com/argoproj-labs/friends

**Comment by dcherman** [comment]
First PR up! https://github.com/argoproj-labs/friends/pull/2
