### ISSUE TITLE
Migrate to CNCF Slack (to join https://slack.cncf.io/)

### ISSUE THREAD

**Issue by alexec** [argoproj/argoproj#47]
# Status

Committed.

# Why

* Argo is a CNCF graduating project.
* It will be easy to work with other communities
* CNCF Slack has >10k message history.
* The current Slack provides support to users, but this does not scale. It would be better for the ecosystem to ask for help via each project's Github Discussions.

# How 

We'll archive the channels on the following schedule, some of which will be migrated to CNCF Slack (https://cloud-native.slack.com/). The party responsible for creating the new channel is listed. @alexec will archive the channel on that schedule.

To join CNCF slack -> https://slack.cncf.io/

| Status | Channel | Users | Date | Migrator | CNCF Channel | 
|---|---|---|---|---|---|
| ✔️ | #argo-approvers | <100 | 15 Apr 2021 | @edlee2121 | #argo-approvers |
| ✔️ | #argo-sig-ui | <100 | 15 Apr 2021 | @rbreeze | [#argo-sig-ui](https://cloud-native.slack.com/archives/C01TR44A8NB) |
| ✔️ | #argo-sdks | <100 | 15 Apr 2021 | no |  N/A |
| ✔️ | #argo-rollouts-and-deployments | <100 | 15 Apr 2021 | no |  N/A  |
| ✔️ | #argoproj-and-gitlab | <100 | 15 Apr 2021 | no |   N/A |
| ✔️ | #argoproj-deployments-notfications | <100 | 15 Apr 2021 | no|  N/A |
| ✔️ | #argo-cd-appset | <500 | 22 Apr 2021 | @jessesuen | [#argo-cd-appset](https://cloud-native.slack.com/archives/C01U45M2SVB) |
| ✔️ | #argo-sig-ci | <500 | 22 Apr 2021 | no |  N/A |
| ✔️ | #argocd-notifications | <500 | 22 Apr 2021 | @jessesuen | [#argo-cd-notifications](https://cloud-native.slack.com/archives/C01UKS2NKK3) |
| ✔️ | #random | <500 | 22 Apr 2021 | no |  N/A |
| - | #argo-helm | >500 | 29 Apr 2021 | no |  [#argo-helm-charts](https://cloud-native.slack.com/archives/C02097VUKUM)] |
| - | #argo-rollouts | >500 | 29 Apr 2021 | @jessesuen | [#argo-rollouts](https://cloud-native.slack.com/archives/C01U781DW2E) |
| - | #argo-dev | >500 | 29 Apr 2021 | no |  N/A  |
| - | #argo-events | >500 | 29 Apr 2021 | @alexec | [#argo-events](https://cloud-native.slack.com/archives/C01TNKD6KL6) |
| - | #argo-cd | >500 | 29 Apr 2021 | @jessesuen | [#argo-cd](https://cloud-native.slack.com/archives/C01TSERG0KZ) | 
| - | #argo-workflows | >500| 29 Apr 2021 | @alexec | [#argo-workflows](https://cloud-native.slack.com/archives/C01QW9QSSSK) |
| - | #annoucements | >500 | 29 Apr 2021 | no |  N/A |

**Comment by terrytangyuan** [comment]
Where will announcements be made if there's no equivalent of #announcements in CNCF Slack? I guess there will be subproject-wise announcements in each sub-project channels then?

**Comment by alexec** [comment]
I suggest we use the products channel for announcements. We can always create new channels if there is demand. I find less Slack channels is better than more.

**Comment by dshackith** [comment]
It would be helpful to point to the sign-up for CNCF Slack, so that it is easy for folks that are not yet there to get there.

**Comment by edlee2121** [comment]
The url is in the initial comment but added it to title to make it easier to find.
FYI: https://cloud-native.slack.com/

**Comment by dshackith** [comment]
That is the URL to sign in, but you need to go through a process to request an account before you can log in. The link on cncf.io to Slack should be an join process, but the link is currently not working: https://slack.cncf.io/

**Comment by edlee2121** [comment]
Thanks, added the info and notified the CNCF ops team.

**Comment by edlee2121** [comment]
The link is fixed now.
https://slack.cncf.io/

**Comment by sbose78** [comment]
Plan looks good to me. Thanks for putting this together!

**Comment by terrytangyuan** [comment]
Perhaps we should do a few `@here` or `@channel` announcements in those channels since they may have muted those channels most of the time. `#announcements` is probably the only channel that many people don't mute normally to stay up-to-date with the project so perhaps we can announce there as well.

**Comment by seanson** [comment]
I think it would be handy to have a column describing what is to be done with the current channel content if it's not being migrated. For example, the `#argo-helm` channel is used for community maintained Helm charts. Is discussion for these charts to be moved to their respective application channels, a common channel (such as `#argo-community`?) or are the community maintainers expected to manage their own channel separately?

**Comment by edlee2121** [comment]
Unfortunately, there is no easy way to migrate the channel contents. I would manually move any important uploaded content for any channels that you care about. The current slack will be around for a while, so there should be plenty of time to move over content.

**Comment by terrytangyuan** [comment]
FYI, the existing Slack invitation link has been revamped (thanks @alexmt!). It includes the sign-up link to join CNCF Slack workspace as well as links to all the channels related to Argo in that workspace.

https://argoproj.github.io/community/join-slack/

**Comment by seanson** [comment]
> Unfortunately, there is no easy way to migrate the channel contents. I would manually move any important uploaded content for any channels that you care about. The current slack will be around for a while, so there should be plenty of time to move over content.

@edlee2121 - I do not mean the actual text content in the channels, I mean what is to be done with the things that normally happen in these channels if they do not exist in the new Slack (such as the `#argo-helm` channel mentioned).

**Comment by edlee2121** [comment]
@seanson Please create an issue to discuss if we need a new channel (e.g. argo-helm).

**Comment by alexec** [comment]
All channels have now been archived

**Comment by nebulon42** [comment]
FYI going to https://slack.cncf.io/ results in "This link is no longer active.". No idea how you would join.

**Comment by edlee2121** [comment]
The link has expired again.
I've created a ticket with the CNCF service desk to fix the problem.
https://cncfservicedesk.atlassian.net/

**Comment by Disturbing** [comment]
o.o annoying!  :(

**Comment by edlee2121** [comment]
They just updated, but DNS propagation may take a little time.
Here's the direct link:
https://join.slack.com/t/cloud-native/shared_invite/zt-qf54sf2o-28u1ukTk2vGJhvb4um6p8A

**Comment by morningspace** [comment]
Again https://slack.cncf.io/ is expired, "This link is no longer active", is there a way to join? @edlee2121

**Comment by edlee2121** [comment]
Filed ticket with CNCF service desk to fix it again. Please stay tuned.

https://cncfservicedesk.atlassian.net/servicedesk/customer/portal/1/CNCFSD-860?created=true

**Comment by edlee2121** [comment]
Should be fixed now.
Here's the direct link if DNS hasn't updated yet.
https://join.slack.com/t/cloud-native/shared_invite/zt-syaeeuhw-SG7dwkxsHFp2gav3NtFEqQ

**Comment by morningspace** [comment]
Thanks @edlee2121 , it works!

**Comment by drissamri** [comment]
The new link has expired again, sadly @edlee2121

**Comment by edlee2121** [comment]
Opened ticket
https://cncfservicedesk.atlassian.net/servicedesk/customer/portal/1/CNCFSD-904

**Comment by edlee2121** [comment]
It's working again.
