### ISSUE TITLE
code of conduct link is broken

### ISSUE THREAD

**Issue by qrilka** [argoproj/argoproj#50]
Link for "Argo Code of Conduct" on https://github.com/argoproj/argoproj/tree/master/community#contributing-to-argo point to https://github.com/argoproj/argo/blob/master/CODE_OF_CONDUCT.md which does not exits

**Comment by terrytangyuan** [comment]
Thanks. Fixing the link in https://github.com/argoproj/argoproj/pull/51

**Comment by alexec** [comment]
Fixed.
