### ISSUE TITLE
REQUEST: New membership for huikang

### ISSUE THREAD

**Issue by huikang** [argoproj/argoproj#52]
### GitHub Username
huikang

### Organization you are requesting membership in
argoproj

### Requirements
- [x] I have reviewed the community membership guidelines (https://github.com/argoproj/argoproj/blob/master/community/membership.md)
- [x] I have enabled 2FA on my GitHub account (https://github.com/settings/security)
- [x] I am actively contributing to 1 or more Argoproj subprojects
- [x] I have two sponsors that meet the sponsor requirements listed in the community membership guidelines
- [x] I have spoken to my sponsors ahead of this application, and they have agreed to sponsor my application

### Sponsors
- @jessesuen 
- @khhirani

### List of contributions to the Argoproj project
- PRs reviewed / authored
   https://github.com/argoproj/argo-rollouts/commits?author=huikang
   https://github.com/argoproj/argo-rollouts/pull/1080
- Issues responded to
   https://github.com/argoproj/argo-rollouts/issues/1105
   https://github.com/argoproj/argo-rollouts/issues/992

**Comment by jessesuen** [comment]
This was completed early may.
