### ISSUE TITLE
REQUEST: New membership for sbose78 in argoproj-labs

### ISSUE THREAD

**Issue by sbose78** [argoproj/argoproj#55]
### GitHub Username
sbose78

### Organization you are requesting membership in
argoproj-labs

### Requirements
- [x] I have reviewed the community membership guidelines (https://github.com/argoproj/argoproj/blob/master/community/membership.md)
- [x] I have enabled 2FA on my GitHub account (https://github.com/settings/security)
- [x] I am actively contributing to 1 or more Argoproj subprojects
- [x] I have two sponsors that meet the sponsor requirements listed in the community membership guidelines
- [x] I have spoken to my sponsors ahead of this application, and they have agreed to sponsor my application

### Sponsors
- TBD
- TBD

### List of contributions to the Argoproj-labs project

I'm responsible for the design of
* https://github.com/argoproj-labs/argocd-operator
* https://github.com/argoproj-labs/applicationset

Also,
Already a member of https://github.com/argoproj/

**Comment by edlee2121** [comment]
Since you are already a member of argoproj, approved.
