### ISSUE TITLE
HELP about a amd64+arm64 platform

### ISSUE THREAD

**Issue by Thitve** [argoproj/argoproj#56]
HELLO！
When we want to deploy on a heterogeneous platform. AMD64 is the master node, ARM64-Raspberry is the slave node of EDGE. But when we run Argo. The POD assigned by Argo to the ARM64 node failed to function properly. Why is that? Thank you very much!

**Comment by wanghong230** [comment]
Could you move the issue to Argo-CD or Argo-Workflows?

**Comment by jessesuen** [comment]
We built multi-arch images. I think this should work already and this issue is in the wrong repo. Feel free to file new issue with more details in workflow/cd/rollout/event specific repos.
