### ISSUE TITLE
Categorize PRs using labels for reviewer triaging

### ISSUE THREAD

**Issue by sbose78** [argoproj/argoproj#6]
### Proposal

To make it easier for reviewers to pick up PRs to review based on areas of expertise, it would be nice to create labels:

* cli
* UI
* controller
* component/sync
* component/authz
* component/eventbus

( not an exhaustive list )

A PR may have one or more labels.
Some of these could be automatically added based on which part of the code is touched, many others could be added manually while triaging.

**Comment by alexec** [comment]
This has been implemented.
