### ISSUE TITLE
REQUEST: New membership for kostis-codefresh

### ISSUE THREAD

**Issue by kostis-codefresh** [argoproj/argoproj#63]
### GitHub Username
@kostis-codefresh

### Organization you are requesting membership in
@argoproj

### Requirements
- [X] I have reviewed the community membership guidelines (https://github.com/argoproj/argoproj/blob/master/community/membership.md)
- [X] I have enabled 2FA on my GitHub account (https://github.com/settings/security)
- [X] I am actively contributing to 1 or more Argoproj subprojects
- [X] I have two sponsors that meet the sponsor requirements listed in the community membership guidelines
- [X] I have spoken to my sponsors ahead of this application, and they have agreed to sponsor my application

### Sponsors
- @jessesuen 
- @edlee2121 

### List of contributions to the Argoproj project

- PRs reviewed / authored
- https://github.com/argoproj/argo-rollouts/pull/1034
- https://github.com/argoproj/argo-rollouts/pull/1035
- https://github.com/argoproj/argo-rollouts/pull/1042
- https://github.com/argoproj/argo-rollouts/pull/1062
- https://github.com/argoproj/argo-rollouts/pull/1065
- https://github.com/argoproj/argo-rollouts/pull/1093
- https://github.com/argoproj/argo-rollouts/pull/1120
- https://github.com/argoproj/argo-rollouts/pull/1125
- https://github.com/argoproj/argo-rollouts/pull/1143
- https://github.com/argoproj/argo-rollouts/pull/1211
- https://github.com/argoproj/argo-rollouts/pull/1269

- Projects I am involved with: Argo Rollouts

**Comment by jessesuen** [comment]
@edlee2121 can you approve (thumbs up) this?

**Comment by edlee2121** [comment]
Approved

**Comment by jessesuen** [comment]
Completed
