### ISSUE TITLE
Vote to affirm updated project governance  

### ISSUE THREAD

**Issue by hblixt** [argoproj/argoproj#70]
The Argo Project is a well-functioning driven community project, with involvement from users, contributors and vendors where decisions by consensus has been the norm since the project was accepted by the CNCF.

As the project is growing in adoption and contributions and on recommendation by the TOC as part of the graduation process, the project governance was updated to include practices already in use and to clarify the voting process. The intent is still to continue to run the project by consensus, but there will now be a documented path to resolution, in the event of a decision where consensus can't be reached. Limits were also put in place to make sure no single entity can get a majority influence over the project. 

As per bootstrap committee decision in June of this year and the associated  [PR](https://github.com/argoproj/argoproj/pull/60), the Argo [governance documentation](https://github.com/argoproj/argoproj/blob/master/community/GOVERNANCE.md) has been updated to align with those aforementioned procedures and processes that were already in place but not fully documented. 

This issue is for the [maintainers](https://github.com/argoproj/argoproj/blob/master/MAINTAINERS.md) to affirm these changes. 

Please vote by adding a +1/-1 and indicate whether your vote is binding (maintainer) or non-binding (community).
Non-binding votes by the community are encouraged!

This vote will close in two weeks, on Sunday August 8th, at 10.30 pm Pacific Time.

**Comment by terrytangyuan** [comment]
+1 (binding)

**Comment by edlee2121** [comment]
+1 binding

**Comment by alexmt** [comment]
+1 (binding)

**Comment by VaibhavPage** [comment]
+1 binding

**Comment by jannfis** [comment]
+1 binding

**Comment by jessesuen** [comment]
+1 binding

**Comment by hblixt** [comment]
+1 binding

**Comment by wtam2018** [comment]
+1 binding

**Comment by ishitasequeira** [comment]
+1 binding

**Comment by reginapizza** [comment]
+1 binding

**Comment by sbose78** [comment]
+1 binding

**Comment by dtaniwaki** [comment]
+1 binding

**Comment by xianlubird** [comment]
+1 binding

**Comment by chetan-rns** [comment]
+1 binding

**Comment by simster7** [comment]
+1 binding

**Comment by whynowy** [comment]
+1 binding

**Comment by alexec** [comment]
+1 binding

**Comment by mayzhang2000** [comment]
+1 binding

**Comment by wanghong230** [comment]
+1 binding

**Comment by todaywasawesome** [comment]
+1 binding

**Comment by jgwest** [comment]
+1 binding

**Comment by khhirani** [comment]
+1 binding

**Comment by sarabala1979** [comment]
+1 binding

**Comment by dthomson25** [comment]
+1 (binding)

**Comment by hblixt** [comment]
Two weeks has passed, closing the vote. 
Result:
24 votes
23 binding +1
1 non-binding +1 (mis-labeled as binding)

The vote has passed. The governance changes are affirmed. 
Thanks everyone for voting!
