### ISSUE TITLE
REQUEST: New membership for tczhao

### ISSUE THREAD

**Issue by tczhao** [argoproj/argoproj#89]
### GitHub Username
@tczhao

### Organization you are requesting membership in
@argoproj

### Requirements
- [x] I have reviewed the community membership guidelines (https://github.com/argoproj/argoproj/blob/master/community/membership.md)
- [x] I have enabled 2FA on my GitHub account (https://github.com/settings/security)
- [x] I am actively contributing to 1 or more Argoproj subprojects
- [x] I have two sponsors that meet the sponsor requirements listed in the community membership guidelines
- [x] I have spoken to my sponsors ahead of this application, and they have agreed to sponsor my application

### Sponsors
- @alexec
- @whynowy 

### List of contributions to the Argoproj project
- PRs reviewed / authored (35)
- https://github.com/argoproj/argo-workflows/pulls?q=is%3Apr+author%3Atczhao+is%3Amerged
- https://github.com/argoproj/argo-events/pulls?q=is%3Apr+author%3Atczhao+is%3Amerged
- Issues responded to (13)
- https://github.com/argoproj/argo-workflows/issues?q=is%3Aissue+tczhao+is%3Aclosed
- Projects I am involved with 
- Argo-workflows
- Argo-events

---

Have your sponsoring reviewers reply confirmation of sponsorship: +1

**Comment by whynowy** [comment]
+1

**Comment by alexec** [comment]
+1

**Comment by alexec** [comment]
You should now have a member invite!

**Comment by alexec** [comment]
@tczhao you’ve been reviewing many PRs. Perhaps you’d like to apply to be promoted to reviewer?

**Comment by tczhao** [comment]
> @tczhao you’ve been reviewing many PRs. Perhaps you’d like to apply to be promoted to reviewer?

Thanks, I'm honored, let me create the relevant issue/PR
