### ISSUE TITLE
Introducing contributor experience sessions

### ISSUE THREAD

**Issue by sbose78** [argoproj/argoproj#9]
One of the things we propose is to have a **Contributor Experience Office hours** as mentioned by @jessesuen in the community meeting today.

I'm requesting feedback on : 

**Which topics would you wish to have covered in a workshop/presentation model ?**

The initial session will target the following:
* Development environment setup.
* Help triage "first good issues" for folks to get started.

Let us know what you think!

**Comment by alexmt** [comment]
Thank you for creating this issue, @sbose78 ! 

I'm proposing to add  "Argo CD Architecture Overview" topic to the first meeting. In this topic, we can describe components included in Argo CD, each component's responsibility, data flow, and performance bottlenecks. What do you think?

More ideas on advanced topics for next meetings:

* Application controller: controller architecture, how to make changes in gitops-engine and test locally
* API: how to prepare dev environment ( we use a lot of code generation - thank you golang :) ), how to change Argo CD API.
* Manifest generation: how Argo CD access git/helm repository, credentials management, config management tools integration
* E2E tests infrastructure: how to run e2e tests locally, how to leverage e2e tests to quickly seed Argo CD configuration
* UI: State management in Argo CD UI, Base components library

**Comment by edlee2121** [comment]
Let's also reserve some time for folks to introduce themselves.

@alexmt Please post an announcement for the office hours on the argo-dev slack channel with an agenda for the first meeting when you're ready.

**Comment by alexmt** [comment]
First meeting recording and presentation: 

https://youtu.be/2U3nE98EzNk
[presentation.pdf](https://github.com/argoproj/argoproj/files/5228501/presentation.pdf)

Next meeting agenda items so far:

1. Debugging a Remote ArgoCD Environment with Telepresence.
1. 1.7 release postmortem
1. 1.8 issues prioritization 

Please let us know if you want to discuss anything else

**Comment by sbose78** [comment]
Thank you for the recording!

**Comment by sbose78** [comment]
> 1.7 release postmortem
   1.8 issues prioritization

Agenda looks good!

**Comment by alexmt** [comment]
Hello everyone,

Sep 15th meeting recording: https://www.youtube.com/watch?v=Sti5EEONhi4&feature=youtu.be&ab_channel=ArgoProj
Presented document: https://docs.google.com/document/d/1g12zUAp9fiPzDuNq4SAUGsWyZhL0aQwnCssppXm25Jk/edit

Created two issues as follow up: 
* E2E test that verifies popular Helm charts deployment (https://github.com/argoproj/argo-cd/issues/4392)
* Automated smoke test that mimics user behavior UI and CLI  (https://github.com/argoproj/argo-cd/issues/4393)

**Comment by sbose78** [comment]
I'm looking for a refresher on the RBAC objects that are used today, to be able to better understand the service-ability of ArgoCD installations 

https://github.com/argoproj/argo-cd/blob/master/manifests/install.yaml

Even those these operator-based issues got me thinking, I have general questions on RBAC ( "who should have how much") 
* https://github.com/argoproj-labs/argocd-operator/issues/154
* https://github.com/argoproj-labs/argocd-operator/issues/125
* https://github.com/argoproj-labs/argocd-operator/issues/107

**Comment by sbose78** [comment]
Feedback session notes:

* Would be good to have more UI/UX oversight and organization
* More contributors need too be reviewing PRs
* Clearer PR descriptions.
* Could have smaller focused PRs
* Issue triaging has been good
* The Getting Started experience was good
* Need to ensure PRs<->Issues are linked better.
* Improve the grooming process ( 1st pass could be offline, and then present it during the contributor office hours ) 
* Label PRs per milestone
* Mark issues/PRs as "needs-discussion" and invite folks to present proposals at community meetings
* Add docs on the code structure.

**Comment by jopit** [comment]
Is there a link to the recording of the Oct 1st meeting recording?  I don't see it in the Argo Proj YouTube channel.
