### ISSUE TITLE
REQUEST: New membership for dinever

### ISSUE THREAD

**Issue by dinever** [argoproj/argoproj#94]
### GitHub Username

@dinever

### Organization you are requesting membership in

@argoproj

### Requirements
- [x] I have reviewed the community membership guidelines (https://github.com/argoproj/argoproj/blob/master/community/membership.md)
- [x] I have enabled 2FA on my GitHub account (https://github.com/settings/security)
- [x] I am actively contributing to 1 or more Argoproj subprojects
- [x] I have two sponsors that meet the sponsor requirements listed in the community membership guidelines
- [x] I have spoken to my sponsors ahead of this application, and they have agreed to sponsor my application

### Sponsors
- @alexec
- @sarabala1979 

### List of contributions to the Argoproj project
- PRs reviewed / authored: https://github.com/argoproj/argo-workflows/pulls?q=is%3Apr+author%3Adinever+is%3Aclosed
- Issues responded to: https://github.com/argoproj/argo-workflows/issues?q=is%3Aissue+involves%3Adinever+is%3Aopen
- Projects I am involved with: Argo Workflows

**Comment by sarabala1979** [comment]
+1
