### ISSUE TITLE
REQUEST: New membership for @agrawroh

### ISSUE THREAD

**Issue by agrawroh** [argoproj/argoproj#98]
### GitHub Username
e.g. @agrawroh

### Organization you are requesting membership in
e.g. @argoproj/argo-rollouts @argoproj

### Requirements
- [X] I have reviewed the community membership guidelines (https://github.com/argoproj/argoproj/blob/master/community/membership.md)
- [X] I have enabled 2FA on my GitHub account (https://github.com/settings/security)
- [X] I am actively contributing to 1 or more Argoproj subprojects
- [X] I have two sponsors that meet the sponsor requirements listed in the community membership guidelines
- [X] I have spoken to my sponsors ahead of this application, and they have agreed to sponsor my application

### Sponsors
- @jessesuen 
- @huikang 

#### PRs Authored

- https://github.com/argoproj/argo-rollouts/pull/1380
- https://github.com/argoproj/argo-rollouts/pull/1414
- https://github.com/argoproj/argo-rollouts/pull/1420
- https://github.com/argoproj/argo-rollouts/pull/1454
- https://github.com/argoproj/argo-rollouts/pull/1460

#### PRs Reviewed

- https://github.com/argoproj/argo-rollouts/pull/1443

#### Issues responded to

- https://github.com/argoproj/argo-rollouts/issues/1364
- https://github.com/argoproj/argo-rollouts/issues/1617

#### Projects I'm Involved With

@argoproj/argo-rollouts

Looking forward to working with you all and making Argo Rollouts more awesome! 🎉

**Comment by huikang** [comment]
I am not a maintainer yet, but fully support @agrawroh 's membmership

**Comment by alexmt** [comment]
I support @agrawroh's membership as well

**Comment by sbose78** [comment]
+1

**Comment by jessesuen** [comment]
Completed!
